/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Evidence = {id:string;dimension:string;claim:string;reference?:string;status:string;proof_of_fit:boolean;gap?:string};
type Candidate = {id:string;project:string;version:string;revision:string;provider_repository:string;evidence:Evidence[];coverage:Record<string,string>;blockers:string[]};
type Workspace = {id:string;title:string;outcome:string;origin:{kind:string;resource_id:string;revision?:string};required_journeys:string[];environments:{name:string;platform:string;version?:string}[];constraints:string[];budget:string;owner_ids:string[];evaluation_criteria:{id:string;description:string;required:boolean}[];participants:{id:string;kind:string;subject_id:string;role:string;consent:string;evidence_access:string}[];candidates:Candidate[];authority_granted:boolean};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);
async function request<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(`/api${path}`,{...init,headers:{"content-type":"application/json",...init?.headers}});if(!r.ok){const x=await r.json().catch(()=>({error:"unavailable"}));throw new Error(String(x.error).replaceAll("_"," "))}return r.json()}

export function AdoptionWorkspaces(){
  const [items,setItems]=useState<Workspace[]>([]),[selected,setSelected]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const x=await request<{items:Workspace[]}>("/adoption-workspaces");setItems(x.items);if(!selected&&x.items[0])setSelected(x.items[0].id);setError("")}catch(e){setError((e as Error).message)}},[selected]);
  useEffect(()=>{void load()},[load]);
  async function submit(e:FormEvent<HTMLFormElement>,path:string,make:(f:FormData)=>unknown){e.preventDefault();const form=e.currentTarget;try{const x=await request<Workspace>(path,{method:"POST",body:JSON.stringify(make(new FormData(form)))});setSelected(x.id);form.reset();await load()}catch(err){setError((err as Error).message)}}
  const current=items.find(x=>x.id===selected);
  return <div className="page-stack">
    <header className="page-header"><div><Badge tone="teal">Shared fit evaluation</Badge><h1>Software adoption</h1><p>Compare exact candidate versions against real journeys and inspectable evidence—not demos or popularity.</p></div></header>
    {error&&<p className="notice error" role="alert">{error}</p>}
    <section className="card"><h2>Open an adoption workspace</h2><form className="stacked-form" onSubmit={e=>submit(e,"/adoption-workspaces",f=>({title:f.get("title"),outcome:f.get("outcome"),origin:{kind:f.get("origin_kind"),resource_id:f.get("origin_id"),revision:f.get("origin_revision")||undefined},required_journeys:lines(f.get("journeys")),environments:[{name:f.get("environment"),platform:f.get("platform"),version:f.get("platform_version")||undefined}],constraints:lines(f.get("constraints")),budget:f.get("budget"),owner_ids:lines(f.get("owners")),evaluation_criteria:lines(f.get("criteria")).map((description,i)=>({id:`criterion-${i+1}`,description,required:true})),visibility:f.get("visibility")}))}>
      <input name="title" placeholder="Workspace title" required/><textarea name="outcome" placeholder="Outcome this dependency must enable" required/><select name="origin_kind" defaultValue="roadmap_outcome">{["roadmap_outcome","support_gap","incubator","decision","package","api","federated_repository"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input name="origin_id" placeholder="Origin resource ID" required/><input name="origin_revision" placeholder="Exact origin revision (when available)"/><textarea name="journeys" placeholder="Required journeys, one per line" required/><input name="environment" placeholder="Environment name" required/><input name="platform" placeholder="Platform" required/><input name="platform_version" placeholder="Platform version"/><textarea name="constraints" placeholder="Constraints, one per line"/><input name="budget" placeholder="Budget boundary" required/><textarea name="owners" placeholder="Owner IDs, one per line" required/><textarea name="criteria" placeholder="Evaluation criteria, one per line" required/><select name="visibility" defaultValue="participants"><option value="participants">Participants</option><option value="public">Public</option></select><Button type="submit">Open workspace</Button>
    </form></section>
    {items.length>0&&<label className="card">Workspace<select value={selected} onChange={e=>setSelected(e.target.value)}>{items.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}
    {current&&<section className="card"><h2>{current.title}</h2><p>{current.outcome}</p><p><strong>Need:</strong> {current.origin.kind.replaceAll("_"," ")} · {current.origin.resource_id}{current.origin.revision&&` @ ${current.origin.revision}`}</p><p><strong>Budget:</strong> {current.budget} · <strong>Owners:</strong> {current.owner_ids.join(", ")}</p><p><strong>Journeys:</strong> {current.required_journeys.join(" · ")}</p><p><strong>Environments:</strong> {current.environments.map(x=>`${x.name} (${x.platform}${x.version?` ${x.version}`:""})`).join(" · ")}</p><p className="notice"><strong>No authority granted:</strong> this workspace records evaluation context and evidence only.</p>
      <details><summary>Invite a participant</summary><form className="stacked-form" onSubmit={e=>submit(e,`/adoption-workspaces/${current.id}/participants`,f=>({kind:f.get("role")==="read_only_agent"?"agent":"human",subject_id:f.get("subject"),role:f.get("role"),evidence_access:f.get("access")}))}><input name="subject" placeholder="User or exact agent identity" required/><select name="role"><option value="provider_maintainer">Provider maintainer</option><option value="affected_user">Affected user</option><option value="read_only_agent">Read-only agent</option></select><select name="access"><option value="shared">Shared evidence</option><option value="provider">Provider evidence</option></select><Button type="submit" size="sm">Invite</Button></form></details>
      <details><summary>Add an exact candidate version</summary><form className="stacked-form" onSubmit={e=>submit(e,`/adoption-workspaces/${current.id}/candidates`,f=>({project:f.get("project"),provider_repository:f.get("repository"),version:f.get("version"),revision:f.get("revision")}))}><input name="project" placeholder="Project" required/><input name="repository" placeholder="Provider or federated repository" required/><input name="version" placeholder="Declared version" required/><input name="revision" placeholder="Exact revision" required/><Button type="submit" size="sm">Add candidate</Button></form></details>
      {current.candidates.map(c=><article className="sub-card" key={c.id}><h3>{c.project} {c.version}</h3><p><code>{c.revision}</code> · {c.provider_repository}</p><div className="badge-row">{Object.entries(c.coverage).sort().map(([d,s])=><Badge key={d} tone={s==="supported"?"teal":"amber"}>{d.replaceAll("_"," ")}: {s}</Badge>)}</div>{c.blockers.length>0&&<><h4>Fit gaps</h4><ul>{c.blockers.map(x=><li key={x}>{x}</li>)}</ul></>}
        <details><summary>Add capability or risk evidence</summary><form className="stacked-form" onSubmit={e=>submit(e,`/adoption-workspaces/${current.id}/candidates/${c.id}/evidence`,f=>({dimension:f.get("dimension"),claim:f.get("claim"),reference:f.get("reference")||undefined,revision:f.get("revision"),visibility:f.get("evidence_visibility"),availability:f.get("availability")}))}><select name="dimension">{["capability","provenance","support","security","data_use","compatibility","gap"].map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select><textarea name="claim" placeholder="Declared claim or known gap" required/><input name="reference" placeholder="Inspectable evidence reference"/><input name="revision" defaultValue={c.revision} required/><select name="evidence_visibility"><option value="public">Public</option><option value="shared">Workspace participants</option><option value="provider">Provider-scoped</option></select><select name="availability"><option value="available">Available</option><option value="unavailable">Unavailable gap</option></select><Button type="submit" size="sm">Record evidence</Button></form></details>
        {c.evidence.map(e=><p key={e.id}><Badge tone={e.proof_of_fit?"teal":"amber"}>{e.status}</Badge> <strong>{e.dimension}</strong> — {e.claim}{e.reference&&<> · <code>{e.reference}</code></>}{e.gap&&<> · {e.gap}</>}</p>)}
      </article>)}
    </section>}
  </div>
}
