"use client";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Release = { id: string; version: string; commit_id: string };
type Bundle = { id: string; release_id: string; verification: { payload_sha256: string } };
type Finding = { kind: string; detail: string; owner_id?: string; reference?: string; blocking: boolean };
type Definition = { number: number; release_id: string; release_version: string; release_revision: string; title: string; why: string; target_audiences: { id: string; name: string; kind: string; desired_coverage: number; owner_id: string }[]; supported_starting_versions: { version: string; supported: boolean; upgrade_path?: string; owner_id: string }[]; deadline: string; success_measures: { id: string; description: string; target: number; unit: string; evidence: string; owner_id: string }[]; support_policy: string; rollback_policy: string; owner_ids: string[]; links: { kind: string; resource_id: string; revision: string; summary: string; owner_id: string }[]; compatibility_requirements: { subject: string; requirement: string; starting_versions: string[]; owner_id: string }[]; author_id: string; change_reason: string };
type Campaign = { id: string; current_version: number; versions: Definition[]; findings: Finding[]; authority_granted: boolean };

export function AdoptionCampaigns({ repository, owner }: { repository: string; owner: boolean }) {
  const [releases, setReleases] = useState<Release[]>([]); const [bundles, setBundles] = useState<Bundle[]>([]); const [items, setItems] = useState<Campaign[]>([]); const [error, setError] = useState("");
  const load = useCallback(async () => { const [rr, cr] = await Promise.all([fetch(`/api/repositories/${repository}/releases?per_page=100`), fetch(`/api/repositories/${repository}/adoption-campaigns`)]); if (cr.ok) setItems(((await cr.json()) as {items:Campaign[]}).items); if (!rr.ok) return; const rel=((await rr.json()) as {items:Release[]}).items; setReleases(rel); const lists=await Promise.all(rel.map(async x=>{const r=await fetch(`/api/repositories/${repository}/releases/${x.id}/provenance-bundles`);return r.ok?((await r.json()) as {items:Bundle[]}).items:[]}));setBundles(lists.flat()); }, [repository]);
  useEffect(()=>{
    // Campaigns and attestations are durable server state selected by repository.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);let body:unknown;try{body=JSON.parse(String(form.get("definition")))}catch{setError("Invalid campaign JSON.");return}const response=await fetch(`/api/repositories/${repository}/adoption-campaigns`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError(((await response.json()) as {error:string}).error.replaceAll("_"," "));return}setError("");await load()}
  const selected=releases.find(x=>bundles.some(b=>b.release_id===x.id)); const bundle=bundles.find(x=>x.release_id===selected?.id);
  const template=selected&&bundle?JSON.stringify({release_id:selected.id,release_version:selected.version,release_revision:selected.commit_id,provenance_bundle_id:bundle.id,provenance_bundle_digest:bundle.verification.payload_sha256,title:`Adopt ${selected.version}`,why:"State the user and project outcome this release enables.",target_audiences:[{id:"package-consumers",name:"Package consumers",kind:"package_consumers",desired_coverage:80,owner_id:""}],supported_starting_versions:[{version:"previous",supported:true,upgrade_path:"documentation:upgrade",owner_id:""}],deadline:"2030-01-31T23:59:59Z",success_measures:[{id:"coverage",description:"Eligible consumers verified on the release",target:80,unit:"percent",evidence:"repository-visible adoption evidence",owner_id:""}],support_policy:"Name support channels, response expectations, and duration.",rollback_policy:"Name supported rollback conditions and destination.",owner_ids:[""],links:[{kind:"documentation",resource_id:"upgrade-guide",revision:selected.commit_id,summary:"Upgrade guidance",owner_id:""}],compatibility_requirements:[{subject:"supported runtime",requirement:"State required runtime and dependency versions.",starting_versions:["previous"],owner_id:""}],change_reason:"Open adoption as a collaborative release outcome"},null,2):"";
  return <section className="panel"><p className="eyebrow">Attested release → accountable audiences → measurable adoption</p><div className="section-heading"><div><h2>Release adoption campaigns</h2><p>Make who should adopt, why it matters, and what success means a versioned project commitment—not an inference from publication or downloads.</p></div><Badge>{items.length} campaigns</Badge></div>
    {error&&<p role="alert" className="form-error">{error}</p>}{owner&&template&&<details><summary>Open a campaign from an attested release</summary><form className="workspace-form" onSubmit={create}><label>Versioned campaign definition<textarea name="definition" rows={24} defaultValue={template} required/></label><p>Release identity and signed bundle digest are frozen. Repository authority, consumer authority, deployment, and rollback remain governed by their ordinary controls.</p><Button type="submit">Open adoption campaign</Button></form></details>}{owner&&!template&&<p>Publish an exact signed provenance bundle before opening an adoption campaign.</p>}
    {items.map(c=>{const v=c.versions[c.versions.length-1];return <article className="workspace-card" key={c.id}><div className="section-heading"><div><h3>{v.title}</h3><p>{v.release_version} · <code>{v.release_revision.slice(0,12)}</code> · campaign <code>{c.id}</code> · version {c.current_version}</p></div><Badge>{c.findings.some(x=>x.blocking)?"blocked":"defined"}</Badge></div><p>{v.why}</p><p><strong>Deadline:</strong> {new Date(v.deadline).toLocaleString()} · <strong>owners:</strong> {v.owner_ids.join(", ")||"missing"}</p><h4>Audiences and coverage</h4>{v.target_audiences.map(a=><p key={a.id}><Badge>{a.kind.replaceAll("_"," ")}</Badge> <strong>{a.name}</strong> · {a.desired_coverage}% desired · owner {a.owner_id||"missing"}</p>)}<h4>Starting versions</h4>{v.supported_starting_versions.map(s=><p key={s.version}><Badge>{s.supported?"supported":"unsupported"}</Badge> {s.version} → {s.upgrade_path||"no upgrade path"} · owner {s.owner_id||"missing"}</p>)}<h4>Success, support, and rollback</h4>{v.success_measures.map(m=><p key={m.id}><strong>{m.description}:</strong> {m.target} {m.unit} · evidence {m.evidence} · owner {m.owner_id||"missing"}</p>)}<p><strong>Support:</strong> {v.support_policy}<br/><strong>Rollback:</strong> {v.rollback_policy}</p><details><summary>Adopter context and compatibility</summary>{v.links.map((x,i)=><p key={i}><Badge>{x.kind}</Badge> {x.summary} · <code>{x.resource_id}@{x.revision.slice(0,12)}</code> · owner {x.owner_id||"missing"}</p>)}{v.compatibility_requirements.map((x,i)=><p key={i}><strong>{x.subject}:</strong> {x.requirement} · from {x.starting_versions.join(", ")} · owner {x.owner_id||"missing"}</p>)}</details>{c.findings.map((f,i)=><p className={f.blocking?"form-error":""} key={`${f.kind}-${i}`}><Badge>{f.blocking?"blocking":"attributed change"}</Badge> <strong>{f.kind.replaceAll("_"," ")}:</strong> {f.detail}{f.reference&&` · ${f.reference}`}{f.owner_id&&` · owner ${f.owner_id}`}</p>)}<p><small>Campaign records coordinate evidence and commitments only; authority granted: {String(c.authority_granted)}.</small></p></article>})}
  </section>;
}
