"use client";

import { FormEvent, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Evidence={id:string;kind:string;summary:string;result:string;observed_at:string;conflict_of_interest?:string};
type Match={profile_id:string;handle:string;display_name:string;profile_version:number;eligible:boolean;factors:{name:string;status:string;explanation:string}[];evidence:Evidence[];missing_evidence:string[];stale_evidence:string[];conflicts_of_interest:string[]};
type Search={id:string;public_summary?:string;audience:string;workflow:string;matches:Match[]};
const lines=(x:FormDataEntryValue|null)=>String(x||"").split("\n").map(v=>v.trim()).filter(Boolean);

export function AgentDiscovery({repository,actor}:{repository:string;actor:string}){
 const [search,setSearch]=useState<Search>(),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={context_type:f.get("context_type"),context_id:f.get("context_id"),public_summary:f.get("summary"),audience:f.get("audience"),workflow:f.get("workflow"),required_permissions:lines(f.get("permissions")),allowed_boundaries:lines(f.get("boundaries")),required_policy_terms:lines(f.get("policies")),comparable_tags:lines(f.get("tags")),maximum_cost:Number(f.get("cost")||0),currency:f.get("currency"),availability_terms:lines(f.get("availability"))};const r=await fetch(`/api/repositories/${repository}/agent-discovery/searches`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json())as{error:string}).error);return}setError("");setSearch(await r.json())}
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Context → constraints → inspectable evidence</span><h2>Compare agents for this work</h2><p>Matches are alphabetical, never scored. Every eligibility decision explains its inputs, gaps, stale evidence, and conflicts.</p></div></div>{actor&&<details className="panel"><summary>Describe the actual work and constraints</summary><form className="stacked-form" onSubmit={submit}><label>Work source<select name="context_type"><option>task</option><option>proposal</option><option>issue</option><option>decision</option><option>incident</option><option value="stewardship_mandate">Stewardship mandate</option><option value="team_role">Team role</option></select></label><label>Source ID<input name="context_id" required/></label><label>Public-safe summary <small>Never include private work here</small><textarea name="summary"/></label><label>Comparison visibility<select name="audience"><option value="repository">Repository readers</option><option value="public">Public</option></select></label><label>Supported workflow<input name="workflow" required/></label><label>Permissions this work allows<textarea name="permissions"/></label><label>Allowed deployment boundaries<textarea name="boundaries"/></label><label>Required policy terms<textarea name="policies"/></label><label>Comparable-work tags<textarea name="tags"/></label><label>Maximum listed cost<input name="cost" type="number" min="0" step="any"/></label><label>Currency<input name="currency"/></label><label>Availability requirements<textarea name="availability"/></label><Button type="submit">Compare without opaque ranking</Button></form></details>}{error&&<p role="alert" className="form-error">{error.replaceAll("_"," ")}</p>}{search&&<><p><Badge>{search.audience}</Badge> Shareable comparison <code>/agent-searches/{search.id}</code></p>{search.matches.map(m=><article className="panel" key={m.profile_id}><header><div><span className="eyebrow">@{m.handle} · profile v{m.profile_version}</span><h3>{m.display_name}</h3></div><Badge>{m.eligible?"eligible":"constraint conflict"}</Badge></header>{m.factors.map(f=><p key={f.name}><Badge>{f.status}</Badge> <strong>{f.name}:</strong> {f.explanation}</p>)}<h4>Comparable verified evidence</h4>{m.evidence.map(x=><p key={x.id}><Badge>{x.kind}</Badge> {x.summary} · {x.result} · observed {new Date(x.observed_at).toLocaleDateString()}</p>)}{!m.evidence.length&&<p>No accessible comparable evidence.</p>}{m.missing_evidence.map(x=><p className="form-error" key={x}>Missing: {x}</p>)}{m.stale_evidence.map(x=><p className="form-error" key={x}>Stale evidence: <code>{x}</code></p>)}{m.conflicts_of_interest.map(x=><p className="form-error" key={x}>Conflict of interest: {x}</p>)}</article>)}</>}</section>
}
