"use client";
import {useCallback,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";

type Query={id:string;control_version:number;control_id:string;name:string;kind:string;source:string;schedule:string;freshness_hours:number;audience:string;transformations:string[]};
type EvidenceRecord={query_id:string;source_record_id:string;source_revision:string;observed_at:string;result:string};
type Package={id:string;control_version:number;control_id:string;period_start:string;period_end:string;collected_at:string;records:EvidenceRecord[];coverage:Record<string,string>;gaps:{kind:string;query_id?:string;detail:string}[];fresh:boolean;package_hash:string;attestation:string};
const queryStarter=JSON.stringify({control_version:1,control_id:"control-id",name:"Merged reviews",kind:"review",source:"/repositories/{repository}/pulls",selector:{state:"merged"},schedule:"0 2 * * *",freshness_hours:48,audience:"public",transformations:["count by reviewer"]},null,2);
const packageStarter=JSON.stringify({control_version:1,control_id:"control-id",period_start:"2026-08-01T00:00:00Z",period_end:"2026-09-01T00:00:00Z",records:[]},null,2);

export function AssuranceEvidence({repository,program,actor}:{repository:string;program:string;actor:string}){
  const root=`/api/repositories/${repository}/assurance-programs/${program}/evidence`,[data,setData]=useState<{queries:Query[];packages:Package[]}>({queries:[],packages:[]}),[error,setError]=useState("");
  const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setData(await r.json() as {queries:Query[];packages:Package[]})},[root]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function submit(e:React.FormEvent<HTMLFormElement>,kind:"queries"|"packages"){e.preventDefault();try{const f=new FormData(e.currentTarget),r=await fetch(`${root}/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:String(f.get("definition"))});if(!r.ok){setError((await r.json() as {error:string}).error);return}setError("");await load()}catch{setError("invalid_evidence_json")}}
  return <section><h4>Continuous assurance evidence</h4><p>Queries bind platform source records to exact control versions and periods. Packages retain provenance and gaps; visible records are limited to this viewer&apos;s audience.</p>{error&&<p className="form-error">{error.replaceAll("_"," ")}</p>}{actor&&<details><summary>Define an evidence query</summary><form className="workspace-form" onSubmit={e=>void submit(e,"queries")}><textarea name="definition" defaultValue={queryStarter} rows={12}/><Button type="submit">Save query and schedule</Button></form></details>}{data.queries.map(q=><p key={q.id}><Badge>{q.kind}</Badge> <strong>{q.name}</strong> · control v{q.control_version}/{q.control_id} · {q.schedule} · fresh within {q.freshness_hours}h · {q.audience}<br/><code>{q.source}</code>{q.transformations.length>0&&<> · transformations: {q.transformations.join(", ")}</>}</p>)}{actor&&<details><summary>Assemble an immutable package</summary><form className="workspace-form" onSubmit={e=>void submit(e,"packages")}><textarea name="definition" defaultValue={packageStarter} rows={10}/><Button type="submit">Collect source evidence</Button></form></details>}{data.packages.map(p=><article key={p.id}><p><Badge>{p.fresh?"fresh":"gaps"}</Badge> <strong>Control v{p.control_version}/{p.control_id}</strong> · {new Date(p.period_start).toLocaleDateString()}–{new Date(p.period_end).toLocaleDateString()} · {p.records.length} visible records</p><p>Coverage: {Object.entries(p.coverage).map(([q,v])=>`${q}: ${v}`).join(", ")||"no queries"}<br/>Package <code>{p.package_hash}</code><br/>Attestation <code>{p.attestation}</code></p>{p.gaps.length>0&&<ul>{p.gaps.map((g,i)=><li key={`${g.kind}-${i}`}><Badge>{g.kind}</Badge> {g.detail}</li>)}</ul>}</article>)}</section>
}
