"use client";

import { useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Removal={id:string;revision:number;state:string;active_stage_id:string;compatibility:string;next_action:string;input:{plan_id:string;proof_id:string;candidate_revision:string;owner_ids:string[];stages:{id:string;name:string;required_evidence:string[];max_remaining_use:number;rollback_boundary:string}[]};delivery_evidence:{id:string;stage_id:string;kind:string;status:string;resource_id:string;revision:string;reference:string}[];signals:{id:string;stage_id:string;remaining_use:number;health:string;control:string;environment:string;release:string;evidence_reference:string;next_action:string}[];unexpected_consumers:{id:string;consumer_id:string;summary:string;evidence_reference:string}[];controls:{id:string;action:string;rationale:string;owner_id:string}[];blockers:{kind:string;subject:string;detail:string}[];completion?:{completed_revision:string;outcome_measures:string[];cleanup:{category:string;subject:string;status:string;evidence_reference:string}[]}};
const starter=JSON.stringify({plan_id:"plan-id",proof_id:"proof-id",candidate_revision:"exact-candidate-revision",owner_ids:["owner-id"],stages:[{id:"disable",name:"Disable new use",plan_stage_id:"notice",required_evidence:["merge_queue","release","documentation"],max_remaining_use:0,rollback_boundary:"reversible"},{id:"remove",name:"Remove obsolete machinery",plan_stage_id:"removal",required_evidence:["merge_queue","release","schema_migration","infrastructure_migration","documentation","protected_environment"],max_remaining_use:0,rollback_boundary:"irreversible"}]},null,2);

export function CapabilityRemovals({repository,actor}:{repository:string;actor:string}){
  const root=`/api/repositories/${repository}/capability-removals`,[items,setItems]=useState<Removal[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems((await r.json() as {items:Removal[]}).items)},[root]);useEffect(()=>{void load()},[load]);
  async function send(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:typeof body==="string"?body:JSON.stringify(body)});if(!r.ok){setError((await r.json() as {error:string}).error);return}setError("");await load()}
  return <section className="investigation-workspace"><div className="section-heading"><div><p className="eyebrow">Controlled delivery to verified product outcome</p><h2>Staged removal</h2><p>Track ordinary delivery, remaining use, health, rollback limits, and complete cleanup without turning this record into deployment authority.</p></div><Badge>{items.length} removals</Badge></div>
    {error&&<p className="form-error" role="alert">{error.replaceAll("_"," ")}</p>}
    {actor&&<details className="workspace-card"><summary>Start from current approved proof</summary><form className="workspace-form" onSubmit={e=>{e.preventDefault();void send(root,String(new FormData(e.currentTarget).get("input")))}}><textarea name="input" defaultValue={starter} rows={22} required/><Button type="submit">Start controlled removal</Button></form></details>}
    {items.map(r=>{const stage=r.input.stages.find(x=>x.id===r.active_stage_id),signal=r.signals.findLast(x=>x.stage_id===r.active_stage_id),owner=r.input.owner_ids.includes(actor);return <article className="workspace-card" key={r.id}><div className="section-heading"><div><h3>{stage?.name||"Verified removal"}</h3><p>Plan <code>{r.input.plan_id}</code> · proof <code>{r.input.proof_id}</code> · candidate <code>{r.input.candidate_revision}</code></p></div><Badge>{r.state}</Badge></div>
      <p><strong>Compatibility:</strong> {r.compatibility} · <strong>rollback boundary:</strong> {stage?.rollback_boundary||"passed"} · <strong>next action:</strong> {r.next_action}</p>
      <h4>Remaining use, health, and control</h4><p>{signal?<><Badge>{signal.health}</Badge> remaining old use {signal.remaining_use} · control {signal.control} · {signal.environment} / {signal.release} · <code>{signal.evidence_reference}</code></>:"No current stage signal"}</p>
      <h4>Ordinary delivery evidence</h4><ul>{stage?.required_evidence.map(k=>{const e=r.delivery_evidence.findLast(x=>x.stage_id===stage.id&&x.kind===k);return <li key={k}><Badge>{e?.status||"missing"}</Badge> {k}{e&&<> · <code>{e.resource_id}@{e.revision}</code> · {e.reference}</>}</li>})}</ul>
      {r.blockers.length>0&&<><h4>Pause and removal blockers</h4><ul>{r.blockers.map((b,i)=><li key={`${b.kind}-${i}`}><Badge>{b.kind}</Badge> <strong>{b.subject}</strong> — {b.detail}</li>)}</ul></>}
      {r.unexpected_consumers.length>0&&<><h4>Unexpected consumers</h4><ul>{r.unexpected_consumers.map(x=><li key={x.id}><strong>{x.consumer_id}</strong> — {x.summary} · <code>{x.evidence_reference}</code></li>)}</ul></>}
      {owner&&!r.completion&&<p><Button variant="secondary" onClick={()=>void send(`${root}/${r.id}/controls`,{expected_revision:r.revision,action:"pause",rationale:"owner paused staged removal for investigation"})}>Pause</Button> {stage?.rollback_boundary==="reversible"&&<Button variant="secondary" onClick={()=>void send(`${root}/${r.id}/controls`,{expected_revision:r.revision,action:"restore",rationale:"owner restored compatibility at the declared safe boundary"})}>Restore compatibility</Button>} {r.blockers.length===0&&stage?.id!==r.input.stages.at(-1)?.id&&<Button onClick={()=>void send(`${root}/${r.id}/controls`,{expected_revision:r.revision,action:"advance",rationale:"owner accepted current delivery, use, health, and control evidence"})}>Advance stage</Button>}</p>}
      {r.completion&&<><h4>Verified cleanup</h4><p>Completed at <code>{r.completion.completed_revision}</code> · {r.completion.outcome_measures.join("; ")}</p><ul>{r.completion.cleanup.map(x=><li key={x.category}><Badge>{x.status}</Badge> <strong>{x.category}</strong>: {x.subject} · <code>{x.evidence_reference}</code></li>)}</ul></>}
    </article>})}
  </section>
}
