"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";
type Blocker={kind:string;member_id?:string;detail:string};type Scope={commit_count:number;changed_paths:string[];from_revision:string;to_revision:string};type Member={id:string;position:number;branch:string;branch_state:string;pull_request_id?:string;revision:string;parent_id?:string;authors:string[];acceptance_criteria:string[];base_revision:string;individual_scope:Scope;cumulative_scope:Scope;effective_permissions:{read:boolean;publish:boolean;update_branch:boolean;reason:string};reviewable:boolean;blockers:Blocker[];publications:{id:string;revision:string;published_by:string;published_at:string;review_state:string}[]};type Stack={id:string;title:string;outcome:string;target_branch:string;target_revision:string;status:string;members:Member[];blockers:Blocker[]};
const list=(x:string)=>(x||"").split(",").map(y=>y.trim()).filter(Boolean);
export function ChangeStacks({repository,revision}:{repository:string;revision:string}){const root=`/api/repositories/${repository}/change-stacks`,[items,setItems]=useState<Stack[]>([]),[error,setError]=useState("");const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems(((await r.json())as{items:Stack[]}).items)},[root]);
// The request completes asynchronously; the effect synchronizes this workspace with its repository resource.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{void load()},[load]);
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);try{const members=String(f.get("members")).split("\n").filter(Boolean).map((line,i)=>{const x=line.split("|").map(v=>v.trim());return{id:x[0],branch:x[1],branch_state:x[2],pull_request_id:x[3],revision:x[4],parent_id:x[5],authors:list(x[6]),acceptance_criteria:list(x[7]),position:i+1}});const body={title:f.get("title"),outcome:f.get("outcome"),target_branch:f.get("target_branch"),target_revision:f.get("target_revision"),members};const r=await fetch(root,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json())as{error:string}).error);return}e.currentTarget.reset();await load()}catch{setError("invalid_members")}}
async function publish(stack:string,m:Member){const r=await fetch(`${root}/${stack}/members/${m.id}/publications`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:m.revision})});if(!r.ok){setError(((await r.json())as{error:string}).error);return}await load()}
return <section className="workspace-stack"><header className="workspace-heading"><div><span className="eyebrow">Pull requests</span><h2>Change stacks</h2><p>Review how one outcome is divided, from the target through each exact dependent revision, without reconstructing ancestry locally.</p></div><Badge tone="accent">{items.length} stacks</Badge></header><form className="panel form-stack" onSubmit={create}><h3>Define an ordered stack</h3><div className="form-grid"><label>Title<input name="title" required/></label><label>Target branch<input name="target_branch" required defaultValue="main"/></label><label>Target revision<input name="target_revision" required defaultValue={revision}/></label></div><label>Shared outcome<textarea name="outcome" required/></label><label>Members in review order <small>id | branch | existing/new | optional pull request | exact revision | parent member id | authors comma-separated | acceptance criteria comma-separated</small><textarea name="members" required/></label>{error&&<p className="error">{error}</p>}<Button type="submit">Create stack</Button></form>
{items.map(s=><article className="panel form-stack" key={s.id}><div className="workspace-heading"><div><h3>{s.title}</h3><p>{s.outcome}</p></div><Badge tone={s.status==="reviewable"?"accent":"warning"}>{s.status}</Badge></div><p>Target <strong>{s.target_branch}</strong> at <code>{s.target_revision}</code></p>{s.members.map(m=><section className="workspace-card" key={m.id}><p><Badge tone={m.reviewable?"accent":"warning"}>#{m.position} {m.reviewable?"review first":"blocked"}</Badge> <strong>{m.branch}</strong> <code>{m.revision}</code>{m.pull_request_id&&<> · {m.pull_request_id}</>}</p><p>Base <code>{m.base_revision}</code>{m.parent_id&&<> · depends on <strong>{m.parent_id}</strong></>}</p><p><strong>Individual:</strong> {m.individual_scope.commit_count} commits, {m.individual_scope.changed_paths.join(", ")||"no supported source paths changed"}<br/><strong>Cumulative:</strong> {m.cumulative_scope.commit_count} commits, {m.cumulative_scope.changed_paths.join(", ")||"no supported source paths changed"}</p><p><strong>Authors:</strong> {m.authors.join(", ")} · <strong>Acceptance:</strong> {m.acceptance_criteria.join(" · ")}</p><small>Permissions: read {String(m.effective_permissions.read)}, publish {String(m.effective_permissions.publish)}, update branch {String(m.effective_permissions.update_branch)} — {m.effective_permissions.reason}</small>{m.blockers.map((b,i)=><p key={i}><Badge tone="warning">{b.kind.replaceAll("_"," ")}</Badge> {b.detail}</p>)}<p>{m.publications.map(p=><Badge key={p.id} tone="neutral">published {p.revision.slice(0,8)} by {p.published_by}</Badge>)} {m.reviewable&&m.effective_permissions.publish&&<Button variant="secondary" onClick={()=>void publish(s.id,m)}>Publish exact revision</Button>}</p></section>)}</article>)}</section>}
