"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Citation={repository_id:string;commit_id?:string;kind:string;path?:string;line_start?:number;workspace_id?:string;workspace_sequence?:number};
type Entry={id:string;sequence:number;type:string;body:string;actor_id:string;agent?:string;commit_id:string;citations?:Citation[];challenges?:string;supersedes?:string;stale:boolean;created_at:string};
type Investigation={id:string;title:string;question:string;creator_id:string;participants:string[];revision:string;commit_id:string;runs:{id:string;commit_id:string;actor_id:string;reason?:string;created_at:string}[];entries:Entry[];updated_at:string};

export function CollaborativeInvestigations({repository,revision,selected}:{repository:string;revision:string;selected?:string}){
 const router=useRouter();const [items,setItems]=useState<Investigation[]>([]),[active,setActive]=useState<Investigation>(),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/repositories/${repository}/investigations`).then(async r=>r.ok?r.json():Promise.reject()).then(async(b:{items:Investigation[]})=>{setItems(b.items);const id=selected||b.items[0]?.id;if(id){const detail=await fetch(`/api/repositories/${repository}/investigations/${id}`);if(detail.ok)setActive(await detail.json())}}).catch(()=>undefined)},[repository,selected]);
 async function send(path:string,body:unknown){setError("");const r=await fetch(`/api/repositories/${repository}/investigations${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("The investigation could not be updated. Check the revision, participant, and cited evidence.");return undefined}const v=await r.json() as Investigation;setActive(v);setItems(old=>[v,...old.filter(x=>x.id!==v.id)]);return v}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const v=await send("",{title:f.get("title"),question:f.get("question"),revision:f.get("revision")});if(v){e.currentTarget.reset();router.push(`/repositories/${repository}?view=investigations&investigation=${v.id}`)}}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget),path=String(f.get("path")||"").trim(),line=Number(f.get("line")||0),workspace=String(f.get("workspace")||"").trim(),sequence=Number(f.get("workspace_sequence")||0);const citations:Citation[]=workspace?[{repository_id:repository,kind:"workspace_observation",workspace_id:workspace,workspace_sequence:sequence}]:path?[{repository_id:repository,kind:"source",path,line_start:line||undefined}]:[];await send(`/${active.id}/entries`,{type:f.get("type"),body:f.get("body"),challenges:f.get("challenges")||undefined,supersedes:f.get("supersedes")||undefined,citations});e.currentTarget.reset()}
 return <section className="investigation-workspace">
  <div className="section-heading"><div><span className="eyebrow">Shared inquiry</span><h2>Investigation canvas</h2><p>Join midway, verify exact-revision evidence, challenge claims, and preserve what changed.</p></div><Badge>{items.length} canvases</Badge></div>
  <form className="investigation-create panel" onSubmit={create}><label>Title<input name="title" required maxLength={200}/></label><label>Revision<input name="revision" defaultValue={revision} required/></label><label className="wide">Framing question<textarea name="question" required maxLength={4000}/></label><Button type="submit">Open investigation</Button></form>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="investigation-layout"><aside className="investigation-list panel">{items.map(v=><Link className={active?.id===v.id?"active":""} key={v.id} href={`/repositories/${repository}?view=investigations&investigation=${v.id}`}><strong>{v.title}</strong><small><code>{v.commit_id.slice(0,12)}</code> · {v.participants.length} participants</small></Link>)}{!items.length&&<p>No shared investigations yet.</p>}</aside>
  {active&&<article className="investigation-canvas panel"><header><div><h3>{active.title}</h3><p>{active.question}</p></div><span><Badge>{active.entries.length} entries</Badge><small><code>{active.commit_id.slice(0,12)}</code></small></span></header>
   <section className="investigation-controls"><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send(`/${active.id}/participants`,{user_id:f.get("user_id")});e.currentTarget.reset()}}><label>Invite repository participant<input name="user_id" required placeholder="Stable user ID"/></label><Button type="submit" variant="secondary">Invite</Button></form><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send(`/${active.id}/runs`,{revision:f.get("revision"),reason:f.get("reason")})}}><label>Rerun at revision<input name="revision" required defaultValue={active.revision}/></label><label>Reason<input name="reason"/></label><Button type="submit" variant="secondary">Rerun</Button></form><small>Participants: {active.participants.join(", ")}</small></section>
   <ol className="investigation-entries">{active.entries.map(entry=><li key={entry.id} className={entry.stale?"stale":""}><span><Badge>{entry.type.replaceAll("_"," ")}</Badge><strong>#{entry.sequence} · {entry.agent?`${entry.agent} via `:""}{entry.actor_id}</strong>{entry.stale&&<Badge>stale</Badge>}</span><p>{entry.body}</p>{entry.challenges&&<small>Challenges entry {active.entries.find(x=>x.id===entry.challenges)?.sequence}</small>}{entry.supersedes&&<small>Supersedes entry {active.entries.find(x=>x.id===entry.supersedes)?.sequence}</small>}<div>{entry.citations?.map((c,i)=>c.path?<Link key={i} href={`/repositories/${c.repository_id}?view=code&ref=${c.commit_id}&path=${encodeURIComponent(c.path)}`}><code>{c.path}{c.line_start?`:${c.line_start}`:""}</code></Link>:<span key={i}>{c.kind}</span>)}</div><small><code>{entry.commit_id.slice(0,12)}</code> · {new Date(entry.created_at).toLocaleString()}</small></li>)}</ol>
   <form className="investigation-entry-form" onSubmit={add}><label>Entry type<select name="type"><option value="code_reference">Code reference</option><option value="query">Reproducible query</option><option value="runtime_observation">Runtime observation</option><option value="hypothesis">Hypothesis</option><option value="agent_finding">Agent finding</option><option value="conclusion">Conclusion</option><option value="challenge">Challenge</option></select></label><label>Code path<input name="path" placeholder="Optional exact path"/></label><label>Line<input name="line" type="number" min="1"/></label><label>Workspace evidence<input name="workspace" placeholder="Optional workspace ID"/></label><label>Event sequence<input name="workspace_sequence" type="number" min="1"/></label><label>Challenges<select name="challenges"><option value="">None</option>{active.entries.map(x=><option key={x.id} value={x.id}>#{x.sequence}</option>)}</select></label><label>Supersedes<select name="supersedes"><option value="">None</option>{active.entries.map(x=><option key={x.id} value={x.id}>#{x.sequence}</option>)}</select></label><label className="wide">Evidence, reasoning, or conclusion<textarea name="body" required maxLength={10000}/></label><Button type="submit">Add to canvas</Button></form>
  </article>}</div>
 </section>
}
