"use client";
import {useCallback,useEffect,useState} from "react";
import type {FormEvent} from "react";
import {Badge,Button,EmptyState} from "@/components/ui";
import {Sparkles} from "@/components/icons";
type Claim={id:string;actor_id:string;expires_at:string;released_at?:string};
type Opportunity={id:string;title:string;required_skills:string[];interests:string[];expected_outcome:string;acceptance_criteria:string[];sample_data?:string[];scope:string[];dependencies:string[];risk:string;mentor_ids:string[];assistance:string;revision:string;ready:boolean;source_state:string;source:{kind:string;resource_id:string;parent_id?:string;organization_id?:string}};
type Match={opportunity:Opportunity;score:number;reasons:string[];gaps:string[];claim?:Claim;available:boolean;grants_write_access:false};
type Outcome={opportunity_id:string;contributor_id:string;pull_request_id:string;release_id:string;credit:string;feedback:string;support_hours:number;readiness:string;next_opportunity?:string;recorded_at:string};
const lines=(v:FormDataEntryValue|null)=>String(v??"").split("\n").map(x=>x.trim()).filter(Boolean);
async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(`/api${url}`,init),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Request failed");return b}
export function ContributionOpportunities({repository,actor,owner}:{repository:string;actor:string;owner:string}){
 const [matches,setMatches]=useState<Match[]>([]),[outcomes,setOutcomes]=useState<Outcome[]>([]),[error,setError]=useState(""),[publishing,setPublishing]=useState(false),[hasProfile,setHasProfile]=useState(false);
 const refresh=useCallback(async()=>{try{if(actor){const b=await json<{items:Match[]}>(`/repositories/${repository}/contribution-opportunity-matches`);setMatches(b.items)}else{const b=await json<{items:Opportunity[];active_claims:Record<string,Claim>}>(`/repositories/${repository}/contribution-opportunities`);setMatches(b.items.map(opportunity=>({opportunity,score:0,reasons:[],gaps:[],claim:b.active_claims[opportunity.id],available:opportunity.ready&&!b.active_claims[opportunity.id],grants_write_access:false})))} }catch(e){setError(e instanceof Error?e.message:"Could not load opportunities")}},[actor,repository]);
 useEffect(()=>{let active=true;if(actor){json<{items:Match[]}>(`/repositories/${repository}/contribution-opportunity-matches`).then(b=>{if(active)setMatches(b.items)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load opportunities")})}else{json<{items:Opportunity[];active_claims:Record<string,Claim>}>(`/repositories/${repository}/contribution-opportunities`).then(b=>{if(active)setMatches(b.items.map(opportunity=>({opportunity,score:0,reasons:[],gaps:[],claim:b.active_claims[opportunity.id],available:opportunity.ready&&!b.active_claims[opportunity.id],grants_write_access:false})))}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load opportunities")})}return()=>{active=false}},[actor,repository]);
 useEffect(()=>{let active=true;json<{outcomes:Outcome[]}>(`/repositories/${repository}/contribution-opportunities`).then(b=>{if(active)setOutcomes(b.outcomes??[])}).catch(()=>{});return()=>{active=false}},[repository]);
 async function profile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await json(`/repositories/${repository}/contribution-opportunity-profile`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({interests:lines(f.get("interests")),skills:lines(f.get("skills")),max_risk:f.get("max_risk"),available_hours:Number(f.get("hours")),assistance:f.get("assistance")})});setHasProfile(true);await refresh()}catch(x){setError(x instanceof Error?x.message:"Could not save preferences")}}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await json(`/repositories/${repository}/contribution-opportunities`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:{kind:f.get("kind"),resource_id:f.get("resource_id"),parent_id:f.get("parent_id"),organization_id:f.get("organization_id")},required_skills:lines(f.get("skills")),interests:lines(f.get("interests")),expected_outcome:f.get("outcome"),acceptance_criteria:lines(f.get("criteria")),sample_data:lines(f.get("sample_data")),scope:lines(f.get("scope")),dependencies:lines(f.get("dependencies")),risk:f.get("risk"),mentor_ids:lines(f.get("mentors")),assistance:f.get("assistance")})});setPublishing(false);await refresh()}catch(x){setError(x instanceof Error?x.message:"Could not publish")}}
 async function claim(op:string){try{await json(`/repositories/${repository}/contribution-opportunities/${op}/claims`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({hours:168,note:"I intend to validate scope and begin this contribution."})});await refresh()}catch(x){setError(x instanceof Error?x.message:"Could not reserve")}}
 async function release(id:string){try{await json(`/repositories/${repository}/contribution-opportunity-claims/${id}/release`,{method:"POST"});await refresh()}catch(x){setError(x instanceof Error?x.message:"Could not release")}}
 async function start(op:string){try{const result=await json<{fork:{id:string};workspace:{id:string}}>(`/repositories/${repository}/contribution-opportunities/${op}/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});window.location.assign(`/repositories/${result.fork.id}?view=workspaces&workspace=${result.workspace.id}`)}catch(x){setError(x instanceof Error?x.message:"Could not prepare contribution")}}
 async function complete(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const b=await json<{outcome:Outcome}>(`/repositories/${repository}/contribution-opportunities/${f.get("opportunity_id")}/outcome`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pull_request_id:f.get("pull_request_id"),release_id:f.get("release_id"),credit:f.get("credit"),feedback:f.get("feedback"),support_hours:Number(f.get("support_hours")),readiness:f.get("readiness"),next_opportunity:f.get("next_opportunity")})});setOutcomes(x=>[...x,b.outcome]);e.currentTarget.reset()}catch(x){setError(x instanceof Error?x.message:"Could not record contributor outcome")}}
 return <section className="workspace"><div className="section-heading"><div><p className="eyebrow">Ready, bounded, unclaimed</p><h2>Contribution opportunities</h2></div>{actor===owner&&<Button onClick={()=>setPublishing(!publishing)}>{publishing?"Cancel":"Expose work"}</Button>}</div>{error&&<p className="form-error">{error}</p>}
 {actor&&<form className="card form-stack" onSubmit={profile}><h3>{hasProfile?"Refine your matches":"What work fits you?"}</h3><label>Interests<textarea name="interests" required placeholder="documentation&#10;developer experience" /></label><label>Skills<textarea name="skills" required placeholder="Go&#10;testing" /></label><label>Available hours<input name="hours" type="number" min="1" max="100" defaultValue="8" required /></label><label>Maximum risk<select name="max_risk"><option>low</option><option>medium</option><option>high</option></select></label><label>Preferred help<select name="assistance"><option value="human_or_agent">Human or agent</option><option value="human">Human mentor</option><option value="agent">Agent assistance</option><option value="none">Independent</option></select></label><Button type="submit">Explain my matches</Button></form>}
 {publishing&&<form className="card form-stack" onSubmit={publish}><h3>Derive an opportunity from existing work</h3><label>Source<select name="kind"><option value="issue">Triaged issue</option><option value="proposal">Proposal</option><option value="proposal_task">Planned task</option><option value="stewardship">Stewardship finding</option></select></label><label>Resource ID<input name="resource_id" required /></label><label>Proposal ID (for a task)<input name="parent_id" /></label><label>Organization ID (for stewardship)<input name="organization_id" /></label><label>Required skills<textarea name="skills" required /></label><label>Interests<textarea name="interests" required /></label><label>Expected outcome<textarea name="outcome" required /></label><label>Acceptance criteria<textarea name="criteria" placeholder="One verifiable result per line" /></label><label>Permitted sample-data paths<textarea name="sample_data" placeholder="testdata/example.json" /></label><label>Bounded paths or areas<textarea name="scope" required /></label><label>Dependencies<textarea name="dependencies" /></label><label>Risk<select name="risk"><option>low</option><option>medium</option><option>high</option></select></label><label>Mentor handles or IDs<textarea name="mentors" /></label><label>Available assistance<select name="assistance"><option value="human_or_agent">Human or agent</option><option value="human">Human mentor</option><option value="agent">Agent</option><option value="none">None</option></select></label><Button type="submit">Publish validated opportunity</Button></form>}
 {actor===owner&&<form className="card form-stack" onSubmit={complete}><h3>Record a delivered contributor outcome</h3><p>The guided pull request must already be merged and included in the named release.</p><label>Opportunity ID<input name="opportunity_id" required /></label><label>Pull request ID<input name="pull_request_id" required /></label><label>Release ID<input name="release_id" required /></label><label>Contributor credit<textarea name="credit" required /></label><label>Maintainer feedback<textarea name="feedback" required /></label><label>Support hours<input name="support_hours" type="number" min="0" max="1000" step="0.25" required /></label><label>Readiness<select name="readiness"><option value="ready">Ready</option><option value="ready_with_support">Ready with support</option><option value="needs_guidance">Needs guidance</option></select></label><label>Suggested next opportunity<input name="next_opportunity" /></label><Button type="submit">Record immutable outcome</Button></form>}
 {outcomes.length>0&&<div className="card"><h3>Trusted contributor outcomes</h3>{outcomes.map(o=><article key={o.opportunity_id}><p><Badge tone="accent">{o.readiness.replaceAll("_"," ")}</Badge> Contributor <strong>{o.contributor_id}</strong> · {o.support_hours} support hours</p><p>{o.credit}</p><p><strong>Maintainer feedback:</strong> {o.feedback}</p><p><a href={`/repositories/${repository}?view=pulls&pull=${o.pull_request_id}`}>Merged contribution</a> · release <code>{o.release_id}</code>{o.next_opportunity?<> · next opportunity <code>{o.next_opportunity}</code></>:null}</p></article>)}</div>}
 {matches.length===0?<EmptyState icon={<Sparkles/>} title="No opportunities yet" description="Maintainers have not exposed ready, bounded work from the project’s existing plans and findings."/>:<div className="card"><p>Rankings explain fit and gaps. Reserving coordinates effort for seven days; it grants no repository write access.</p>{matches.map(m=><article key={m.opportunity.id}><p><Badge tone={m.available?"accent":"neutral"}>{m.available?"available":"unavailable"}</Badge> <Badge>{m.opportunity.risk} risk</Badge> {m.score>0&&<strong> Fit {m.score}</strong>}</p><h3>{m.opportunity.title}</h3><p>{m.opportunity.expected_outcome}</p><p><strong>Acceptance:</strong> {(m.opportunity.acceptance_criteria||[m.opportunity.expected_outcome]).join(" · ")}</p>{m.opportunity.sample_data?.length?<p><strong>Sample data:</strong> {m.opportunity.sample_data.join(", ")}</p>:null}<p><strong>Scope:</strong> {m.opportunity.scope.join(", ")} · <strong>Revision:</strong> <code>{m.opportunity.revision.slice(0,12)}</code></p><p><strong>Skills:</strong> {m.opportunity.required_skills.join(", ")} · <strong>Mentors:</strong> {m.opportunity.mentor_ids.join(", ")||"none listed"}</p>{m.reasons.length>0&&<p><strong>Why suggested:</strong> {m.reasons.join(" · ")}</p>}{m.gaps.length>0&&<p><strong>Check first:</strong> {m.gaps.join(" · ")}</p>}{actor&&m.available&&!m.claim&&<Button onClick={()=>void claim(m.opportunity.id)}>Reserve for 7 days</Button>}{m.claim?.actor_id===actor&&<><Button onClick={()=>void start(m.opportunity.id)}>Create fork and prepare workspace</Button> <Button variant="secondary" onClick={()=>void release(m.claim!.id)}>Release reservation</Button></>}<hr/></article>)}</div>}</section>
}
