"use client";

import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import Link from "next/link";
import { Badge, Button, EmptyState } from "@/components/ui";
import { Book } from "@/components/icons";

type Reference={kind:string;label:string;url?:string;resource_id?:string;path?:string;revision?:string;status:"current"|"stale"|"inaccessible";detail:string};
type Category={name:string;description:string;suitable_for:"human"|"agent"|"human_or_agent";prerequisites:string[];review_expectations:string};
type Version={number:number;goals:string[];prerequisites:string[];conduct_guidance:string;security_guidance:string;supported_setup:string[];communication_expectations:string[];review_policy:string[];work_categories:Category[];references:Reference[];author_id:string;change_reason:string;created_at:string};
type Pathway={repository_id:string;current_version:number;versions:Version[];acknowledgements:Array<{id:string;version:number;actor_id:string;note?:string;created_at:string}>};
const lines=(value:FormDataEntryValue|null)=>String(value??"").split("\n").map(v=>v.trim()).filter(Boolean);
async function json<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api${url}`,init);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Request failed");return body}

export function ContributorPathway({repository,actor,owner,revision}:{repository:string;actor:string;owner:string;revision:string}){
 const [pathway,setPathway]=useState<Pathway>();const [editing,setEditing]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{let active=true;json<Pathway>(`/repositories/${repository}/contributor-pathway`).then(value=>{if(active)setPathway(value)}).catch(e=>{if(active&&(!(e instanceof Error)||e.message!=="contributor_pathway_not_found"))setError(e instanceof Error?e.message:"Pathway unavailable")});return()=>{active=false}},[repository]);
 async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const f=new FormData(event.currentTarget);const references:Omit<Reference,"status"|"detail">[]=[{kind:"documentation",label:"Contributor documentation",path:String(f.get("documentation_path")),revision,url:String(f.get("documentation_url"))},{kind:"ownership",label:"Repository maintainer",resource_id:owner,url:`/repositories/${repository}?view=people`}];const linkedKind=String(f.get("linked_kind")),linkedID=String(f.get("linked_id"));if(linkedID)references.push({kind:linkedKind,label:String(f.get("linked_label")),resource_id:linkedID,url:String(f.get("linked_url"))});try{const value=await json<Pathway>(`/repositories/${repository}/contributor-pathway/versions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:pathway?.current_version??0,goals:lines(f.get("goals")),prerequisites:lines(f.get("prerequisites")),conduct_guidance:f.get("conduct"),security_guidance:f.get("security"),supported_setup:lines(f.get("setup")),communication_expectations:lines(f.get("communication")),review_policy:lines(f.get("review")),work_categories:[{name:f.get("category_name"),description:f.get("category_description"),suitable_for:f.get("suitable_for"),prerequisites:lines(f.get("category_prerequisites")),review_expectations:f.get("category_review")}],references,change_reason:f.get("reason")})});setPathway(value);setEditing(false)}catch(e){setError(e instanceof Error?e.message:"Could not publish")}}
 async function acknowledge(){if(!pathway)return;try{setPathway(await json<Pathway>(`/repositories/${repository}/contributor-pathway/acknowledgements`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:pathway.current_version,note:"I reviewed the contributor pathway before beginning work."})}))}catch(e){setError(e instanceof Error?e.message:"Could not acknowledge")}}
 const current=pathway?.versions[pathway.versions.length-1],acknowledged=pathway?.acknowledgements.some(a=>a.version===pathway.current_version&&a.actor_id===actor);
 if(!current&&!editing)return <section className="workspace"><div className="section-heading"><div><p className="eyebrow">Before committing effort</p><h2>Contributor pathway</h2></div>{actor===owner&&<Button onClick={()=>setEditing(true)}>Publish pathway</Button>}</div>{error&&<p className="form-error">{error}</p>}<EmptyState icon={<Book/>} title="No pathway published" description="Maintainers have not yet assembled the project’s goals, requirements, and ways to help." /></section>;
 if(editing)return <section className="workspace"><div className="section-heading"><div><p className="eyebrow">Immutable version {Number(pathway?.current_version??0)+1}</p><h2>Publish contributor pathway</h2></div><Button variant="secondary" onClick={()=>setEditing(false)}>Cancel</Button></div>{error&&<p className="form-error">{error}</p>}<form className="card form-stack" onSubmit={publish}><label>Project goals<textarea name="goals" required placeholder="One goal per line" /></label><label>Prerequisites<textarea name="prerequisites" required placeholder="One requirement per line" /></label><label>Conduct guidance<textarea name="conduct" required /></label><label>Security guidance<textarea name="security" required /></label><label>Supported setup<textarea name="setup" required placeholder="One supported setup step per line" /></label><label>Communication expectations<textarea name="communication" required /></label><label>Review policy<textarea name="review" required /></label><h3>Outside work category</h3><label>Name<input name="category_name" required /></label><label>Description<textarea name="category_description" required /></label><label>Suitable for<select name="suitable_for"><option value="human_or_agent">Humans or agents</option><option value="human">Humans</option><option value="agent">Agents</option></select></label><label>Category prerequisites<textarea name="category_prerequisites" /></label><label>Review expectations<textarea name="category_review" required /></label><h3>Current evidence</h3><label>Documentation path<input name="documentation_path" required placeholder="CONTRIBUTING.md" /></label><label>Documentation revision<input name="documentation_revision" value={revision} readOnly required /></label><label>Documentation URL<input name="documentation_url" placeholder="https://…" /></label><label>Additional link type<select name="linked_kind"><option value="issue">Issue</option><option value="proposal">Proposal</option><option value="release">Release</option></select></label><label>Link label<input name="linked_label" /></label><label>Resource ID<input name="linked_id" /></label><label>Resource URL<input name="linked_url" /></label><label>Reason for this version<textarea name="reason" required /></label><Button type="submit">Publish immutable version</Button></form></section>;
 return <section className="workspace"><div className="section-heading"><div><p className="eyebrow">Participation contract · version {current!.number}</p><h2>Contributor pathway</h2></div><div>{actor&&!acknowledged&&<Button variant="secondary" onClick={()=>void acknowledge()}>Acknowledge version</Button>}{actor===owner&&<Button onClick={()=>setEditing(true)}>Revise pathway</Button>}</div></div>{error&&<p className="form-error">{error}</p>}<div className="card"><p><Badge>{current!.change_reason}</Badge> Published by {current!.author_id}</p><h3>Project goals</h3><ul>{current!.goals.map(v=><li key={v}>{v}</li>)}</ul><h3>Before you begin</h3><ul>{current!.prerequisites.map(v=><li key={v}>{v}</li>)}</ul><h3>Supported setup</h3><ol>{current!.supported_setup.map(v=><li key={v}>{v}</li>)}</ol><h3>Conduct</h3><p>{current!.conduct_guidance}</p><h3>Security</h3><p>{current!.security_guidance}</p><h3>Communication</h3><ul>{current!.communication_expectations.map(v=><li key={v}>{v}</li>)}</ul><h3>Review policy</h3><ul>{current!.review_policy.map(v=><li key={v}>{v}</li>)}</ul></div><div className="card"><h3>Ways to help</h3>{current!.work_categories.map(c=><article key={c.name}><p><Badge>{c.suitable_for.replaceAll("_"," ")}</Badge></p><h4>{c.name}</h4><p>{c.description}</p><p><strong>Review:</strong> {c.review_expectations}</p>{c.prerequisites.length>0&&<ul>{c.prerequisites.map(v=><li key={v}>{v}</li>)}</ul>}</article>)}</div><div className="card"><h3>Linked requirements</h3>{current!.references.map((r,i)=><p key={`${r.kind}-${i}`}><Badge>{r.status}</Badge> {r.url?<Link href={r.url}>{r.label}</Link>:<strong>{r.label}</strong>} · {r.detail}</p>)}</div><div className="card"><h3>Acknowledgements</h3>{pathway!.acknowledgements.filter(a=>a.version===current!.number).map(a=><p key={a.id}>{a.actor_id} · {a.note}</p>)}{!pathway!.acknowledgements.some(a=>a.version===current!.number)&&<p>No acknowledgements yet.</p>}</div><details className="card"><summary>Version history</summary>{pathway!.versions.map(v=><p key={v.number}>Version {v.number} · {v.change_reason} · {v.author_id}</p>)}</details></section>
}
