"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Budget={hours:number;cost_units:number;agent_runs:number};
type Access={actions:string[];sources:string[];expires_at?:string;missing?:string[];grants_authority:boolean};
type Person={id:string;kind:"human"|"agent";principal_id:string;role:string;why:string;responsibilities:string[];budget:Budget;deadline?:string;escalates_to_id?:string;requested_actions:string[];effective_access:Access;state:string;invited_by_id:string;responded_by_id?:string;removed_by_id?:string};
type Charter={version:number;outcome:string;success_measures:string[];operating_principles:string[];total_budget:Budget;deadline?:string;default_escalation:string;changed_by_id:string;change_reason?:string;created_at:string};
type Scope={repository_id:string;commit_id:string;paths:string[];required_actions:string[]};
type Stream={id:string;revision:number;title:string;owner_participant_id:string;inputs:string[];expected_artifacts:string[];depends_on:string[];acceptance_criteria:string[];repository_scope:Scope[];integration_order:number;budget:Budget;assumptions:{id:string;statement:string;source_stream_id?:string;source_stream_revision?:number}[]};
type PlanVersion={version:number;charter_version:number;status:string;streams:Stream[];blockers:{kind:string;stream_ids?:string[];owner_id?:string;detail:string}[];required_acceptances:string[];acceptances:{participant_id:string;actor_id:string;accepted_at:string}[];proposed_by_id:string;change_reason:string;created_at:string};
type Context={kind:"change_session"|"investigation"|"experiment"|"workspace";id:string;parent_id?:string;repository_id:string;revision:string};
type Citation={repository_id:string;revision:string;path?:string;resource_kind:string;resource_id:string;url?:string};
type TimelineEntry={id:string;sequence:number;stream_id:string;stream_revision:number;kind:string;summary:string;author_participant_id:string;author_id:string;context:Context;citations:Citation[];created_at:string};
type Handoff={id:string;stream_id:string;stream_revision:number;from_participant_id:string;to_participant_id:string;input_entry_ids:string[];input_revisions:string[];context:Context;acceptance_criteria:string[];residual_uncertainty:string[];status:string;requested_by_id:string;requested_at:string;acceptance?:{actor_id:string;note:string;accepted_at:string}};
type Team={id:string;name:string;source:{kind:string;id:string;title:string;url?:string};organizer_id:string;state:string;version:number;charter:Charter;charter_history:Charter[];participants:Person[];events:{sequence:number;type:string;actor_id:string;participant_id?:string;detail?:string;created_at:string}[];plan?:{current:PlanVersion;history:PlanVersion[]};executions:{id:string;stream_id:string;stream_revision:number;owner_participant_id:string;context:Context;attached_by_id:string;attached_at:string}[];timeline:TimelineEntry[];handoffs:Handoff[]};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);
const budget=(f:FormData,prefix="")=>({hours:Number(f.get(`${prefix}hours`)||0),cost_units:Number(f.get(`${prefix}cost_units`)||0),agent_runs:Number(f.get(`${prefix}agent_runs`)||0)});
const date=(v:FormDataEntryValue|null)=>v?`${v}T23:59:59Z`:null;

export function DeliveryTeams({repository,actor,selected}:{repository:string;actor:string;selected?:string}){
 const [items,setItems]=useState<Team[]>([]),[active,setActive]=useState<Team>(),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`/api/repositories/${repository}/delivery-teams`);if(!r.ok)return;const v=await r.json() as Team[];setItems(v);const id=selected||v[0]?.id;if(id){const d=await fetch(`/api/repositories/${repository}/delivery-teams/${id}`);if(d.ok)setActive(await d.json())}},[repository,selected]);
 useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
  void load()},[load]);
 async function mutate(path:string,method:string,body:unknown){setError("");const r=await fetch(`/api/repositories/${repository}/delivery-teams${path}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const b=await r.json().catch(()=>({error:"unknown"})) as {error:string};setError(b.error==="authority_not_held"?"That participant or requested action is outside the organizer's current authority.":"The team changed or the operating contract is incomplete. Refresh and try again.");return}const v=await r.json() as Team;setActive(v);setItems(old=>[v,...old.filter(x=>x.id!==v.id)]);return v}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),v=await mutate("","POST",{name:f.get("name"),source:{kind:f.get("source_kind"),id:f.get("source_id"),title:f.get("source_title"),url:f.get("source_url")},charter:charterBody(f)});if(v)window.history.pushState(null,"",`?view=teams&team=${v.id}`)}
 function charterBody(f:FormData){return {outcome:f.get("outcome"),success_measures:lines(f.get("measures")),operating_principles:lines(f.get("principles")),total_budget:budget(f,"total_"),deadline:date(f.get("deadline")),default_escalation:f.get("escalation"),change_reason:f.get("reason")}}
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Agree before execution</span><h2>Delivery teams</h2><p>Make the outcome, responsibilities, limits, budgets, deadlines, and escalation path inspectable before coordinated work starts. A charter records intent; it never creates access.</p></div><Badge>{items.filter(x=>x.state==="forming").length} forming</Badge></div>
 <details className="investigation-create panel"><summary>Form a delivery team</summary><form onSubmit={create}><label>Team name<input name="name" required/></label><label>Planned outcome type<select name="source_kind"><option>proposal</option><option>initiative</option><option>decision</option><option>incident_follow_up</option><option>planned_outcome</option></select></label><label>Outcome resource ID<input name="source_id"/></label><label>Outcome title<input name="source_title" required/></label><label>Outcome link<input name="source_url"/></label><CharterFields/><Button type="submit">Create attributable charter</Button></form></details>{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="investigation-layout"><aside className="investigation-list panel">{items.map(x=><Link key={x.id} className={active?.id===x.id?"active":""} href={`/repositories/${repository}?view=teams&team=${x.id}`}><strong>{x.name}</strong><small>{x.source.kind.replaceAll("_"," ")} · v{x.charter.version}</small><small>{x.participants.filter(p=>p.state==="accepted").length} accepted</small></Link>)}{!items.length&&<p>No delivery teams yet.</p>}</aside>
 {active&&<article className="investigation-canvas panel"><header><div><span className="eyebrow">{active.source.kind.replaceAll("_"," ")}</span><h3>{active.name}</h3><p>Organized by {active.organizer_id} · contract version {active.charter.version}</p></div><Badge>{active.state}</Badge></header>
 <section><h4>Shared outcome</h4><p>{active.charter.outcome}</p><h4>Success measures</h4><ul>{active.charter.success_measures.map(x=><li key={x}>{x}</li>)}</ul><h4>Operating principles</h4><ul>{active.charter.operating_principles.map(x=><li key={x}>{x}</li>)}</ul><p><strong>Team budget:</strong> {active.charter.total_budget.hours}h · {active.charter.total_budget.cost_units} cost units · {active.charter.total_budget.agent_runs} agent runs</p><p><strong>Deadline:</strong> {active.charter.deadline?new Date(active.charter.deadline).toLocaleDateString():"None"} · <strong>Default escalation:</strong> {active.charter.default_escalation}</p></section>
 <section><div className="section-heading"><div><h4>Participants and authority boundaries</h4><p>Invitations explain why each person is present. Effective access is a preview of independent roles and grants, not authority issued by this team.</p></div><Badge>{active.participants.filter(x=>x.state!=="removed").length} invited</Badge></div>
 {active.participants.map(p=><article className="investigation-entry" key={p.id}><header><div><strong>{p.role} · {p.principal_id}</strong><small>{p.kind} · invited by {p.invited_by_id}</small></div><Badge>{p.state}</Badge></header><p>{p.why}</p><p><strong>Responsible for:</strong> {p.responsibilities.join("; ")}</p><p><strong>Boundary:</strong> {p.effective_access.actions.join(", ")||"No requested access is effective"}</p>{p.effective_access.missing?.length?<p className="form-error">Unavailable: {p.effective_access.missing.join(", ")}</p>:null}<small>Source: {p.effective_access.sources.join("; ")} · grants authority: no{p.effective_access.expires_at?` · expires ${new Date(p.effective_access.expires_at).toLocaleString()}`:""}</small><p>{p.budget.hours}h · {p.budget.cost_units} units · {p.budget.agent_runs} runs · escalation {p.escalates_to_id||active.charter.default_escalation}</p>
 {p.state==="invited"&&((p.kind==="human"&&p.principal_id===actor)||p.kind==="agent")&&<div className="button-row"><Button size="sm" onClick={()=>void mutate(`/${active.id}/participants/${p.id}/response`,"POST",{expected_version:active.version,response:"accepted"})}>Accept role</Button><Button size="sm" variant="secondary" onClick={()=>void mutate(`/${active.id}/participants/${p.id}/response`,"POST",{expected_version:active.version,response:"declined"})}>Decline</Button></div>}
 {p.state!=="removed"&&<Button size="sm" variant="secondary" onClick={()=>void mutate(`/${active.id}/participants/${p.id}`,"DELETE",{expected_version:active.version,reason:"Team scope changed"})}>Remove with attribution</Button>}</article>)}
 <details><summary>Invite a complementary participant</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),v=await mutate(`/${active.id}/participants`,"POST",{expected_version:active.version,kind:f.get("kind"),principal_id:f.get("principal"),role:f.get("role"),why:f.get("why"),responsibilities:lines(f.get("responsibilities")),budget:budget(f),deadline:date(f.get("participant_deadline")),escalates_to_id:f.get("participant_escalation"),requested_actions:lines(f.get("actions"))});if(v)form.reset()}}><label>Participant type<select name="kind"><option value="human">Repository participant</option><option value="agent">Organization-approved agent</option></select></label><label>Stable human or agent ID<input name="principal" required/></label><label>Complementary role<input name="role" required/></label><label>Why this participant?<textarea name="why" required/></label><label>Responsibilities, one per line<textarea name="responsibilities" required/></label><BudgetFields/><label>Participant deadline<input name="participant_deadline" type="date"/></label><label>Escalates to<input name="participant_escalation" placeholder={active.charter.default_escalation}/></label><label>Requested actions, one per line<textarea name="actions" placeholder={"contents:read\ndiscussion:write\ncandidate_branch:write"}/></label><Button type="submit">Preview authority and invite</Button></form></details></section>
 <details><summary>Revise the operating contract</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${active.id}/charter`,"PATCH",{expected_version:active.version,...charterBody(f)})}}><CharterFields charter={active.charter}/><label>Why is the charter changing?<input name="reason" required/></label><Button type="submit">Append charter version</Button></form></details>
 <PlanWorkspace team={active} actor={actor} mutate={mutate}/>
 <CollaborationWorkspace team={active} actor={actor} mutate={mutate}/>
 <section><h4>Attributable record</h4><ol className="investigation-entries">{active.events.map(x=><li key={x.sequence}><strong>{x.type.replaceAll("."," ")}</strong> by {x.actor_id}{x.detail&&<p>{x.detail}</p>}<small>{new Date(x.created_at).toLocaleString()}</small></li>)}</ol><h4>Charter history</h4><ol>{active.charter_history.map(x=><li key={x.version}>Version {x.version} by {x.changed_by_id}{x.change_reason?` · ${x.change_reason}`:""}</li>)}</ol></section></article>}</div></section>
}

function CollaborationWorkspace({team,actor,mutate}:{team:Team;actor:string;mutate:(path:string,method:string,body:unknown)=>Promise<Team|undefined>}){
 const plan=team.plan?.current, owned=team.participants.filter(p=>p.state==="accepted"&&(p.principal_id===actor||p.kind==="agent"));
 const defaultOwner=owned.find(p=>plan?.streams.some(s=>s.owner_participant_id===p.id));
 function context(f:FormData):Context{return {kind:String(f.get("context_kind")) as Context["kind"],id:String(f.get("context_id")),parent_id:String(f.get("parent_id")||"")||undefined,repository_id:String(f.get("repository_id")),revision:String(f.get("revision"))}}
 function citations(value:FormDataEntryValue|null){return String(value||"").split("\n").filter(Boolean).map(row=>{const [repository_id,revision,path,resource_kind,resource_id,url]=row.split("|").map(x=>x.trim());return {repository_id,revision,path,resource_kind,resource_id,url}})}
 return <section><div className="section-heading"><div><h4>Shared context and governed handoffs</h4><p>Publish only inspectable evidence from an accepted stream scope. Credentials, private terminal input, hidden prompts, and uncited output are never copied into this record.</p></div><Badge>{team.handoffs?.filter(h=>h.status==="requested").length||0} pending</Badge></div>
 {!plan||plan.status!=="accepted"?<p>An accepted, blocker-free plan is required before work contexts or evidence can be attached.</p>:<>
 <details><summary>Attach a scoped execution context</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),stream=String(f.get("stream"));await mutate(`/${team.id}/streams/${stream}/contexts`,"POST",{expected_version:team.version,participant_id:f.get("participant"),context:context(f)})}}><OwnerAndStream team={team} owners={owned}/><ContextFields team={team}/><Button type="submit" disabled={!defaultOwner}>Attach exact context</Button></form></details>
 <details><summary>Publish cited work to the team timeline</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${team.id}/timeline`,"POST",{expected_version:team.version,participant_id:f.get("participant"),stream_id:f.get("stream"),kind:f.get("kind"),summary:f.get("summary"),context:context(f),citations:citations(f.get("citations"))})}}><OwnerAndStream team={team} owners={owned}/><label>Record type<select name="kind"><option>finding</option><option>question</option><option>checkpoint</option><option>artifact</option><option>decision</option><option>uncertainty</option></select></label><label>Useful, reviewable summary<textarea name="summary" required/></label><ContextFields team={team}/><label>Citations, one per line<textarea name="citations" required placeholder="repository | 40-char revision | scoped/path | blob | object-id | optional URL"/></label><Button type="submit" disabled={!defaultOwner}>Publish cited record</Button></form></details>
 <ol className="investigation-entries">{[...(team.timeline||[])].reverse().map(entry=><li key={entry.id}><header><div><strong>{entry.kind} · {entry.summary}</strong><small>{entry.author_id} for {entry.author_participant_id} · stream {entry.stream_id} r{entry.stream_revision}</small></div><Badge>{entry.context.kind}</Badge></header><p><code>{entry.context.repository_id}@{entry.context.revision.slice(0,12)}</code> · {entry.context.id}</p>{entry.citations.map((c,i)=><p key={i}><strong>{c.resource_kind}</strong> {c.resource_id} · {c.path||"resource"} at <code>{c.revision.slice(0,12)}</code></p>)}<small>{new Date(entry.created_at).toLocaleString()}</small></li>)}</ol>
 <details><summary>Request a structured handoff</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${team.id}/handoffs`,"POST",{expected_version:team.version,participant_id:f.get("participant"),stream_id:f.get("stream"),to_participant_id:f.get("recipient"),input_entry_ids:lines(f.get("inputs")),context:context(f),acceptance_criteria:lines(f.get("criteria")),residual_uncertainty:lines(f.get("uncertainty"))})}}><OwnerAndStream team={team} owners={owned}/><label>Recipient<select name="recipient">{team.participants.filter(p=>p.state==="accepted").map(p=><option key={p.id} value={p.id}>{p.role} · {p.principal_id}</option>)}</select></label><label>Exact timeline entry IDs, one per line<textarea name="inputs" required/></label><label>Acceptance criteria, one per line<textarea name="criteria" required/></label><label>Residual uncertainty, one per line<textarea name="uncertainty" placeholder="State what remains unknown; do not paste hidden context."/></label><ContextFields team={team}/><Button type="submit" disabled={!defaultOwner}>Request attributable handoff</Button></form></details>
 <ol className="investigation-entries">{[...(team.handoffs||[])].reverse().map(h=>{const recipient=team.participants.find(p=>p.id===h.to_participant_id),canAccept=h.status==="requested"&&(recipient?.kind==="agent"||recipient?.principal_id===actor);return <li key={h.id}><header><div><strong>{h.from_participant_id} → {h.to_participant_id}</strong><small>stream {h.stream_id} r{h.stream_revision} · inputs {h.input_entry_ids.join(", ")}</small></div><Badge>{h.status}</Badge></header><p><strong>Exact revisions:</strong> {h.input_revisions.join(", ")}</p><p><strong>Accept when:</strong> {h.acceptance_criteria.join("; ")}</p><p><strong>Still uncertain:</strong> {h.residual_uncertainty.join("; ")||"Nothing declared"}</p>{h.acceptance&&<p>Accepted by {h.acceptance.actor_id}: {h.acceptance.note||"Verified without an additional note."}</p>}{canAccept&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${team.id}/handoffs/${h.id}/acceptance`,"POST",{expected_version:team.version,participant_id:h.to_participant_id,note:f.get("note")})}}><label>Verification note<textarea name="note" placeholder="What did you verify before continuing?"/></label><Button type="submit">Accept after verification</Button></form>}</li>})}</ol></>}
 </section>
}
function OwnerAndStream({team,owners}:{team:Team;owners:Person[]}){return <><label>Acting owner<select name="participant">{owners.map(p=><option key={p.id} value={p.id}>{p.role} · {p.principal_id}</option>)}</select></label><label>Work stream<select name="stream">{team.plan?.current.streams.filter(s=>owners.some(p=>p.id===s.owner_participant_id)).map(s=><option key={s.id} value={s.id}>{s.title} · r{s.revision}</option>)}</select></label></>}
function ContextFields({team}:{team:Team}){const scope=team.plan?.current.streams[0]?.repository_scope[0];return <><label>Execution capability<select name="context_kind"><option value="change_session">Change session</option><option>investigation</option><option>experiment</option><option>workspace</option></select></label><label>Context resource ID<input name="context_id" required/></label><label>Parent pull request or decision ID<input name="parent_id"/><small>Required only for a change session or decision experiment.</small></label><label>Repository ID<input name="repository_id" required defaultValue={scope?.repository_id}/></label><label>Exact 40-character revision<input name="revision" required defaultValue={scope?.commit_id}/></label></>}

function PlanWorkspace({team,actor,mutate}:{team:Team;actor:string;mutate:(path:string,method:string,body:unknown)=>Promise<Team|undefined>}){
 const plan=team.plan?.current;
 const editable=JSON.stringify(plan?.streams.map(({revision,...stream})=>{void revision;return stream})??[],null,2);
 return <section><div className="section-heading"><div><h4>Revision-bound parallel plan</h4><p>Streams expose ownership, interfaces, exact repository revisions, dependencies, integration order, and conflicts before execution.</p></div><Badge>{plan?.status??"not planned"}</Badge></div>
 {plan&&<><p>Plan v{plan.version} against charter v{plan.charter_version} · proposed by {plan.proposed_by_id}{plan.change_reason?` · ${plan.change_reason}`:""}</p>
 {plan.blockers.length>0&&<div className="form-error" role="status"><strong>{plan.blockers.length} visible blocker{plan.blockers.length===1?"":"s"}</strong><ul>{plan.blockers.map((b,i)=><li key={`${b.kind}-${i}`}><strong>{b.kind.replaceAll("_"," ")}:</strong> {b.detail}{b.stream_ids?.length?` (${b.stream_ids.join(" → ")})`:""}</li>)}</ul></div>}
 <ol className="investigation-entries">{[...plan.streams].sort((a,b)=>a.integration_order-b.integration_order).map(s=><li key={s.id}><header><div><strong>{s.integration_order}. {s.title}</strong><small>{s.id} · revision {s.revision} · owner {s.owner_participant_id}</small></div><Badge>{s.depends_on.length?`after ${s.depends_on.join(", ")}`:"independent"}</Badge></header><p><strong>Inputs:</strong> {s.inputs.join("; ")}</p><p><strong>Artifacts:</strong> {s.expected_artifacts.join("; ")}</p><p><strong>Accepted when:</strong> {s.acceptance_criteria.join("; ")}</p>{s.repository_scope.map((scope,i)=><p key={i}><strong>{scope.repository_id}@{scope.commit_id.slice(0,12)}</strong> · {scope.paths.join(", ")} · needs {scope.required_actions.join(", ")||"no actions"}</p>)}<small>{s.budget.hours}h · {s.budget.cost_units} cost units · {s.budget.agent_runs} agent runs{s.assumptions.length?` · assumptions: ${s.assumptions.map(a=>a.statement).join("; ")}`:""}</small></li>)}</ol>
 <div><strong>Material-plan acceptance</strong>{plan.required_acceptances.map(pid=>{const accepted=plan.acceptances.some(a=>a.participant_id===pid),p=team.participants.find(x=>x.id===pid),canRespond=p?.kind==="agent"||(p?.kind==="human"&&p.principal_id===actor);return <p key={pid}>{p?.role??pid}: {accepted?"accepted":"pending"} {!accepted&&canRespond&&<Button size="sm" onClick={()=>void mutate(`/${team.id}/plan/versions/${plan.version}/acceptances`,"POST",{expected_version:team.version,participant_id:pid})}>Accept plan v{plan.version}</Button>}</p>})}</div></>}
 <details><summary>{plan?"Propose a revised decomposition":"Propose the decomposition"}</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);let streams:unknown;try{streams=JSON.parse(String(f.get("streams")))}catch{return}await mutate(`/${team.id}/plan/versions`,"POST",{expected_version:team.version,change_reason:f.get("change_reason"),streams})}}><p>Use one object per stream. Keep stable stream IDs across revisions; pin every repository scope to a full 40-character commit.</p><label>Why this plan or replan?<input name="change_reason" required defaultValue={plan?"Resolve dependencies or changed assumptions":"Initial collaborative decomposition"}/></label><label>Work streams (JSON)<textarea name="streams" rows={18} required defaultValue={editable}/></label><Button type="submit">Derive blockers and propose plan</Button></form></details>
 {team.plan&&<details><summary>Plan history ({team.plan.history.length})</summary><ol>{team.plan.history.map(v=><li key={v.version}>Version {v.version} · {v.status} · {v.streams.length} streams · {v.blockers.length} blockers · by {v.proposed_by_id}</li>)}</ol></details>}</section>
}
function BudgetFields({prefix=""}:{prefix?:string}){return <fieldset><legend>Budget ceiling</legend><label>Hours<input name={`${prefix}hours`} type="number" min="0" defaultValue="0"/></label><label>Cost units<input name={`${prefix}cost_units`} type="number" min="0" defaultValue="0"/></label><label>Agent runs<input name={`${prefix}agent_runs`} type="number" min="0" defaultValue="0"/></label></fieldset>}
function CharterFields({charter}:{charter?:Charter}){return <><label>Outcome<textarea name="outcome" required defaultValue={charter?.outcome}/></label><label>Success measures, one per line<textarea name="measures" required defaultValue={charter?.success_measures.join("\n")}/></label><label>Operating principles, one per line<textarea name="principles" required defaultValue={charter?.operating_principles.join("\n")}/></label><BudgetFields prefix="total_"/><label>Team deadline<input name="deadline" type="date" defaultValue={charter?.deadline?.slice(0,10)}/></label><label>Default escalation path<input name="escalation" required defaultValue={charter?.default_escalation}/></label></>}
