/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Evidence={id:string;kind:string;reference:string;revision?:string;summary:string;audience:string};
type Revision={number:number;title:string;user_goal:string;origin:{kind:string;id:string;revision?:string};journeys:{name:string;steps:string[];outcome:string}[];states:{name:string;trigger:string;behavior:string;content:string}[];content:string[];constraints:{kind:string;requirement:string}[];alternatives:{name:string;tradeoff:string;reason:string}[];success_measures:{name:string;target:string}[];affected_components:string[];component_contracts?:{name:string;contract:string}[];breakpoints?:{name:string;minimum_width:number;maximum_width?:number;behavior:string}[];evidence:Evidence[];uncertainty:string[];change_reason:string;author_id:string;created_at:string};
type Proposal={id:string;current_revision:number;revisions:Revision[];participants:{id:string;subject_id:string;kind:string;role:string;grounded_evidence_ids?:string[]}[];artifacts:{id:string;current_version:number;revisions:{number:number;kind:string;title:string;proposal_revision:number;frames:{name:string;description:string;format:string;body:string}[];interactions:{trigger:string;action:string;result:string}[];assets?:{id:string;name:string;source:string;author_id:string;license:string;transformations?:string[]}[];uncertainty:string[]}[]}[];comments:{id:string;author_id:string;subject_kind:string;subject_id:string;subject_revision:number;body:string;stance:string;uncertainty?:string}[];acknowledgements:{id:string;owner_id:string;status:string;rationale?:string;proposal_revision:number;current:boolean}[];implementations?:{id:string;proposal_revision:number;base_revision:string;work_proposal_id:string;requirements:{id:string;kind:string;subject:string;expected:string}[];assets?:{id:string;name:string;source:string;author_id:string;license:string;transformations?:string[]}[];tasks:{task_id:string;title:string;owner_kind:string;owner_id:string;position:number}[]}[];implementation_mappings?:{id:string;task_id:string;pull_request_id:string;revision:string;changed_paths:string[];rendered_surfaces:string[];requirement_ids:string[];deviations?:{requirement_id:string;reason:string;impact:string;status:string;approved_by_id?:string}[]}[];private_evidence_count:number};
const template=JSON.stringify({origin:{kind:"issue",id:"issue-id",revision:"exact-revision"},user_goal:"A person can complete the goal confidently",journeys:[{name:"primary journey",steps:["begin","review","finish"],outcome:"goal completed"}],states:[{name:"review",trigger:"continue",behavior:"show the effect before commitment",content:"Review changes"}],content:["Review changes","Continue"],constraints:[{kind:"accessibility",requirement:"Keyboard and screen-reader complete"}],alternatives:[{name:"Immediate action",tradeoff:"Faster but easier to trigger accidentally",reason:"Retain for comparison"}],success_measures:[{name:"task completion",target:"At least 90%"}],affected_components:["ComponentName"],component_contracts:[{name:"ComponentName",contract:"Required inputs, outputs, focus behavior, and error handling"}],breakpoints:[{name:"compact",minimum_width:0,maximum_width:639,behavior:"Stack actions"},{name:"wide",minimum_width:640,behavior:"Place actions inline"}],evidence:[{id:"issue-evidence",kind:"issue",reference:"issue-id",revision:"exact-revision",summary:"Observed need",audience:"repository"}],uncertainty:["The review step may add friction"],change_reason:"Open behavior for review"},null,2);

export function DesignProposals({repository,actor}:{repository:string;actor:string}){
 const root=`/api/repositories/${repository}/design-proposals`;const [items,setItems]=useState<Proposal[]>([]);const [error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems(((await r.json()) as {items:Proposal[]}).items)},[root]);useEffect(()=>{void load()},[load]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{const body={...JSON.parse(String(d.get("definition"))) as object,title:d.get("title")};const r=await fetch(root,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}f.reset();setError("");await load()}catch{setError("invalid_design_proposal_json")}}
 async function comment(e:React.FormEvent<HTMLFormElement>,p:Proposal){e.preventDefault();const f=e.currentTarget,d=new FormData(f);const r=await fetch(`${root}/${p.id}/comments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({subject_kind:"proposal",subject_id:p.id,subject_revision:p.current_revision,body:d.get("body"),stance:d.get("stance"),uncertainty:d.get("uncertainty"),evidence_ids:[]})});if(r.ok){f.reset();await load()}else setError(((await r.json()) as {error:string}).error)}
 async function implement(e:React.FormEvent<HTMLFormElement>,p:Proposal){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{const body=JSON.parse(String(d.get("contract"))) as object;const r=await fetch(`${root}/${p.id}/implementations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){f.reset();setError("");await load()}else setError(((await r.json()) as {error:string}).error)}catch{setError("invalid_implementation_contract")}}
 return <section className="investigation-workspace"><div className="section-heading"><div><p className="eyebrow">Before implementation</p><h2>Product design proposals</h2><p>Challenge goals, journeys, behavior, content, and assumptions through revision-bound wireframes and prototypes.</p></div><Badge>{items.length} proposals</Badge></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{actor&&<details className="workspace-card"><summary>Open a design proposal</summary><form className="workspace-form" onSubmit={create}><input name="title" placeholder="Proposal title" required/><textarea name="definition" defaultValue={template} rows={22} aria-label="Structured product behavior proposal" required/><Button type="submit">Open for review</Button></form></details>}
 {items.map(p=>{const v=p.revisions[p.revisions.length-1];return <article className="workspace-card" key={p.id}><div className="section-heading"><div><h3>{v.title}</h3><p>{v.user_goal}</p></div><Badge>revision {v.number}</Badge></div><p><strong>Origin:</strong> {v.origin.kind} <code>{v.origin.id}</code>{v.origin.revision&&<> at <code>{v.origin.revision}</code></>} · <strong>Affected:</strong> {v.affected_components.join(", ")}</p>
 <h4>Journeys and states</h4><ul>{v.journeys.map(x=><li key={x.name}><strong>{x.name}:</strong> {x.steps.join(" → ")} — {x.outcome}</li>)}{v.states.map(x=><li key={x.name}><strong>{x.name}:</strong> {x.trigger} → {x.behavior}; “{x.content}”</li>)}</ul><h4>Constraints, contracts, breakpoints, and measures</h4><ul>{v.constraints.map((x,i)=><li key={`c${i}`}><Badge>{x.kind}</Badge> {x.requirement}</li>)}{v.component_contracts?.map(x=><li key={x.name}><strong>{x.name} contract:</strong> {x.contract}</li>)}{v.breakpoints?.map(x=><li key={x.name}><strong>{x.name}:</strong> {x.minimum_width}–{x.maximum_width||"∞"}px — {x.behavior}</li>)}{v.alternatives.map(x=><li key={x.name}><strong>{x.name}:</strong> {x.tradeoff} — {x.reason}</li>)}{v.success_measures.map(x=><li key={x.name}><strong>{x.name}:</strong> {x.target}</li>)}</ul>
 <p><strong>Evidence:</strong> {v.evidence.map(x=>x.summary).join("; ")||"No accessible evidence"}{p.private_evidence_count>0&&<> · <Badge>{p.private_evidence_count} restricted references not propagated</Badge></>}</p>{v.uncertainty.length>0&&<p><strong>Uncertainty:</strong> {v.uncertainty.join("; ")}</p>}
 {p.artifacts.map(a=>{const x=a.revisions[a.revisions.length-1];return <section key={a.id}><h4>{x.kind}: {x.title} <Badge>artifact v{x.number} · proposal r{x.proposal_revision}</Badge></h4>{x.frames.map(f=><figure key={f.name}><pre>{f.body}</pre><figcaption>{f.name} — {f.description}</figcaption></figure>)}{x.interactions.map((i,n)=><p key={n}>{i.trigger} → {i.action} → {i.result}</p>)}{x.assets?.map(asset=><p key={asset.id}><strong>Asset:</strong> {asset.name} by {asset.author_id} · {asset.license} · <code>{asset.source}</code>{asset.transformations?.length?` · ${asset.transformations.join(" → ")}`:""}</p>)}</section>})}
 <h4>Discussion</h4><ul>{p.comments.map(c=><li key={c.id}><Badge>{c.stance}</Badge> {c.body} — {c.author_id}, bound to {c.subject_kind} revision {c.subject_revision}{c.uncertainty&&<>; uncertainty: {c.uncertainty}</>}</li>)}</ul><p><strong>Owner acknowledgement:</strong> {p.acknowledgements.length?p.acknowledgements.map(a=>`${a.owner_id}: ${a.status}${a.current?"":" (stale)"}`).join("; "):"Not requested"}</p>
 {p.implementations?.map(i=><section key={i.id}><h4>Accountable implementation <Badge>design r{i.proposal_revision}</Badge></h4><p>Exact base <code>{i.base_revision}</code> · ordinary proposal <code>{i.work_proposal_id}</code></p><ol>{i.tasks.map(t=><li key={t.task_id}>{t.title} — {t.owner_kind} <code>{t.owner_id}</code></li>)}</ol><p><strong>Requirements:</strong> {i.requirements.map(r=>`${r.id} ${r.subject}`).join("; ")}</p>{i.assets?.map(a=><p key={a.id}>Exported {a.name}: {a.author_id}, {a.license}, <code>{a.source}</code></p>)}</section>)}
 {p.implementation_mappings?.map(m=><section key={m.id}><h4>Implementation mapping <Badge>{m.revision}</Badge></h4><p>Pull <code>{m.pull_request_id}</code> · {m.changed_paths.join(", ")} → {m.rendered_surfaces.join(", ")} → {m.requirement_ids.join(", ")}</p>{m.deviations?.map(d=><p key={d.requirement_id}><Badge>{d.status}</Badge> Deviation from {d.requirement_id}: {d.reason} — {d.impact}{d.approved_by_id&&` · approved by ${d.approved_by_id}`}</p>)}</section>)}
 {actor&&<><form className="workspace-form" onSubmit={e=>void comment(e,p)}><select name="stance" defaultValue="comment"><option>comment</option><option>support</option><option>dissent</option><option>question</option></select><textarea name="body" placeholder="Challenge the behavior or add context" required/><input name="uncertainty" placeholder="What remains uncertain?"/><Button type="submit">Add revision-bound comment</Button></form>{p.acknowledgements.some(a=>a.current&&a.status==="acknowledged")&&<details><summary>Carry accepted intent into implementation</summary><form className="workspace-form" onSubmit={e=>void implement(e,p)}><textarea name="contract" rows={12} aria-label="Ordered implementation contract" defaultValue={JSON.stringify({base_revision:"exact-source-commit",title:`Implement ${v.title}`,tasks:[{title:"Implement complete experience",outcome:v.user_goal,owner_kind:"agent",owner_id:"codex",acceptance_criteria:v.success_measures.map(x=>`${x.name}: ${x.target}`),changed_paths:["apps/web/component.tsx"],rendered_surfaces:["wide","compact","loading","error","success"]}]},null,2)} required/><Button type="submit">Create ordinary implementation tasks</Button></form></details>}</>}</article>})}</section>
}
