"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";
type Context={type:string;id?:string;path?:string}; type Citation={repository_id:string;commit_id:string;kind:string;path?:string;line_start?:number}; type Claim={id:string;text:string;mode:"evidence"|"inference"|"uncertainty";citations:Citation[];uncertainty?:string}; type Conversation={id:string;question:string;commit_id:string;context:Context;claims:Claim[]};
export function GroundedQuestions({repository,revision,context}:{repository:string;revision:string;context:Context}){
 const [items,setItems]=useState<Conversation[]>([]),[question,setQuestion]=useState(""),[active,setActive]=useState<Conversation>(),[claims,setClaims]=useState<Claim[]>([]),[status,setStatus]=useState(""),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/repositories/${repository}/questions`).then(async r=>r.ok?r.json():Promise.reject()).then((b:{items:Conversation[]})=>setItems(b.items)).catch(()=>undefined)},[repository]);
 async function ask(e:FormEvent){e.preventDefault();setError("");setClaims([]);setStatus("Pinning repository evidence…");const r=await fetch(`/api/repositories/${repository}/questions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,revision,context})});if(!r.ok){setError("The explanation could not be created.");setStatus("");return}const created=await r.json() as Conversation;setActive(created);setItems(v=>[created,...v]);setQuestion("");const stream=new EventSource(`/api/repositories/${repository}/questions/${created.id}/events`);stream.addEventListener("status",e=>setStatus((JSON.parse((e as MessageEvent).data) as {text:string}).text));stream.addEventListener("claim",e=>setClaims(v=>[...v,(JSON.parse((e as MessageEvent).data) as {claim:Claim}).claim]));stream.addEventListener("done",()=>{setStatus("Complete and reproducible");stream.close()});stream.onerror=()=>{stream.close();setClaims(created.claims);setStatus("Complete and reproducible")}}
 return <section className="grounded-questions panel"><div className="section-heading"><div><span className="eyebrow">Ask Codex</span><h2>Grounded explanation</h2><p>Answers stay pinned to one commit and separate evidence from inference.</p></div><Badge>{context.type}</Badge></div><form onSubmit={ask} className="grounded-question-form"><label htmlFor="grounded-question">Question about this context</label><textarea id="grounded-question" required maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="How does this behavior work, and what evidence supports it?"/><div className="form-actions"><small>Revision: <code>{revision||"default branch"}</code></small><Button type="submit">Ask with evidence</Button></div></form>{error&&<p className="form-error" role="alert">{error}</p>}{active&&<div className="grounded-answer" aria-live="polite"><div className="answer-meta"><strong>{active.question}</strong><small>{status} · <code>{active.commit_id.slice(0,12)}</code></small></div>{claims.map(c=><article key={c.id} className={`grounded-claim ${c.mode}`}><Badge>{c.mode}</Badge><p>{c.text}</p>{c.uncertainty&&<small>{c.uncertainty}</small>}<div className="claim-citations">{c.citations.map((x,i)=>x.path?<Link key={i} href={`/repositories/${x.repository_id}?view=code&ref=${x.commit_id}&path=${encodeURIComponent(x.path)}`}><code>{x.path}{x.line_start?`:${x.line_start}`:""}</code> · {x.kind}</Link>:<span key={i}><code>{x.commit_id.slice(0,12)}</code> · {x.kind}</span>)}</div></article>)}</div>}{items.length>0&&<details className="question-history"><summary>Prior explanations ({items.length})</summary>{items.map(item=><button type="button" key={item.id} onClick={()=>{setActive(item);setClaims(item.claims);setStatus("Replayed from durable evidence")}}><span>{item.question}</span><small><code>{item.commit_id.slice(0,12)}</code> · {item.context.type}</small></button>)}</details>}</section>
}
