"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Evidence={repository_id:string;commit_id:string;kind:string;path?:string;line?:number;label:string};
type Impact={id:string;category:string;summary:string;repository_id:string;owner_ids?:string[];verification?:string[];evidence:Evidence[];state:string;rationale?:string;acknowledgements?:{owner_id:string;state:string;note?:string}[]};
type Assessment={id:string;title:string;revision:string;commit_id:string;participants:string[];impacts:Impact[];unknowns:string[];analysis_status:string;analysis_reasons?:string[];agent_findings:{id:string;body:string;uncertainty?:string;evidence:Evidence[]}[]};

export function ImpactAssessments({repository,revision,selected,actor}:{repository:string;revision:string;selected?:string;actor:string}){
 const router=useRouter(),[items,setItems]=useState<Assessment[]>([]),[active,setActive]=useState<Assessment>(),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/repositories/${repository}/impact-assessments`).then(r=>r.ok?r.json():Promise.reject()).then(async(b:{items:Assessment[]})=>{setItems(b.items);const id=selected||b.items[0]?.id;if(id){const r=await fetch(`/api/repositories/${repository}/impact-assessments/${id}`);if(r.ok)setActive(await r.json())}}).catch(()=>undefined)},[repository,selected]);
 async function mutate(path:string,method:string,body:unknown){setError("");const r=await fetch(`/api/repositories/${repository}/impact-assessments${path}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("The assessment could not be updated. Confirm the revision, evidence, and owner authority.");return}const v=await r.json() as Assessment;setActive(v);setItems(old=>[v,...old.filter(x=>x.id!==v.id)]);return v}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),kind=String(f.get("kind")),value=String(f.get("source"));const source=kind==="symbol"?{kind,symbol:value}:kind==="diff"?{kind,diff:value}:{kind:"code",path:value};const v=await mutate("","POST",{title:f.get("title"),revision:f.get("revision"),sources:[source]});if(v)router.push(`/repositories/${repository}?view=impact&assessment=${v.id}&ref=${encodeURIComponent(v.commit_id)}`)}
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Before implementation</span><h2>Impact assessments</h2><p>Review revision-exact blast radius, verification, owners, accepted risks, and unknowns before code is written.</p></div><Badge>{items.length} assessments</Badge></div>
 <form className="investigation-create panel" onSubmit={create}><label>Title<input name="title" required maxLength={200}/></label><label>Revision<input name="revision" defaultValue={revision} required/></label><label>Starting point<select name="kind"><option value="code">Code path</option><option value="symbol">Symbol</option><option value="diff">Proposed diff</option></select></label><label className="wide">Selected path, symbol, or unified diff<textarea name="source" required maxLength={200000}/></label><Button type="submit">Assess impact</Button></form>{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="investigation-layout"><aside className="investigation-list panel">{items.map(x=><Link className={active?.id===x.id?"active":""} href={`/repositories/${repository}?view=impact&assessment=${x.id}&ref=${encodeURIComponent(x.commit_id)}`} key={x.id}><strong>{x.title}</strong><small><code>{x.commit_id.slice(0,12)}</code> · {x.analysis_status}</small></Link>)}{!items.length&&<p>No prospective assessments yet.</p>}</aside>
 {active&&<article className="investigation-canvas panel"><header><div><h3>{active.title}</h3><p>Evidence pinned to <code>{active.commit_id}</code></p></div><Badge>{active.analysis_status}</Badge></header>{active.unknowns.map(x=><p className="form-error" key={x}>Unknown: {x}</p>)}
 <ol className="investigation-entries">{active.impacts.map(x=><li key={x.id}><span><Badge>{x.category}</Badge><strong>{x.summary}</strong><Badge>{x.state.replaceAll("_"," ")}</Badge></span>{x.owner_ids?.length?<small>Affected owners: {x.owner_ids.join(", ")}</small>:null}{x.verification?.map(v=><p key={v}>Verify: <code>{v}</code></p>)}<div>{x.evidence.map((ev,i)=>ev.path?<Link key={i} href={`/repositories/${ev.repository_id}?view=code&ref=${ev.commit_id}&path=${encodeURIComponent(ev.path)}`}><code>{ev.path}{ev.line?`:${ev.line}`:""}</code></Link>:<span key={i}>{ev.kind}: {ev.label}</span>)}</div>
 <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${active.id}/impacts/${x.id}`,"PATCH",{state:f.get("state"),rationale:f.get("rationale")})}}><label>Decision<select name="state" defaultValue={x.state}><option value="open">Open</option><option value="mitigated">Mitigated</option><option value="accepted_risk">Accepted risk</option><option value="unknown">Unknown</option></select></label><label>Rationale<input name="rationale" defaultValue={x.rationale}/></label><Button type="submit" variant="secondary">Record</Button></form>
 {x.owner_ids?.map(owner=>{const acknowledgement=x.acknowledgements?.find(a=>a.owner_id===owner);return acknowledgement?.state==="requested"&&owner===actor?<form key={owner} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${active.id}/impacts/${x.id}/acknowledgements`,"PATCH",{state:f.get("state"),note:f.get("note")})}}><span>{owner}</span><select name="state"><option value="acknowledged">Acknowledge</option><option value="concern">Raise concern</option></select><input name="note" placeholder="Decision note"/><Button type="submit" variant="secondary">Respond</Button></form>:<form key={owner} onSubmit={e=>{e.preventDefault();void mutate(`/${active.id}/impacts/${x.id}/acknowledgements`,"POST",{owner_id:owner})}}><span>{owner}: {acknowledgement?.state||"not requested"}</span>{!acknowledgement&&<Button type="submit" variant="secondary">Request acknowledgement</Button>}</form>})}</li>)}</ol>
 {active.agent_findings?.map(x=><section key={x.id}><Badge>codex finding</Badge><p>{x.body}</p>{x.uncertainty&&<small>Uncertainty: {x.uncertainty}</small>}</section>)}
 <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${active.id}/impacts`,"POST",{category:f.get("category"),summary:f.get("summary"),repository_id:repository,evidence:[]})}}><label>Refine category<select name="category"><option>reference</option><option>test</option><option>owner</option><option>package</option><option>interface</option><option>consumer</option><option>release</option><option>environment</option></select></label><label>Additional impact<input name="summary" required/></label><Button type="submit">Refine scope</Button></form></article>}</div></section>
}
