"use client";

import Link from "next/link";
import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Release = { id: string; version: string };
type Attachment = { id?: string; kind: string; name: string; media_type: string; content: string };
type Issue = { id:string; reporter_id:string; title:string; expected_behavior:string; observed_behavior:string; severity:string; environment:string; reproduction_steps:string[]; affected_version?:string; affected_release_id?:string; visibility:string; status:string; attachments:Attachment[]; discussion?:Array<{id:string;author_id:string;body:string;created_at:string}>; history?:Array<{sequence:number;type:string;actor_id:string;created_at:string}> };

async function json<T>(url:string, init?:RequestInit):Promise<T>{const response=await fetch(`/api${url}`,init);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error((body as {error?:string}).error??"Request failed");return body as T}
async function fileContent(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let offset=0;offset<bytes.length;offset+=8192)binary+=String.fromCharCode(...bytes.subarray(offset,offset+8192));return btoa(binary)}

export function Issues({repository,actor,owner,selected}:{repository:string;actor:string;owner:string;selected?:string}){
  const [items,setItems]=useState<Issue[]>([]),[current,setCurrent]=useState<Issue>(),[releases,setReleases]=useState<Release[]>([]),[error,setError]=useState(""),[creating,setCreating]=useState(false),[duplicates,setDuplicates]=useState<Issue[]>([]),[comment,setComment]=useState("");
  const load=useCallback(async()=>{try{const [list,rels]=await Promise.all([json<{items:Issue[]}>(`/repositories/${repository}/issues`),json<{items:Release[]}>(`/repositories/${repository}/releases?per_page=100`)]);setItems(list.items);setReleases(rels.items);if(selected)setCurrent(await json<Issue>(`/repositories/${repository}/issues/${selected}`))}catch(e){setError(e instanceof Error?e.message:"Issues unavailable")}},[repository,selected]);
  useEffect(()=>{
    // Issue data follows the shareable selected issue URL.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load()
  },[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget), files=form.getAll("evidence") as File[];const attachments:Attachment[]=[];for(const file of files){if(!file.size)continue;attachments.push({kind:file.type.startsWith("image/")?"screenshot":String(form.get("attachment_kind")),name:file.name,media_type:file.type||"application/octet-stream",content:await fileContent(file)})}try{const issue=await json<Issue>(`/repositories/${repository}/issues`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:form.get("title"),expected_behavior:form.get("expected"),observed_behavior:form.get("observed"),severity:form.get("severity"),environment:form.get("environment"),reproduction_steps:String(form.get("steps")).split("\n").map(v=>v.trim()).filter(Boolean),affected_release_id:form.get("release"),visibility:form.get("visibility"),attachments})});window.location.assign(`/repositories/${repository}?view=issues&issue=${issue.id}`)}catch(e){setError(e instanceof Error?e.message:"Could not open issue")}}
  async function suggest(title:string){if(title.trim().length<3){setDuplicates([]);return}try{setDuplicates((await json<{items:Issue[]}>(`/repositories/${repository}/issues/suggestions?q=${encodeURIComponent(title)}`)).items)}catch{setDuplicates([])}}
  async function discuss(event:FormEvent){event.preventDefault();if(!current)return;try{setCurrent(await json<Issue>(`/repositories/${repository}/issues/${current.id}/comments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:comment})}));setComment("")}catch(e){setError(e instanceof Error?e.message:"Could not comment")}}
  async function changeStatus(){if(!current)return;try{setCurrent(await json<Issue>(`/repositories/${repository}/issues/${current.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:current.status==="open"?"closed":"open"})}))}catch(e){setError(e instanceof Error?e.message:"Could not change status")}}
  if(current)return <section className="workspace"><div className="section-heading"><div><p className="eyebrow">Issue · {current.severity}</p><h2>{current.title}</h2></div><div><Link href={`/repositories/${repository}?view=issues`}>All issues</Link>{(actor===current.reporter_id||actor===owner)&&<Button onClick={()=>void changeStatus()}>{current.status==="open"?"Close issue":"Reopen issue"}</Button>}</div></div><div className="card"><p><Badge>{current.status}</Badge> Reported by {current.reporter_id}{current.affected_version&&<> against <strong>{current.affected_version}</strong></>}</p><h3>Expected behavior</h3><p>{current.expected_behavior}</p><h3>Observed behavior</h3><p>{current.observed_behavior}</p><h3>Environment</h3><p>{current.environment}</p><h3>Reproduction steps</h3><ol>{current.reproduction_steps.map((step,i)=><li key={i}>{step}</li>)}</ol><h3>Evidence</h3>{current.attachments.length?<ul>{current.attachments.map(a=><li key={a.id}><a href={`data:${a.media_type};base64,${a.content}`} download={a.name}>{a.kind}: {a.name}</a> ({a.media_type}){a.kind==="screenshot"&&<div><Image unoptimized width={800} height={450} src={`data:${a.media_type};base64,${a.content}`} alt={`Attached screenshot ${a.name}`} style={{maxWidth:"100%",height:"auto"}} /></div>}</li>)}</ul>:<p>No evidence attached.</p>}</div><div className="card"><h3>Discussion</h3>{current.discussion?.map(c=><div key={c.id}><strong>{c.author_id}</strong><p>{c.body}</p></div>)}{actor&&<form onSubmit={discuss}><label>Reply<textarea value={comment} onChange={e=>setComment(e.target.value)} required /></label><Button type="submit">Add comment</Button></form>}</div><div className="card"><h3>History</h3>{current.history?.map(e=><p key={e.sequence}><strong>{e.type}</strong> by {e.actor_id}</p>)}</div></section>;
  return <section className="workspace"><div className="section-heading"><div><p className="eyebrow">Actionable problem reports</p><h2>Issues</h2></div>{actor&&<Button onClick={()=>setCreating(!creating)}>{creating?"Cancel":"Report a problem"}</Button>}</div>{error&&<p className="form-error" role="alert">{error}</p>}{creating&&<form className="card form-stack" onSubmit={submit}><p className="muted">Unexpected behavior template · required fields help maintainers begin without an external support thread.</p><label>Title<input name="title" required maxLength={200} onChange={e=>void suggest(e.target.value)} /></label>{duplicates.length>0&&<div><strong>Possible duplicates</strong>{duplicates.map(v=><p key={v.id}><Link href={`/repositories/${repository}?view=issues&issue=${v.id}`}>{v.title}</Link></p>)}</div>}<label>Expected behavior<textarea name="expected" required /></label><label>Observed behavior<textarea name="observed" required /></label><label>Environment<textarea name="environment" required placeholder="OS, browser/runtime, hardware, configuration" /></label><label>Reproduction steps<textarea name="steps" required placeholder={"One step per line"} /></label><label>Severity<select name="severity" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Affected release<select name="release" defaultValue=""><option value="">Repository / unreleased</option>{releases.map(v=><option value={v.id} key={v.id}>{v.version}</option>)}</select></label><label>Visibility<select name="visibility"><option value="public">Public</option><option value="repository">Repository participants only</option></select></label><label>Evidence type<select name="attachment_kind"><option value="log">Log</option><option value="trace">Trace</option><option value="sample_input">Sample input</option></select></label><label>Attach permitted evidence<input type="file" name="evidence" multiple accept="image/png,image/jpeg,text/plain,application/json,application/octet-stream" /></label><p className="muted">Up to 10 files, 1 MiB each. Remove secrets and private data before uploading.</p><Button type="submit">Open issue</Button></form>}<div className="card-list">{items.map(v=><Link className="card" href={`/repositories/${repository}?view=issues&issue=${v.id}`} key={v.id}><p><Badge>{v.status}</Badge> <Badge>{v.severity}</Badge></p><h3>{v.title}</h3><p>{v.observed_behavior}</p><small>Reported by {v.reporter_id}{v.affected_version&&` · ${v.affected_version}`}</small></Link>)}</div></section>
}
