"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Reference = { kind: string; id: string; revision?: string; summary: string };
type Settlement = { milestone_id: string; recipient_id: string; state: string; awarded: number; released: number; payment_state: string; events: Array<{ id: string; kind: string; actor_id: string; rationale: string; award?: number; evidence: Reference[] }> };
type Execution = { state: string; active_recipient_id: string; budget: number; approved_expenses: number; agent_compute: number; blockers: Array<{ kind: string; detail: string }>; forecast: { percent: number; status: string; remaining_budget: number }; progress: Array<{ id: string; actor_id: string; milestone_id: string; status: string; percent: number; summary: string; evidence: Reference[] }>; expenses: Array<{ id: string; actor_id: string; amount: number; description: string; state: string }>; changes: Array<{ id: string; actor_id: string; kind: string; reason: string; from_recipient_id?: string; to_recipient_id?: string }>; milestone_settlements: Settlement[] };
type Proposal = { id: string; version: number; state: string; terms: { recipient_kind: string; recipient_id: string; approach: string; cost: number; milestones: Array<{ id: string; cost: number; deliverables: string[] }> }; approvals: Array<{ actor_id: string }>; selection?: { steward_id: string; reason: string; reservation_id: string }; execution?: Execution; operational_authority: string[] };
type Outcome = { id: string; fund_id: string; version: number; pledged: number; versions: Array<{ version: number; author_id: string; change_reason: string; terms: { title: string; scope: string; budget: number; deadline: string; origin: { kind: string; resource_id: string }; acceptance_criteria: string[]; evidence_requirements: string[]; milestones: Array<{ id: string; name: string; budget: number }> } }>; blockers: Array<{ kind: string; detail: string; resource_id?: string }>; replanning: Array<{ kind: string; actor_id: string; reason: string }>; delivery: Array<{ delivery_proposal_id: string; recipient_id: string; execution: Execution }>; operational_authority: string[] };
type Fund = { id: string; version: number; terms: { name: string; description: string; steward_ids: string[]; accepted_funding_sources: string[]; unit: string; unit_kind: string; spending_limits: { per_allocation: number; per_recipient: number; total: number }; approval_rule: { minimum_approvals: number; approver_ids: string[]; threshold: number }; eligible_recipients: string[]; refund_policy: string; ledger_visibility: string }; balances: { available: number; reserved: number; spent: number; refunded: number; disputed: number }; transfers: Array<{ id: string; reference: string; source: string; contributor_id: string; requested: number; settled: number; state: string; note?: string }> };

const lines = (value: FormDataEntryValue | null) => String(value ?? "").split("\n").map(x => x.trim()).filter(Boolean);

export function ProjectFunds({ repository, actor }: { repository: string; actor: string }) {
  const [funds, setFunds] = useState<Fund[]>([]);
  const [outcomes, setOutcomes] = useState<Outcome[]>([]);
  const [proposals, setProposals] = useState<Record<string, Proposal[]>>({});
  const [error, setError] = useState("");
  const root = `/api/repositories/${repository}`;
  const refresh = useCallback(async () => {
    const [fundResponse, outcomeResponse] = await Promise.all([fetch(`${root}/funds`), fetch(`${root}/funded-outcomes`)]);
    if (!fundResponse.ok || !outcomeResponse.ok) return;
    const nextFunds = (await fundResponse.json()).items as Fund[];
    const nextOutcomes = (await outcomeResponse.json()).items as Outcome[];
    setFunds(nextFunds); setOutcomes(nextOutcomes);
    const entries = await Promise.all(nextOutcomes.map(async outcome => {
      const response = await fetch(`${root}/funded-outcomes/${outcome.id}/delivery-proposals`);
      return [outcome.id, response.ok ? (await response.json()).items : []] as const;
    }));
    setProposals(Object.fromEntries(entries));
  }, [root]);
  useEffect(() => {
    const timer = window.setTimeout(() => void refresh(), 0);
    return () => window.clearTimeout(timer);
  }, [refresh]);

  async function send(path: string, body: unknown) {
    setError("");
    const response = await fetch(`${root}${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    if (!response.ok) { setError((await response.json()).error); return; }
    await refresh();
  }

  function createFund(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const f = new FormData(event.currentTarget);
    void send("/funds", { name: f.get("name"), description: f.get("description"), steward_ids: lines(f.get("stewards")), accepted_funding_sources: lines(f.get("sources")), unit: f.get("unit"), unit_kind: f.get("kind"), spending_limits: { per_allocation: Number(f.get("allocation")), per_recipient: Number(f.get("recipient")), total: Number(f.get("total")) }, approval_rule: { minimum_approvals: Number(f.get("approvals")), approver_ids: lines(f.get("approvers")), threshold: Number(f.get("threshold")) }, eligible_recipients: lines(f.get("eligible")), refund_policy: f.get("refund"), ledger_visibility: f.get("visibility") });
  }

  function createOutcome(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const f = new FormData(event.currentTarget); const budget = Number(f.get("budget")); const milestone = String(f.get("milestone"));
    void send("/funded-outcomes", { fund_id: f.get("fund"), terms: { origin: { kind: "roadmap_outcome", resource_id: f.get("roadmap") }, title: f.get("title"), scope: f.get("scope"), acceptance_criteria: lines(f.get("acceptance")), evidence_requirements: lines(f.get("evidence")), budget, deadline: new Date(String(f.get("deadline"))).toISOString(), contributor_eligibility: lines(f.get("eligibility")), allocation_method: "reviewed milestone award", cancellation_terms: f.get("cancellation"), milestones: [{ id: milestone, name: milestone, budget, acceptance_criteria: lines(f.get("acceptance")), evidence_requirements: lines(f.get("evidence")), reviewer_ids: lines(f.get("reviewers")) }], dependencies: [], risks: [], declared_conflicts: [], overlap_keys: [String(f.get("roadmap"))], embargoed: false } });
  }

  return <section className="investigation-workspace">
    <div className="section-heading"><div><span className="eyebrow">Backing → evidence → receipt</span><h2>Project funding</h2><p>Fund measurable roadmap work, compare human and approved-agent offers, and follow ordinary delivery evidence. Financial participation grants no repository authority.</p></div><Badge>{funds.length} funds · {outcomes.length} outcomes</Badge></div>
    {error && <p className="form-error">{error}</p>}
    <details><summary>Create governed fund</summary><form onSubmit={createFund}>
      <label>Name<input name="name" required /></label><label>Description<textarea name="description" /></label><label>Steward IDs<textarea name="stewards" defaultValue={actor} required /></label><label>Accepted sources<textarea name="sources" placeholder="stripe" required /></label><label>Unit<input name="unit" placeholder="USD" required /></label><label>Type<select name="kind"><option>currency</option><option>credit</option></select></label><label>Per-allocation limit<input name="allocation" type="number" min="1" required /></label><label>Per-recipient limit<input name="recipient" type="number" min="1" required /></label><label>Total limit<input name="total" type="number" min="1" required /></label><label>Approver IDs<textarea name="approvers" defaultValue={actor} required /></label><label>Minimum approvals<input name="approvals" type="number" min="1" defaultValue="1" required /></label><label>Approval threshold<input name="threshold" type="number" min="0" defaultValue="0" /></label><label>Eligible recipient classes<textarea name="eligible" defaultValue={"human\napproved_agent_operator"} required /></label><label>Refund policy<textarea name="refund" required /></label><label>Ledger visibility<select name="visibility"><option value="public">Public</option><option value="repository">Repository readers</option></select></label><Button type="submit">Publish fund terms</Button>
    </form></details>
    {funds.length > 0 && <details><summary>Fund a roadmap outcome</summary><form onSubmit={createOutcome}>
      <label>Fund<select name="fund">{funds.map(f => <option value={f.id} key={f.id}>{f.terms.name} · available {f.balances.available}</option>)}</select></label><label>Roadmap outcome ID<input name="roadmap" required /></label><label>Title<input name="title" required /></label><label>Scope<textarea name="scope" required /></label><label>Milestone ID<input name="milestone" required /></label><label>Budget<input name="budget" type="number" min="1" required /></label><label>Deadline<input name="deadline" type="datetime-local" required /></label><label>Acceptance criteria<textarea name="acceptance" required /></label><label>Evidence requirements<textarea name="evidence" required /></label><label>Eligible contributor classes<textarea name="eligibility" defaultValue={"human\napproved_agent_operator"} required /></label><label>Reviewer IDs<textarea name="reviewers" defaultValue={actor} /></label><label>Cancellation and refund terms<textarea name="cancellation" required /></label><Button type="submit">Publish measurable outcome</Button>
    </form></details>}

    {funds.map(f => <article className="card" key={f.id}><h3>{f.terms.name} <Badge>{f.terms.unit_kind}</Badge></h3><p>{f.terms.description}</p><p><strong>Balances ({f.terms.unit} minor units):</strong> available {f.balances.available} · reserved {f.balances.reserved} · spent {f.balances.spent} · refunded {f.balances.refunded} · disputed {f.balances.disputed}</p><p><strong>Stewards:</strong> {f.terms.steward_ids.join(" · ")}<br /><strong>Approvals:</strong> {f.terms.approval_rule.minimum_approvals} of {f.terms.approval_rule.approver_ids.join(" · ")}<br /><strong>Limits:</strong> allocation {f.terms.spending_limits.per_allocation} · recipient {f.terms.spending_limits.per_recipient} · total {f.terms.spending_limits.total}<br /><strong>Refunds:</strong> {f.terms.refund_policy}</p><details><summary>Commit resources</summary><form onSubmit={event => { event.preventDefault(); const x = new FormData(event.currentTarget); void send(`/funds/${f.id}/commitments`, { reference: x.get("reference"), source: x.get("source"), amount: Number(x.get("amount")), state: "pending" }); }}><label>Provider reference<input name="reference" required /></label><label>Source<select name="source">{f.terms.accepted_funding_sources.map(x => <option key={x}>{x}</option>)}</select></label><label>Amount<input name="amount" type="number" min="1" required /></label><Button type="submit">Record pending commitment</Button></form></details><h4>Ledger</h4>{f.transfers.length ? f.transfers.map(x => <p key={x.id}><Badge>{x.state}</Badge> {x.source} · {x.reference} · requested {x.requested} · settled {x.settled} · contributor {x.contributor_id}</p>) : <p>No commitments recorded.</p>}</article>)}

    {outcomes.map(outcome => { const terms = outcome.versions.at(-1)!.terms; return <article className="card" key={outcome.id}><h3>{terms.title} <Badge>{outcome.pledged}/{terms.budget} backed</Badge></h3><p><strong>Roadmap origin:</strong> {terms.origin.resource_id}<br /><strong>Scope v{outcome.version}:</strong> {terms.scope}<br /><strong>Deadline:</strong> {new Date(terms.deadline).toLocaleString()}</p><p><strong>Acceptance:</strong> {terms.acceptance_criteria.join(" · ")}<br /><strong>Evidence:</strong> {terms.evidence_requirements.join(" · ")}</p>{outcome.blockers.map((b, index) => <p className="form-error" key={`${b.kind}-${index}`}><Badge>{b.kind}</Badge> {b.detail}</p>)}{outcome.replanning.map((r, index) => <p key={`${r.kind}-${index}`}><strong>{r.kind}</strong> by {r.actor_id}: {r.reason}</p>)}<details><summary>Back this outcome</summary><form onSubmit={event => { event.preventDefault(); const x = new FormData(event.currentTarget); void send(`/funded-outcomes/${outcome.id}/pledges`, { target: x.get("target"), amount: Number(x.get("amount")) }); }}><label>Target<select name="target"><option value="outcome">Whole outcome</option>{terms.milestones.map(m => <option value={`milestone:${m.id}`} key={m.id}>{m.name}</option>)}</select></label><label>Amount<input name="amount" type="number" min="1" required /></label><Button type="submit">Pledge backing</Button></form></details><details><summary>Offer delivery</summary><form onSubmit={event => { event.preventDefault(); const x = new FormData(event.currentTarget); const cost = Number(x.get("cost")); const milestone = String(x.get("milestone")); void send(`/funded-outcomes/${outcome.id}/delivery-proposals`, { terms: { recipient_kind: x.get("kind"), recipient_id: x.get("recipient"), approach: x.get("approach"), milestones: [{ id: milestone, approach: x.get("approach"), cost, deliverables: lines(x.get("deliverables")) }], cost, dependencies: [], availability: x.get("availability"), required_access: lines(x.get("access")), relevant_attributed_work: [] } }); }}><label>Recipient class<select name="kind"><option value="human">Human</option><option value="approved_agent_operator">Approved agent operator</option></select></label><label>Recipient ID<input name="recipient" defaultValue={actor} required /></label><label>Milestone<select name="milestone">{terms.milestones.map(m => <option key={m.id}>{m.id}</option>)}</select></label><label>Cost<input name="cost" type="number" min="1" required /></label><label>Approach<textarea name="approach" required /></label><label>Deliverables<textarea name="deliverables" required /></label><label>Availability<input name="availability" required /></label><label>Requested access (descriptive only)<textarea name="access" /></label><Button type="submit">Submit delivery offer</Button></form></details>
      {(proposals[outcome.id] ?? []).map(p => <section key={p.id}><h4>{p.terms.recipient_id} · {p.terms.recipient_kind} <Badge>{p.state}</Badge></h4><p>{p.terms.approach} · {p.terms.cost} requested · {p.approvals.length} approvals</p>{p.state === "proposed" && p.terms.recipient_id === actor && <Button onClick={() => void send(`/funded-outcomes/${outcome.id}/delivery-proposals/${p.id}/accept`, { expected_version: p.version })}>Accept offer</Button>}{p.state === "accepted" && <><Button onClick={() => void send(`/funded-outcomes/${outcome.id}/delivery-proposals/${p.id}/approve`, { expected_version: p.version })}>Approve offer</Button> <Button onClick={() => void send(`/funded-outcomes/${outcome.id}/delivery-proposals/${p.id}/select`, { expected_version: p.version, reason: "selected through visible fund governance", connections: [] })}>Select and reserve</Button></>}{p.execution && <ExecutionTrail execution={p.execution} />}</section>)}
    </article>; })}
  </section>;
}

function ExecutionTrail({ execution }: { execution: Execution }) {
  return <div><p><strong>Execution:</strong> {execution.state} · active recipient {execution.active_recipient_id} · {execution.forecast.percent}% · {execution.forecast.status}<br /><strong>Account:</strong> budget {execution.budget} · expenses {execution.approved_expenses} · compute {execution.agent_compute} · remaining {execution.forecast.remaining_budget}</p>{execution.blockers.map((b, index) => <p className="form-error" key={`${b.kind}-${index}`}><Badge>{b.kind}</Badge> {b.detail}</p>)}{execution.progress.map(p => <p key={p.id}><Badge>{p.status}</Badge> {p.milestone_id} · {p.percent}% · {p.actor_id}: {p.summary}<br />{p.evidence.map(e => `${e.kind}:${e.id}`).join(" · ")}</p>)}{execution.expenses.map(e => <p key={e.id}><Badge>{e.state}</Badge> expense {e.amount} by {e.actor_id}: {e.description}</p>)}{execution.changes.map(c => <p key={c.id}><Badge>{c.kind}</Badge> {c.actor_id}: {c.reason}{c.to_recipient_id && ` · ${c.from_recipient_id} → ${c.to_recipient_id}`}</p>)}{execution.milestone_settlements.map(s => <div key={s.milestone_id}><h4>Receipt · {s.milestone_id} <Badge>{s.payment_state}</Badge></h4><p>Original recipient {s.recipient_id} · awarded {s.awarded} · released {s.released} · {s.state}</p>{s.events.map(e => <p key={e.id}><strong>{e.kind}</strong> by {e.actor_id}{e.award ? ` · award ${e.award}` : ""}: {e.rationale}</p>)}</div>)}</div>;
}
