"use client";
import {useCallback,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";

type Rule={kind:string;permitted_origins:string[];permitted_licenses:string[];permitted_uses:string[];required_attribution:string[];contributor_attestations:string[];review_owner_ids:string[]};
type Version={number:number;name:string;description:string;material_rules:Rule[];distribution_contexts:{id:string;audience:string;uses:string[];licenses:string[];notice_required:boolean;owner_ids:string[]}[];links:{kind:string;reference:string;revision?:string;boundary?:string}[];exceptions:{id:string;rationale:string;owner_id:string;expires_at:string}[];owner_ids:string[];change_reason:string;author_id:string;published_at:string};
type Policy={id:string;current_version:number;versions:Version[];blockers:{kind:string;subject:string;detail:string;attributed_to?:string}[]};
const starter=JSON.stringify({material_rules:[{kind:"source",permitted_origins:["original","reviewed contribution"],permitted_licenses:["Apache-2.0"],permitted_uses:["modify","public_distribution"],required_attribution:["retain copyright and license notices"],contributor_attestations:["developer certificate of origin"],review_owner_ids:["legal-owner"]},{kind:"generated_code",permitted_origins:["approved generator at an exact revision"],permitted_licenses:["Apache-2.0"],permitted_uses:["modify","public_distribution"],required_attribution:["identify generator and source inputs"],contributor_attestations:["agent contract attestation"],review_owner_ids:["maintainer"]},{kind:"package",permitted_origins:["verified registry publisher"],permitted_licenses:["Apache-2.0","MIT"],permitted_uses:["build","public_distribution"],required_attribution:["dependency notices"],contributor_attestations:[],review_owner_ids:["dependency-owner"]}],distribution_contexts:[{id:"public-release",audience:"public",uses:["public_distribution"],licenses:["Apache-2.0","MIT"],notice_required:true,owner_ids:["release-owner"]}],links:[{kind:"contributor_pathway",reference:"pathway:external"},{kind:"agent_contract",reference:"agent-contract:delivery",revision:"v1"},{kind:"contribution_boundary",reference:"federated:upstream",boundary:"federated"}],exceptions:[],owner_ids:["project-owner"]},null,2);
const body=(v:Version)=>JSON.stringify({material_rules:v.material_rules,distribution_contexts:v.distribution_contexts,links:v.links,exceptions:v.exceptions,owner_ids:v.owner_ids},null,2);
export function ProvenancePolicies({scope,id,canManage}:{scope:"repositories"|"organizations";id:string;canManage:boolean}){const root=`/api/${scope}/${id}/provenance-policies`;const[items,setItems]=useState<Policy[]>([]);const[error,setError]=useState("");const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems((await r.json() as {items:Policy[]}).items)},[root]);useEffect(()=>{void load()},[load]);
async function submit(e:React.FormEvent<HTMLFormElement>,p?:Policy){e.preventDefault();const f=new FormData(e.currentTarget);try{const payload={...JSON.parse(String(f.get("definition"))) as object,name:f.get("name"),description:f.get("description"),change_reason:f.get("change_reason"),...(p?{expected_version:p.current_version}:{})};const r=await fetch(p?`${root}/${p.id}/versions`:root,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){setError((await r.json() as {error:string}).error);return};setError("");await load()}catch{setError("invalid_provenance_policy_json")}}
const form=(p?:Policy)=>{const v=p?.versions.at(-1);return <form className="workspace-form" onSubmit={e=>void submit(e,p)}><input name="name" required placeholder="Policy name" defaultValue={v?.name}/><textarea name="description" required placeholder="Which material may enter and how it may be distributed" defaultValue={v?.description}/><textarea name="definition" rows={22} required aria-label="Structured provenance policy as JSON" defaultValue={v?body(v):starter}/><input name="change_reason" required placeholder="Why this policy changed"/><Button type="submit">{p?`Publish version ${p.current_version+1}`:"Publish provenance policy"}</Button></form>};
return <section className="panel"><p className="eyebrow">Accept before release</p><div className="section-heading"><div><h2>Provenance and licensing</h2><p>Make permitted origins, licenses, uses, attribution, attestations, reviewers, distribution, and bounded exceptions clear before material enters the product.</p></div><Badge>{items.length} policies</Badge></div>{error&&<p role="alert" className="form-error">{error.replaceAll("_"," ")}</p>}{canManage&&<details><summary>Define a versioned provenance policy</summary>{form()}</details>}{items.map(p=>{const v=p.versions.at(-1)!;return <article className="workspace-card" key={p.id}><div className="section-heading"><div><h3>{v.name}</h3><p>{v.description}</p></div><Badge>version {v.number}</Badge></div><p><strong>Owners:</strong> {v.owner_ids.join(", ")||"missing"}</p>{p.blockers.length>0&&<><h4>Explicit blockers</h4><ul>{p.blockers.map((b,i)=><li key={i}><Badge>{b.kind}</Badge> <strong>{b.subject}</strong> — {b.detail}{b.attributed_to&&` · ${b.attributed_to}`}</li>)}</ul></>}<h4>Material acceptance</h4><ul>{v.material_rules.map(r=><li key={r.kind}><strong>{r.kind.replaceAll("_"," ")}</strong> · origins {r.permitted_origins.join(", ")} · licenses {r.permitted_licenses.join(", ")} · uses {r.permitted_uses.join(", ")}<br/>Review: {r.review_owner_ids.join(", ")||"missing"}; attestations: {r.contributor_attestations.join(", ")||"none"}; attribution: {r.required_attribution.join(", ")||"none"}</li>)}</ul><h4>Distribution contexts</h4><ul>{v.distribution_contexts.map(c=><li key={c.id}><Badge>{c.audience}</Badge> <strong>{c.id}</strong> · {c.licenses.join(", ")} · notices {c.notice_required?"required":"not required"} · owners {c.owner_ids.join(", ")||"missing"}</li>)}</ul><p><strong>Connected boundaries:</strong> {v.links.map(l=>`${l.kind}: ${l.reference}${l.revision?`@${l.revision}`:""}${l.boundary?` (${l.boundary})`:""}`).join(" · ")||"none"}</p><details><summary>Immutable history ({p.versions.length} versions)</summary><ol>{p.versions.map(h=><li key={h.number}>v{h.number}: {h.change_reason} · {h.author_id} · {new Date(h.published_at).toLocaleString()}</li>)}</ol></details>{canManage&&<details><summary>Revise this policy</summary>{form(p)}</details>}</article>})}</section>}
