/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";
type V={number:number;title:string;description:string;owner_ids:string[];author_id:string;resources:{id:string;kind:string;name:string;user_capability:string;owner_ids:string[];acceptable_loss:string;restoration_time:string;retention:string;jurisdictions:string[];validation_criteria:string[];feasibility:string}[];dependencies:{id:string;name:string;protected:boolean;protection_reference?:string;owner_ids:string[]}[];links:{kind:string;resource_id:string;label:string}[];declared_exclusions:{scope:string;reason:string;approved_by:string}[]};
type O={id:string;versions:V[];blockers:{kind:string;detail:string}[]};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean),csv=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean),rows=(v:FormDataEntryValue|null)=>lines(v).map(x=>x.split("|").map(y=>y.trim()));
export function RecoveryObjectives({repository,actor}:{repository:string;actor:string}){
 const root=`/api/repositories/${repository}/recovery-objectives`,[items,setItems]=useState<O[]>([]),[error,setError]=useState("");const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems(((await r.json()) as {items:O[]}).items)},[root]);useEffect(()=>{void load()},[load]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={title:f.get("title"),description:f.get("description"),owner_ids:csv(String(f.get("owners")||actor)),resources:rows(f.get("resources")).map(x=>({id:x[0],kind:x[1],resource_id:x[2]||undefined,name:x[3],user_capability:x[4],owner_ids:csv(x[5]),dependency_ids:csv(x[6]),acceptable_loss:x[7],restoration_time:x[8],retention:x[9],jurisdictions:csv(x[10]),validation_criteria:csv(x[11]),feasibility:x[12],feasibility_rationale:x[13]||undefined})),dependencies:rows(f.get("dependencies")).map(x=>({id:x[0],name:x[1],kind:x[2],owner_ids:csv(x[3]),protected:x[4]==="protected",protection_reference:x[5]||undefined})),links:rows(f.get("links")).map(x=>({kind:x[0],resource_id:x[1],label:x[2]})),declared_exclusions:rows(f.get("exclusions")).map(x=>({scope:x[0],reason:x[1],approved_by:x[2]})),exceptions:rows(f.get("exceptions")).map(x=>({id:x[0],scope:x[1],reason:x[2],owner_id:x[3],approved_by:x[4],expires_at:x[5]})),exception_policy:f.get("policy"),change_reason:f.get("reason")};const r=await fetch(root,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}setError("");e.currentTarget.reset();await load()}
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">State → loss tolerance → restoration → validation</span><h2>Continuity commitments</h2><p>Make the state behind user-facing capabilities, acceptable loss, restoration time, and accountable recovery ownership explicit before a serious failure.</p></div><Badge>{items.length} objectives</Badge></div>
 <details className="panel"><summary>Define a recovery objective</summary><form className="stacked-form" onSubmit={submit}><label>Title<input name="title" required /></label><label>Description<textarea name="description" required /></label><label>Commitment owners<input name="owners" defaultValue={actor} /></label><label>Resources <small>id | kind | resource id | name | user capability | owners | dependencies | loss | restore | retention | jurisdictions | validation criteria | feasibility | rationale</small><textarea name="resources" rows={5} placeholder={`git | repository | | Git history | Contributors resume work | ${actor} | object-store | 0s | 2h | 7y | EU,US | refs resolve,commits reachable | achievable |`} required /></label><label>Dependencies <small>id | name | kind | owners | protected/unprotected | protection reference</small><textarea name="dependencies" rows={3} /></label><label>Links <small>service_objective/environment/incident/privacy_rule/governance | resource id | label</small><textarea name="links" rows={3} /></label><label>Declared exclusions <small>scope | reason | approver</small><textarea name="exclusions" /></label><label>Exceptions <small>id | scope | reason | owner | approver | RFC3339 expiry</small><textarea name="exceptions" /></label><label>Exception policy<textarea name="policy" required /></label><label>Change reason<input name="reason" required /></label><Button type="submit">Publish continuity terms</Button></form></details>{error&&<p className="form-error">{error.replaceAll("_"," ")}</p>}
 {items.map(x=>{const v=x.versions.at(-1)!;return <article className="panel" key={x.id}><header><div><span className="eyebrow">version {v.number} · {v.author_id}</span><h3>{v.title}</h3><p>{v.description}</p></div><Badge>{x.blockers.length?`${x.blockers.length} explicit blockers`:"targets supported"}</Badge></header>{x.blockers.map((b,i)=><p className="form-error" key={i}><strong>{b.kind.replaceAll("_"," ")}:</strong> {b.detail}</p>)}<p><strong>Commitment owners:</strong> {v.owner_ids.join(", ")||"missing"}</p><h4>State that must survive</h4>{v.resources.map(r=><div key={r.id}><p><Badge>{r.kind.replaceAll("_"," ")}</Badge> <strong>{r.name}</strong> — {r.user_capability}</p><p>Loss ≤ <strong>{r.acceptable_loss}</strong> · restore ≤ <strong>{r.restoration_time}</strong> · retain {r.retention} · {r.jurisdictions.join(", ")} · owners {r.owner_ids.join(", ")||"missing"}</p><p><strong>Validation:</strong> {r.validation_criteria.join("; ")} · <Badge>{r.feasibility}</Badge></p></div>)}<h4>Dependencies and context</h4>{v.dependencies.map(d=><p key={d.id}><Badge>{d.protected?"protected":"unprotected"}</Badge> {d.name} · {d.owner_ids.join(", ")||"missing owner"} {d.protection_reference&&`· ${d.protection_reference}`}</p>)}<p>{v.links.map(l=>`${l.kind}: ${l.label} (${l.resource_id})`).join(" · ")||"No links declared"}</p>{v.declared_exclusions.map((q,i)=><p key={i}><strong>Excluded:</strong> {q.scope} — {q.reason} · {q.approved_by}</p>)}</article>})}</section>
}
