"use client";

import {FormEvent,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";

type Boundary={kind:"revision"|"release";reference:string;commit_id:string;release_id?:string};
type Scope={expected_behavior:string;regressed_behavior:string;known_good:Boundary;known_bad:Boundary;environments:string[];comparability:string;severity:string;owner_ids:string[];acceptance_criteria:string[]};
type Entry={id:string;sequence:number;kind:string;body:string;actor_id:string;created_at:string};
type Investigation={id:string;title:string;source:{kind:string;resource_id:string};version:number;scope:Scope;status:string;blockers:string[];stale_inputs:string[];evidence:{id:string;kind:string;resource_id:string;summary:string;actor_id:string}[];entries:Entry[];updated_at:string};
const split=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);

export function RegressionInvestigations({repository,revision}:{repository:string;revision:string}){
 const [items,setItems]=useState<Investigation[]>([]),[active,setActive]=useState<Investigation>(),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/repositories/${repository}/regression-investigations`).then(r=>r.ok?r.json():Promise.reject()).then(async(b:{items:Investigation[]})=>{setItems(b.items);if(b.items[0]){const r=await fetch(`/api/repositories/${repository}/regression-investigations/${b.items[0].id}`);if(r.ok)setActive(await r.json())}}).catch(()=>undefined)},[repository]);
 async function send(path:string,method:string,body:unknown){setError("");const r=await fetch(`/api/repositories/${repository}/regression-investigations${path}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("The regression boundary could not be saved. Check ancestry, evidence visibility, and the current version.");return}const v=await r.json() as Investigation;setActive(v);setItems(old=>[v,...old.filter(x=>x.id!==v.id)])}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await send("","POST",{title:f.get("title"),source:{kind:f.get("source_kind"),resource_id:f.get("source_id")},scope:{expected_behavior:f.get("expected"),regressed_behavior:f.get("regressed"),known_good:{kind:f.get("good_kind"),reference:f.get("good")},known_bad:{kind:f.get("bad_kind"),reference:f.get("bad")},environments:split(f.get("environments")),comparability:f.get("comparability"),severity:f.get("severity"),owner_ids:split(f.get("owners")),acceptance_criteria:split(f.get("criteria"))}})}
 return <section className="regression-workspace panel">
  <header><div><span className="eyebrow">Before the bisect</span><h2>Regression search boundaries</h2><p>Agree on observable behavior, comparable endpoints, and the eligible history before testing commits.</p></div><Badge>{items.length} investigations</Badge></header>
  <form className="regression-create" onSubmit={create}><label>Title<input name="title" required/></label><label>Opened from<select name="source_kind"><option value="issue">Issue</option><option value="support_thread">Support thread</option><option value="failed_check">Failed check</option><option value="release">Release</option><option value="deployment">Deployment</option><option value="reproduction">Reproduction</option></select></label><label>Source ID<input name="source_id" required/></label><label className="wide">Expected behavior<textarea name="expected" required/></label><label className="wide">Regressed behavior<textarea name="regressed" required/></label><label>Good endpoint<select name="good_kind"><option value="revision">Revision</option><option value="release">Release</option></select><input name="good" required placeholder="branch, commit, or release ID"/></label><label>Bad endpoint<select name="bad_kind"><option value="revision">Revision</option><option value="release">Release</option></select><input name="bad" defaultValue={revision} required/></label><label>Severity<select name="severity"><option>medium</option><option>low</option><option>high</option><option>critical</option></select></label><label>Environments<textarea name="environments" placeholder="One per line" required/></label><label>Owners<textarea name="owners" placeholder="Stable user IDs, one per line" required/></label><label>Acceptance criteria<textarea name="criteria" placeholder="One per line" required/></label><label className="wide">Why the endpoints are comparable<textarea name="comparability" required/></label><Button type="submit">Open boundary</Button></form>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="regression-grid"><nav>{items.map(x=><button type="button" className={active?.id===x.id?"active":""} key={x.id} onClick={async()=>{const r=await fetch(`/api/repositories/${repository}/regression-investigations/${x.id}`);if(r.ok)setActive(await r.json())}}><strong>{x.title}</strong><small>{x.status} · v{x.version}</small></button>)}</nav>
  {active&&<article><header><div><h3>{active.title}</h3><small>{active.source.kind.replaceAll("_"," ")} · <code>{active.source.resource_id}</code></small></div><Badge>{active.status}</Badge></header>{(active.blockers.length>0||active.stale_inputs.length>0)&&<div className="regression-blockers"><strong>Boundary needs attention</strong>{[...active.blockers,...active.stale_inputs].map(x=><span key={x}>{x.replaceAll("_"," ")}</span>)}</div>}<dl><div><dt>Expected</dt><dd>{active.scope.expected_behavior}</dd></div><div><dt>Regressed</dt><dd>{active.scope.regressed_behavior}</dd></div><div><dt>Search range</dt><dd><code>{active.scope.known_good.commit_id?.slice(0,12)}</code> → <code>{active.scope.known_bad.commit_id?.slice(0,12)}</code></dd></div><div><dt>Comparable because</dt><dd>{active.scope.comparability}</dd></div><div><dt>Environment / severity</dt><dd>{active.scope.environments.join(", ")} · {active.scope.severity}</dd></div><div><dt>Owners / acceptance</dt><dd>{active.scope.owner_ids.join(", ")} · {active.scope.acceptance_criteria.join("; ")}</dd></div></dl>
   <form className="regression-entry" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send(`/${active.id}/entries`,"POST",{kind:f.get("kind"),body:f.get("body")});e.currentTarget.reset()}}><select name="kind"><option value="discussion">Discussion</option><option value="hypothesis">Hypothesis</option><option value="scope_note">Scope note</option></select><textarea name="body" required placeholder="Add attributable context or a causal hypothesis"/><Button type="submit" variant="secondary">Add</Button></form><ol>{active.entries.map(x=><li key={x.id}><Badge>{x.kind.replaceAll("_"," ")}</Badge><p>{x.body}</p><small>#{x.sequence} · {x.actor_id}</small></li>)}</ol>
   <details className="regression-actions"><summary>Attach evidence or change status</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send(`/${active.id}/evidence`,"POST",{kind:f.get("kind"),resource_id:f.get("resource"),summary:f.get("summary"),audience:f.get("audience")});e.currentTarget.reset()}}><select name="kind"><option value="issue">Issue</option><option value="support_thread">Support thread</option><option value="failed_check">Failed check</option><option value="release">Release</option><option value="deployment">Deployment</option><option value="reproduction">Reproduction</option></select><input name="resource" required placeholder="Readable resource ID"/><input name="summary" required placeholder="Sanitized evidence summary"/><select name="audience"><option value="repository">Repository</option><option value="public">Public</option></select><Button type="submit" variant="secondary">Attach evidence</Button></form><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send(`/${active.id}/status`,"POST",{status:f.get("status"),reason:f.get("reason")})}}><select name="status" defaultValue={active.status}><option value="open">Open</option><option value="ready">Ready to search</option><option value="paused">Paused</option><option value="closed">Closed</option></select><input name="reason" required placeholder="Attributable status rationale"/><Button type="submit" variant="secondary">Change status</Button></form>{active.evidence.map(x=><p key={x.id}><Badge>{x.kind.replaceAll("_"," ")}</Badge> {x.summary} · <code>{x.resource_id}</code> · {x.actor_id}</p>)}</details>
  </article>}</div>
 </section>
}
