/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Plan = {
  id: string; title: string; summary: string; creator_id: string; deadline: string;
  sources: { repository_id: string; revision: string; owner_ids: string[]; role: string }[];
  destinations: { id: string; name: string; owner_ids: string[]; visibility: string; default_branch: string; retained_identities: string[] }[];
  mappings: { id: string; source_paths: string[]; destination_id?: string; destination_paths: string[]; history_mode: string; disposition: string; rationale: string }[];
  inventory: { id: string; kind: string; reference: string; revision: string; owner_ids: string[]; access: string; disposition: string; destination_ids: string[]; reason?: string }[];
  success_criteria: string[]; rollback_limits: { latest_time: string; irreversible_after: string; maximum_data_loss: string; required_retentions: string[] };
  blockers: { kind: string; resource_id: string; detail: string }[];
  findings: { id: string; actor_id: string; actor_kind: string; summary: string; impact: string; uncertainty?: string; citations: { reference: string; revision: string }[] }[];
  candidates: { id:string; created_by:string; assembly_cost:number; required_decisions:string[]; repositories:{destination_id:string;object_digest:string;default_ref:string;default_commit:string;object_count:number;size_bytes:number;evidence:{kind:string;reference:string;status:string;detail:string}[]}[]; cross_repository_links:{kind:string;reference:string;status:string;detail:string}[]; issues:{kind:string;reference:string;status:string;detail:string}[] }[];
  rehearsals: { id:string;candidate_id:string;environment:string;status:string;observed_cost:number;budget:number;required_decisions:string[];checks:{domain:string;status:string;summary:string;cost:number}[];blockers:{kind:string;resource_id:string;detail:string}[] }[];
  work_mappings: {id:string;inventory_item_id:string;kind:string;source_revision:string;authorship:string[];discussion:string[];dependencies:string[];acceptance_criteria:string[];context_audience:string;version:number;status:string;destinations:{destination_id:string;kind:string;reference:string;revision:string;contribution_id?:string;depends_on:string[]}[];decisions:{actor_id:string;decision:string;reason:string}[];outcomes:{destination_id:string;actor_id:string;status:string;reference?:string;revision?:string;reason:string}[];blockers:{kind:string;resource_id:string;detail:string}[]}[];
  migration_plans: {id:string;revision:string;candidate_id:string;targets:{id:string;kind:string;owner_ids:string[];audience:string;current_location:string;replacement_location:string;replacement_remote?:string;redirect_signature?:string;mappings:Record<string,string>;synchronization:string[];compatibility_until:string;state:string;next_action:string}[];events:{id:string;target_id:string;actor_id:string;state:string;revision?:string;pull_request_reference?:string;release_reference?:string;next_action:string}[];blockers:{kind:string;resource_id:string;detail:string}[]}[];
  cutovers: {id:string;candidate_id:string;rehearsal_id:string;migration_plan_id:string;version:number;state:string;active_stage_id?:string;write_boundary:string;source_disposition:string;required_owner_ids:string[];stages:{id:string;kind:string;owner_ids:string[];depends_on:string[];atomic_group?:string;state:string;summary?:string;evidence:string[]}[];approvals:{actor_id:string;decision:string;reason:string}[];signals:{id:string;kind:string;resource_id:string;status:string;value?:number;summary:string;actor_id:string}[];controls:{actor_id:string;kind:string;reason:string}[];blockers:{kind:string;resource_id:string;detail:string}[];rollback_options:string[]}[];
};
const csv=(v:string|undefined)=>(v||"").split(",").map(x=>x.trim()).filter(Boolean);
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean).map(x=>x.split("|").map(y=>y.trim()));

export function RepositoryRestructuring({repository,revision}:{repository:string;revision:string}) {
  const root=`/api/repositories/${repository}/restructuring-plans`,[items,setItems]=useState<Plan[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems(((await r.json()) as {items:Plan[]}).items)},[root]);
  useEffect(()=>{void load()},[load]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);
    const sources=lines(f.get("sources")).map(x=>({repository_id:x[0],revision:x[1],owner_ids:csv(x[2]),role:x[3]}));
    const destinations=lines(f.get("destinations")).map(x=>({id:x[0],name:x[1],owner_ids:csv(x[2]),visibility:x[3],default_branch:x[4],retained_identities:csv(x[5])}));
    const mappings=lines(f.get("mappings")).map(x=>({id:x[0],source_repository_id:x[1],source_revision:x[2],source_paths:csv(x[3]),destination_id:x[4],destination_paths:csv(x[5]),history_mode:x[6],disposition:x[7],rationale:x[8]}));
    const inventory=lines(f.get("inventory")).map(x=>({id:x[0],kind:x[1],repository_id:x[2],reference:x[3],revision:x[4],owner_ids:csv(x[5]),access:x[6],disposition:x[7],destination_ids:csv(x[8]),shared_with:csv(x[9]),reason:x[10]}));
    const body={title:f.get("title"),summary:f.get("summary"),sources,destinations,mappings,inventory,deadline:new Date(String(f.get("deadline"))).toISOString(),success_criteria:lines(f.get("criteria")).flat(),rollback_limits:{latest_time:new Date(String(f.get("rollback_time"))).toISOString(),irreversible_after:f.get("irreversible"),maximum_data_loss:f.get("data_loss"),required_retentions:lines(f.get("retentions")).flat()}};
    const r=await fetch(root,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}e.currentTarget.reset();await load();}
  async function finding(e:FormEvent<HTMLFormElement>,plan:string){e.preventDefault();const f=new FormData(e.currentTarget),citation=String(f.get("citation")).split("|").map(x=>x.trim());const r=await fetch(`${root}/${plan}/findings`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actor_kind:f.get("actor_kind"),summary:f.get("finding_summary"),impact:f.get("impact"),affected_item_ids:csv(String(f.get("items"))),uncertainty:f.get("uncertainty"),citations:[{repository_id:citation[0],reference:citation[1],revision:citation[2],path:citation[3]}]})});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}e.currentTarget.reset();await load()}
  async function append(plan:string,kind:"candidates"|"rehearsals",form:HTMLFormElement){setError("");const f=new FormData(form);try{const body=JSON.parse(String(f.get("body")));const r=await fetch(`${root}/${plan}/${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}form.reset();await load()}catch{setError("invalid_json")}}
  async function workAction(plan:string,path:string,form:HTMLFormElement){setError("");try{const body=JSON.parse(String(new FormData(form).get("body")));const r=await fetch(`${root}/${plan}/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}form.reset();await load()}catch{setError("invalid_json")}}
  return <section className="workspace-stack">
    <header className="workspace-heading"><div><span className="eyebrow">Project boundaries</span><h2>Repository restructuring</h2><p>Review exact moves, retained identities, affected collaboration, ownership, and rollback limits before repository authority changes.</p></div><Badge tone="accent">{items.length} plans</Badge></header>
    <form className="panel form-stack" onSubmit={submit}><h3>Open a restructuring plan</h3>
      <label>Title<input name="title" required /></label><label>Outcome summary<textarea name="summary" required /></label>
      <label>Sources <small>repository | revision | owners comma-separated | role</small><textarea name="sources" required defaultValue={`${repository}|${revision}|owner|primary`} /></label>
      <label>Destinations <small>id | name | owners | public/private/internal | default branch | retained identities</small><textarea name="destinations" required /></label>
      <label>Content and history mappings <small>id | source repository | revision | paths | destination id | destination paths | history mode | move/remain/copy/split/redirect/retire/unresolved | rationale</small><textarea name="mappings" required /></label>
      <label>Affected inventory <small>id | kind | repository | reference | revision | owners | accessible/inaccessible/ambiguous/shared | disposition | destinations | shared with | reason</small><textarea name="inventory" required /></label>
      <div className="form-grid"><label>Deadline<input name="deadline" type="datetime-local" required /></label><label>Rollback until<input name="rollback_time" type="datetime-local" required /></label><label>Irreversible after<input name="irreversible" required /></label><label>Maximum data loss<input name="data_loss" required /></label></div>
      <label>Success criteria <small>one per line</small><textarea name="criteria" required /></label><label>Required retentions <small>one per line</small><textarea name="retentions" required /></label>{error&&<p className="error">{error}</p>}<Button type="submit">Open reviewable plan</Button>
    </form>
    {items.map(p=><article className="panel form-stack" key={p.id}><div className="workspace-heading"><div><h3>{p.title}</h3><p>{p.summary}</p></div><Badge tone={p.blockers.length?"warning":"accent"}>{p.blockers.length} blockers</Badge></div>
      <p><strong>{p.sources.length}</strong> sources → <strong>{p.destinations.length}</strong> destinations · deadline {new Date(p.deadline).toLocaleString()}</p>
      <div className="form-grid">{p.destinations.map(d=><div key={d.id}><strong>{d.name}</strong><p>{d.visibility} · {d.default_branch}</p><small>Owners: {d.owner_ids.join(", ")} · retained: {d.retained_identities.join(", ")||"none"}</small></div>)}</div>
      <h4>What moves and remains</h4>{p.inventory.map(x=><div key={x.id}><Badge tone={x.access==="accessible"?"neutral":"warning"}>{x.access}</Badge> <strong>{x.kind}: {x.reference}</strong> → {x.disposition}{x.destination_ids.length?` (${x.destination_ids.join(", ")})`:""}<small>{x.reason&&` · ${x.reason}`}</small></div>)}
      {p.findings.map(x=><blockquote key={x.id}><strong>{x.actor_kind} · {x.actor_id}</strong>: {x.summary}<br/><small>{x.impact} · cited {x.citations.map(c=>`${c.reference}@${c.revision}`).join(", ")}</small></blockquote>)}
      <h4>Immutable candidate repositories</h4>{p.candidates.map(c=><section className="workspace-card" key={c.id}><p><Badge tone="accent">candidate</Badge> <code>{c.id}</code> · {c.repositories.length} repositories · cost {c.assembly_cost}</p>{c.repositories.map(r=><div key={r.destination_id}><strong>{r.destination_id}</strong> <code>{r.default_ref}@{r.default_commit}</code> · {r.object_count} objects / {r.size_bytes} bytes<ul>{r.evidence.map((e,i)=><li key={i}><Badge tone={e.status==="preserved"||e.status==="not_applicable"?"neutral":"warning"}>{e.status}</Badge> {e.kind}: {e.reference} — {e.detail}</li>)}</ul></div>)}{[...c.cross_repository_links,...c.issues].map((e,i)=><p key={i}><Badge tone={e.status==="preserved"?"neutral":"warning"}>{e.status}</Badge> {e.kind}: {e.detail}</p>)}{c.required_decisions.length>0&&<p><strong>Decisions:</strong> {c.required_decisions.join(" · ")}</p>}</section>)}
      <details><summary>Assemble candidate evidence</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();void append(p.id,"candidates",e.currentTarget)}}><label>Candidate JSON <small>mapping IDs, repository object graphs, preservation evidence, links, issues, costs, and decisions</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Freeze candidate</Button></form></details>
      <h4>Bounded usability rehearsals</h4>{p.rehearsals.map(r=><section className="workspace-card" key={r.id}><p><Badge tone={r.status==="passed"?"accent":"warning"}>{r.status}</Badge> candidate <code>{r.candidate_id}</code> · {r.environment} · cost {r.observed_cost}/{r.budget}</p><div className="form-grid">{r.checks.map(c=><div key={c.domain}><Badge tone={c.status==="passed"?"neutral":"warning"}>{c.status}</Badge> <strong>{c.domain.replaceAll("_"," ")}</strong><small><br/>{c.summary} · cost {c.cost}</small></div>)}</div>{r.blockers.map((b,i)=><p key={i}><Badge tone="warning">{b.kind}</Badge> {b.resource_id}: {b.detail}</p>)}{r.required_decisions.length>0&&<p><strong>Required decisions:</strong> {r.required_decisions.join(" · ")}</p>}</section>)}
      <details><summary>Record a bounded rehearsal</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();void append(p.id,"rehearsals",e.currentTarget)}}><label>Rehearsal JSON <small>candidate, environment, budget, all ten Git/build/resolution/journey domains, issues, costs, and decisions</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Record rehearsal</Button></form></details>
      <h4>Work carried across boundaries</h4>{p.work_mappings.map(m=><section className="workspace-card" key={m.id}><p><Badge tone={m.status==="continued"||m.status==="approved"?"accent":m.status==="proposed"?"neutral":"warning"}>{m.status}</Badge> <strong>{m.kind} {m.inventory_item_id}</strong> · source <code>{m.source_revision}</code> · revision {m.version}</p><p><strong>Authorship:</strong> {m.authorship.join(", ")} · <strong>context:</strong> {m.context_audience}</p><p><strong>Acceptance:</strong> {m.acceptance_criteria.join(" · ")} · <strong>dependencies:</strong> {m.dependencies.join(", ")||"none"}</p>{m.destinations.map(d=><p key={d.destination_id}><strong>{d.destination_id}</strong> → {d.kind} <code>{d.reference}@{d.revision}</code>{d.contribution_id&&` · connected contribution ${d.contribution_id}`}{d.depends_on.length?` · after ${d.depends_on.join(", ")}`:""}</p>)}{m.decisions.map((d,i)=><blockquote key={i}>{d.actor_id} <strong>{d.decision}</strong>: {d.reason}</blockquote>)}{m.outcomes.map((o,i)=><p key={i}><Badge tone={o.status==="continued"?"accent":"warning"}>{o.status}</Badge> {o.destination_id} by {o.actor_id}: {o.reason}</p>)}{m.blockers.map((b,i)=><p key={i}><Badge tone="warning">{b.kind}</Badge> {b.detail}</p>)}<details><summary>Owner decision or destination outcome</summary><form onSubmit={e=>{e.preventDefault();void workAction(p.id,`work-mappings/${m.id}/${String(new FormData(e.currentTarget).get("action"))}`,e.currentTarget)}}><label>Action<select name="action"><option value="decisions">Decision</option><option value="outcomes">Outcome</option></select></label><label>JSON <small>include expected_version {m.version}; only the independent work or destination owner can act</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Record attributable action</Button></form></details></section>)}
      <details><summary>Propose an exact live-work mapping</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();void workAction(p.id,"work-mappings",e.currentTarget)}}><label>Mapping JSON <small>inventory item, exact revision, authorship, discussion, reviews, dependencies, acceptance criteria, audience, and connected destination contributions</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Propose mapping</Button></form></details>
      <h4>Downstream location migration</h4>{p.migration_plans.map(m=><section className="workspace-card" key={m.id}><p><Badge tone={m.blockers.length?"warning":"accent"}>{m.blockers.length?`${m.blockers.length} blockers`:"clear"}</Badge> candidate <code>{m.candidate_id}</code> at <code>{m.revision}</code></p>{m.targets.map(t=><div key={t.id}><p><Badge tone={t.state==="adopted"||t.state==="redirect_ready"?"accent":t.state==="planned"||t.state==="propagating"?"neutral":"warning"}>{t.state}</Badge> <strong>{t.kind} · {t.id}</strong> · owners {t.owner_ids.join(", ")} · {t.audience}</p><p><code>{t.current_location}</code> → <code>{t.replacement_location}</code>{t.replacement_remote&&<> · remote <code>{t.replacement_remote}</code></>}</p><small>Compatibility through {new Date(t.compatibility_until).toLocaleString()} · next: {t.next_action}<br/>Mappings: {Object.entries(t.mappings).map(([a,b])=>`${a} → ${b}`).join("; ")} · sync: {t.synchronization.join("; ")}</small>{m.events.filter(e=>e.target_id===t.id).map(e=><blockquote key={e.id}>{e.actor_id} marked <strong>{e.state}</strong>{e.revision&&<> at <code>{e.revision}</code></>}: {e.next_action}</blockquote>)}</div>)}{m.blockers.map((b,i)=><p key={i}><Badge tone="warning">{b.kind}</Badge> {b.resource_id}: {b.detail}</p>)}<details><summary>Record an owner propagation outcome</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();void workAction(p.id,`migration-plans/${m.id}/events`,e.currentTarget)}}><label>Event JSON <small>target, state, exact revision, ordinary pull request or release, evidence, and next action</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Record owner outcome</Button></form></details></section>)}
      <details><summary>Plan downstream migration</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();void workAction(p.id,"migration-plans",e.currentTarget)}}><label>Migration JSON <small>candidate, revision, and every clone, fork, package, API, dependency, extension, workflow, documentation link, deployment, and follower with owner, mapping, compatibility, safe synchronization, state, and next action</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Freeze migration plan</Button></form></details>
      <h4>Authority cutover and topology health</h4>{p.cutovers.map(c=><section className="workspace-card" key={c.id}><p><Badge tone={c.state==="completed"||c.state==="ready"?"accent":c.state==="running"?"neutral":"warning"}>{c.state.replaceAll("_"," ")}</Badge> <code>{c.id}</code> · revision {c.version}{c.active_stage_id&&<> · active <code>{c.active_stage_id}</code></>}</p><p><strong>Write boundary:</strong> {c.write_boundary} · <strong>source policy:</strong> {c.source_disposition} · <strong>owners:</strong> {c.required_owner_ids.join(", ")}</p><div className="form-grid">{c.stages.map(s=><div key={s.id}><Badge tone={s.state==="succeeded"?"accent":s.state==="failed"?"warning":"neutral"}>{s.state}</Badge> <strong>{s.kind.replaceAll("_"," ")}</strong><small><br/>owner {s.owner_ids.join(", ")}{s.atomic_group&&` · atomic ${s.atomic_group}`}{s.depends_on.length?` · after ${s.depends_on.join(", ")}`:""}{s.summary&&` · ${s.summary}`}</small></div>)}</div><p><strong>Approvals:</strong> {c.approvals.map(a=>`${a.actor_id}: ${a.decision}`).join(" · ")||"pending"}</p>{c.signals.map(s=><p key={s.id}><Badge tone={s.status==="passed"||s.status==="healthy"?"accent":"warning"}>{s.status}</Badge> <strong>{s.kind.replaceAll("_"," ")}</strong> · {s.resource_id}{s.value!==undefined&&` · ${s.value}`}: {s.summary}</p>)}{c.blockers.map((b,i)=><p key={i}><Badge tone="warning">{b.kind.replaceAll("_"," ")}</Badge> {b.resource_id}: {b.detail}</p>)}<p><strong>Rollback:</strong> {c.rollback_options.join(" · ")}</p><details><summary>Owner approval, control, stage, or health signal</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),path=String(f.get("path")).replace("{stage}",String(f.get("stage")));void workAction(p.id,`cutovers/${c.id}/${path}`,e.currentTarget)}}><label>Action<select name="path"><option value="approvals">Approval</option><option value="controls">Start, pause, resume, or rollback</option><option value="stages/{stage}">Stage update</option><option value="signals">Health or verification signal</option></select></label><label>Stage ID (for stage updates)<input name="stage" /></label><label>JSON <small>include expected_version {c.version}; named owners retain their native authority</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Record cutover action</Button></form></details></section>)}
      <details><summary>Prepare a controlled authority cutover</summary><form className="form-stack" onSubmit={e=>{e.preventDefault();void workAction(p.id,"cutovers",e.currentTarget)}}><label>Cutover JSON <small>exact candidate, passing rehearsal, downstream plan, source revisions, required owners, write boundary, source disposition, and dependency-ordered pause/activate/policy/atomic refs/verify/retire stages</small><textarea name="body" required /></label><Button type="submit" variant="secondary">Prepare owner-gated cutover</Button></form></details>
      <form className="form-stack" onSubmit={e=>finding(e,p.id)}><h4>Add a cited impact finding</h4><div className="form-grid"><label>Actor kind<select name="actor_kind"><option value="human">Human</option><option value="read_only_agent">Read-only agent</option></select></label><label>Affected inventory IDs<input name="items" required /></label></div><label>Summary<input name="finding_summary" required /></label><label>Impact<textarea name="impact" required /></label><label>Uncertainty<input name="uncertainty" /></label><label>Citation <small>repository | reference | exact revision | optional path</small><input name="citation" required /></label><Button type="submit" variant="secondary">Add finding</Button></form>
      <small>Rollback until {new Date(p.rollback_limits.latest_time).toLocaleString()}; irreversible after {p.rollback_limits.irreversible_after}. Cutover coordinates only named owners&apos; existing authority and grants none.</small>
    </article>)}
  </section>;
}
