"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Alert={id:string;revision:number;status:string;policy_version:number;team_id?:string;response_deadline?:string;duplicate_count:number;signal:{signal_class:string;severity:string;resource_kind:string;resource_id:string;revision:string;summary:string;affected_user_count:number;uncertainty:string;evidence:{reference:string;accessible:boolean}[]};routing_attempts:{recipient_id?:string;channel:string;status:string;reason?:string}[];gaps:string[];events:{kind:string;detail:string}[];non_authority:string[]};
export function ResponseAlerts({repository,actor}:{repository:string;actor:string}){
 const root=`/api/repositories/${repository}/response-alerts`,[items,setItems]=useState<Alert[]>([]),[mine,setMine]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`${root}${mine?`?recipient=${encodeURIComponent(actor)}`:""}`);if(r.ok)setItems((await r.json() as {items:Alert[]}).items)},[root,mine,actor]);useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
 void load()},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),now=new Date().toISOString(),body={policy_id:f.get("policy"),signal:{signal_class:f.get("class"),severity:f.get("severity"),resource_kind:f.get("kind"),resource_id:f.get("resource"),revision:f.get("revision"),observed_at:now,correlation_key:f.get("correlation"),summary:f.get("summary"),affected_resources:[`${f.get("kind")}:${f.get("resource")}`],affected_user_count:Number(f.get("users")),evidence:[{kind:"repository_signal",reference:String(f.get("evidence")),revision:String(f.get("evidence_revision")),accessible:true}],uncertainty:f.get("uncertainty")},rate_limit_per_hour:Number(f.get("limit"))};const r=await fetch(root,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json())as{error:string}).error);return}setError("");await load()}
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Actionable attention, without silent loss</span><h2>Response alerts</h2><p>Revision-bound signals are evaluated against current coverage, correlated, and routed to current duty with delivery gaps retained.</p></div><div><Button onClick={()=>setMine(!mine)}>{mine?"Show repository alerts":"Show my inbox"}</Button> <Badge>{items.length} alerts</Badge></div></div><details className="investigation-create panel"><summary>Publish a repository signal</summary><form onSubmit={create}><label>Active policy ID<input name="policy" required/></label><label>Signal class<select name="class">{["reliability","deployment","security","privacy","dependency","workflow","user_impact"].map(x=><option key={x}>{x}</option>)}</select></label><label>Severity<select name="severity">{["critical","high","medium","low"].map(x=><option key={x}>{x}</option>)}</select></label><label>Resource kind<input name="kind" defaultValue="service" required/></label><label>Resource ID<input name="resource" required/></label><label>Signal revision<input name="revision" required/></label><label>Correlation key<input name="correlation" required/></label><label>Summary<input name="summary" required/></label><label>Affected users<input name="users" type="number" min="0" defaultValue="0"/></label><label>Evidence reference<input name="evidence" required/></label><label>Evidence revision<input name="evidence_revision" required/></label><label>Uncertainty<input name="uncertainty"/></label><label>Pages per team per hour<input name="limit" type="number" min="0" defaultValue="10"/></label><Button type="submit">Evaluate and route signal</Button></form></details>{error&&<p className="form-error">{error.replaceAll("_"," ")}</p>}{items.map(a=><article className="investigation-canvas panel" key={a.id}><header><div><h3>{a.signal.summary}</h3><p>{a.signal.signal_class} · {a.signal.resource_kind}:{a.signal.resource_id} @ {a.signal.revision}</p></div><Badge>{a.signal.severity} · {a.status.replaceAll("_"," ")}</Badge></header><p>{a.signal.affected_user_count} affected users · policy v{a.policy_version}{a.team_id?` · ${a.team_id}`:""}{a.response_deadline?` · respond by ${new Date(a.response_deadline).toLocaleString()}`:""}</p>{a.signal.uncertainty&&<p><strong>Uncertainty:</strong> {a.signal.uncertainty}</p>}<p>Evidence: {a.signal.evidence.map(e=>`${e.reference}${e.accessible?"":" (inaccessible)"}`).join(" · ")}</p>{a.duplicate_count>0&&<p>{a.duplicate_count} related events deduplicated</p>}{a.routing_attempts.map((x,i)=><p key={i}><strong>{x.channel} → {x.recipient_id||"unassigned"}:</strong> {x.status}{x.reason?` — ${x.reason}`:""}</p>)}{a.gaps.map((g,i)=><p className="form-error" key={i}>{g}</p>)}<small>{a.non_authority.join(" ")}</small></article>)}</section>
}
