"use client";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type QueueItem={id:string;area_id:string;kind:string;reference:string;revision:string;question?:string;accessible:boolean;depends_on?:string[]};
type Progress={assignment_id:string;actor_id:string;state:string;queue_item_ids:string[];coverage:string[];uncertainty:string[]};
type Finding={id:string;area_id:string;assignment_id:string;actor_id:string;actor_kind:string;summary:string;severity:string;conclusion:string;citations:{kind:string;reference:string;revision:string;summary:string;audience:string}[];uncertainty:string[];status:string};
type Message={id:string;area_id:string;actor_id:string;kind:string;body:string;finding_ids:string[]};
type Handoff={id:string;area_id:string;from_assignment_id:string;to_assignment_id:string;reason:string;queue_item_ids:string[];finding_ids:string[];residual_uncertainty:string[];state:string};
type Work={version:number;revision:string;queue:QueueItem[];progress:Progress[];findings:Finding[];discussion:Message[];handoffs:Handoff[];coverage:Record<string,string[]>;conflicts:string[];blockers:string[];authority_notice:string};
type Assignment={id:string;area_id:string;participant_id:string;kind:string;state:string};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);

export function ReviewWork({repository,pull,actor,assignments}:{repository:string;pull:string;actor:string;assignments:Assignment[]}){
 const [work,setWork]=useState<Work>();const [error,setError]=useState("");const base=`/api/repositories/${repository}/pull-requests/${pull}/review-work`;
 const load=useCallback(()=>fetch(base).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b}).then(setWork).catch(e=>setError(e.message)),[base]);useEffect(()=>{void load()},[load]);
 const mine=assignments.filter(a=>a.participant_id===actor&&a.state==="accepted");
 const post=async(path:string,body:Record<string,unknown>)=>{setError("");const r=await fetch(base+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:work?.version,...body})});const b=await r.json();if(!r.ok){setError(b.error);return}setWork(b)};
 if(!work)return <section className="panel"><h4>Shared review work</h4><p>{error?error.replaceAll("_"," "):"Loading exact review queue…"}</p></section>;
 return <section className="panel"><div className="section-heading"><div><h4>Shared review work</h4><p>Reviewers publish revision-bound coverage, citations, uncertainty, questions, challenges, and handoffs where the whole pull-request team can inspect them.</p></div><Badge>{work.progress.length} active · {work.findings.length} findings</Badge></div>
 <p><small>{work.authority_notice}</small></p>{error&&<p role="alert" className="form-error">{error.replaceAll("_"," ")}</p>}
 {[...work.blockers,...work.conflicts].map(x=><p className="proposal-notice" key={x}>{x}</p>)}
 <h5>Scoped exact-revision queue</h5><ol className="investigation-entries">{work.queue.map(q=><li key={q.id}><header><div><strong>{q.area_id} · {q.kind}</strong><small><code>{q.id}</code> · <code>{q.revision.slice(0,12)}</code></small></div><Badge>{q.accessible?(work.coverage[q.id]?.length?"covered":"open"):"inaccessible"}</Badge></header><p>{q.question||q.reference}</p>{q.depends_on?.length?<p>Depends on {q.depends_on.join(", ")}</p>:null}</li>)}</ol>
 {mine.length>0&&<details><summary>Publish progress or finding</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post("/progress",{assignment_id:f.get("assignment"),state:f.get("state"),queue_item_ids:lines(f.get("items")),coverage:lines(f.get("coverage")),uncertainty:lines(f.get("uncertainty"))})}}><label>Accepted assignment<select name="assignment">{mine.map(a=><option key={a.id} value={a.id}>{a.area_id} · {a.kind}</option>)}</select></label><label>State<select name="state"><option>investigating</option><option>blocked</option><option>ready_for_handoff</option><option>complete</option></select></label><label>Exact queue item IDs<textarea name="items" required/></label><label>Files, symbols, or requirements covered<textarea name="coverage" required/></label><label>Uncertainty<textarea name="uncertainty"/></label><Button>Publish shared progress</Button></form>
 <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const citation=String(f.get("citation")||"").split(" | ");void post("/findings",{assignment_id:f.get("assignment"),summary:f.get("summary"),severity:f.get("severity"),conclusion:f.get("conclusion"),citations:[{kind:citation[0],reference:citation[1],revision:work.revision,summary:citation[2],accessible:true,audience:citation[3]||"repository"}],uncertainty:lines(f.get("uncertainty"))})}}><label>Accepted assignment<select name="assignment">{mine.map(a=><option key={a.id} value={a.id}>{a.area_id} · {a.kind}</option>)}</select></label><label>Finding<textarea name="summary" required/></label><label>Severity<select name="severity"><option>info</option><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Conclusion<select name="conclusion"><option>concern</option><option>no_issue</option><option>uncertain</option></select></label><label>Citation: kind | reference | summary | repository/public<input name="citation" required/></label><label>What remains uncertain<textarea name="uncertainty"/></label><Button>Publish cited finding</Button></form></details>}
 <h5>Progress and coverage</h5>{work.progress.map(p=><p key={p.assignment_id}><Badge>{p.state.replaceAll("_"," ")}</Badge> <strong>{p.actor_id}</strong> · {p.queue_item_ids.join(", ")} · {p.coverage.join("; ")}{p.uncertainty.length>0&&<> · uncertain: {p.uncertainty.join("; ")}</>}</p>)}
 <h5>Cited findings and uncertainty</h5>{work.findings.map(f=><article className="proposal-notice" key={f.id}><p><Badge>{f.severity}</Badge> <Badge>{f.status.replaceAll("_"," ")}</Badge> <strong>{f.summary}</strong> — {f.actor_id}</p><p>{f.citations.map(c=>`${c.kind} ${c.reference}@${c.revision.slice(0,12)}: ${c.summary}`).join(" · ")}</p>{f.uncertainty.length>0&&<p>Uncertainty: {f.uncertainty.join(" · ")}</p>}</article>)}
 <h5>Public discussion, input, and handoffs</h5>{work.discussion.map(m=><p key={m.id}><Badge>{m.kind.replaceAll("_"," ")}</Badge> <strong>{m.actor_id}</strong>: {m.body}</p>)}{work.handoffs.map(h=><div className="proposal-notice" key={h.id}><p><Badge>{h.state}</Badge> {h.from_assignment_id} → {h.to_assignment_id}: {h.reason} · queue {h.queue_item_ids.join(", ")} · uncertainty {h.residual_uncertainty.join("; ")||"none"}</p>{h.state==="requested"&&mine.some(a=>a.id===h.to_assignment_id)&&<Button onClick={()=>void post(`/handoffs/${h.id}/acceptance`,{})}>Accept exact handoff</Button>}</div>)}
 {mine.length>0&&<details><summary>Request input, challenge, or hand off</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const a=mine.find(x=>x.id===f.get("assignment"));void post("/messages",{assignment_id:f.get("assignment"),area_id:a?.area_id,kind:f.get("kind"),body:f.get("body"),finding_ids:lines(f.get("findings")),citations:[]})}}><label>Assignment<select name="assignment">{mine.map(a=><option key={a.id} value={a.id}>{a.area_id} · {a.id}</option>)}</select></label><label>Message kind<select name="kind"><option>discussion</option><option>input_request</option><option>answer</option><option>challenge</option></select></label><label>Public reasoning<textarea name="body" required/></label><label>Finding IDs<textarea name="findings"/></label><Button>Publish to review</Button></form><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post("/handoffs",{from_assignment_id:f.get("from"),to_assignment_id:f.get("to"),reason:f.get("reason"),queue_item_ids:lines(f.get("items")),finding_ids:lines(f.get("findings")),residual_uncertainty:lines(f.get("uncertainty"))})}}><label>From assignment<select name="from">{mine.map(a=><option key={a.id} value={a.id}>{a.id}</option>)}</select></label><label>To accepted assignment<select name="to">{assignments.filter(a=>a.state==="accepted").map(a=><option key={a.id} value={a.id}>{a.participant_id} · {a.area_id}</option>)}</select></label><label>Why hand off<textarea name="reason" required/></label><label>Queue item IDs<textarea name="items" required/></label><label>Finding IDs<textarea name="findings"/></label><label>Residual uncertainty<textarea name="uncertainty"/></label><Button>Request attributable handoff</Button></form></details>}
 </section>
}
