"use client";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Assignment={id:string;area_id:string;participant_id:string;kind:string;state:string};
type Ack={actor_id:string;decision:string;rationale:string};
type Override={actor_id:string;reason:string;follow_up:string;expires_at:string};
type Area={id:string;name:string;required:boolean;owners:string[];assignments:string[];evidence_inspected:string[];finding_ids:string[];decisions:string[];required_acknowledgements:string[];acknowledged_by:string[];unresolved_gaps:string[];stale_approvals:Ack[];complete:boolean;override?:Override};
type Completion={version:number;ready:boolean;revision:string;areas:Area[];blockers:string[];authority_notice:string};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);
export function ReviewCompletion({repository,pull,actor,assignments}:{repository:string;pull:string;actor:string;assignments:Assignment[]}){
 const [value,setValue]=useState<Completion>();const [error,setError]=useState("");const base=`/api/repositories/${repository}/pull-requests/${pull}/review-completion`;
 const load=useCallback(()=>fetch(base).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b}).then(setValue).catch(e=>setError(e.message)),[base]);useEffect(()=>{void load()},[load]);
 const send=async(path:string,method:string,body:Record<string,unknown>)=>{const r=await fetch(base+path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:value?.version,...body})});const b=await r.json();if(!r.ok){setError(b.error);return}setValue(b)};
 if(!value)return <section className="panel"><h4>Review completion</h4><p>{error?error.replaceAll("_"," "):"Loading review matrix…"}</p></section>;
 return <section className="panel"><div className="section-heading"><div><h4>Current review matrix</h4><p>Completion is area-specific and bound to the exact candidate, target, risk, ownership, dependencies, scope, and rules.</p></div><Badge>{value.ready?"review complete":"review incomplete"}</Badge></div>{error&&<p className="form-error">{error.replaceAll("_"," ")}</p>}
 <div className="table-wrap"><table><thead><tr><th>Area / owners</th><th>Evidence</th><th>Findings / decisions</th><th>Acknowledgements</th><th>Gaps</th></tr></thead><tbody>{value.areas.map(a=><tr key={a.id}><td><strong>{a.name}</strong> {a.required&&<Badge>required</Badge>}<br/>{a.owners.join(", ")||"missing"}</td><td>{a.evidence_inspected.length?a.evidence_inspected.map(x=><code key={x}>{x} </code>):"none"}</td><td>{a.finding_ids.length} finding(s)<br/>{a.decisions.join(" · ")||"no decisions"}</td><td>{a.acknowledged_by.join(", ")||"missing"}{a.stale_approvals.length>0&&<p className="form-error">{a.stale_approvals.length} stale approval(s)</p>}</td><td>{a.complete?<Badge>complete</Badge>:a.unresolved_gaps.map(x=><p key={x}>{x.replaceAll("_"," ")}</p>)}{a.override&&<p><Badge>emergency override</Badge> {a.override.reason} · follow-up {a.override.follow_up}</p>}</td></tr>)}</tbody></table></div>
 {actor&&<details><summary>Set requirements or emergency override</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send("/requirements","PUT",{area_ids:lines(f.get("areas"))})}}><label>Required review area IDs<textarea name="areas" required defaultValue={value.areas.filter(a=>a.required).map(a=>a.id).join("\n")}/></label><Button>Require selected areas</Button></form><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send("/overrides","POST",{area_ids:lines(f.get("areas")),reason:f.get("reason"),follow_up:f.get("follow_up"),expires_at:f.get("expires_at")})}}><label>Scoped area IDs<textarea name="areas" required/></label><label>Emergency reason<textarea name="reason" required/></label><label>Follow-up work reference<input name="follow_up" required/></label><label>Expires at (within seven days)<input name="expires_at" type="datetime-local" required/></label><Button>Record bounded override</Button></form></details>}
 {assignments.filter(a=>a.participant_id===actor&&a.kind==="human"&&a.state==="accepted").map(a=><form key={a.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send(`/areas/${a.area_id}/acknowledgements`,"POST",{assignment_id:a.id,decision:f.get("decision"),rationale:f.get("rationale")})}}><h5>Acknowledge {a.area_id}</h5><label>Decision<select name="decision"><option value="approve">Complete</option><option value="request_changes">Request changes</option></select></label><label>Evidence-based rationale<textarea name="rationale" required/></label><Button>Record current acknowledgement</Button></form>)}<small>{value.authority_notice}</small></section>
}
