"use client";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";
import { ReviewWork } from "@/components/review-work";

type Blocker={kind:string;subject:string;detail:string;attributed_to?:string};
type Context={kind:string;reference:string;revision?:string;accessible:boolean;owner_ids:string[]};
type Evidence={kind:string;description:string;reference?:string;required:boolean};
type Area={id:string;name:string;expertise:string[];paths:string[];owner_ids:string[];acceptance_questions:string[];required_evidence:Evidence[];depends_on:string[];completion_rules:string[]};
type Version={number:number;revision:string;target_revision:string;changed_paths:string[];intent:string;risk:string;policy_references:string[];commitments:Context[];context:Context[];review_areas:Area[];change_reason:string;author_id:string;created_at:string};
type Plan={current_version:number;versions:Version[];blockers:Blocker[];stale:boolean};
type Suggestion={area_id:string;participant_id:string;kind:string;eligible:boolean;reasons:string[];blockers:string[];evidence:Evidence[]};
type Assignment={id:string;area_id:string;participant_id:string;kind:string;state:string;deadline?:string;escalation?:string;invitation_reason:string;authority_notice:string;outcome_reason?:string};
type Routing={suggestions:Suggestion[];assignments:Assignment[];reassignment_areas:string[]};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);
const contexts=(v:FormDataEntryValue|null)=>lines(v).map(x=>{const [kind,reference,revision,access,owners]=x.split(" | ");return{kind,reference,revision,accessible:access!=="inaccessible",owner_ids:(owners||"").split(",").filter(Boolean)}});

export function ReviewPlans({repository,pull,actor,paths}:{repository:string;pull:string;actor:string;paths:string[]}){
 const [plan,setPlan]=useState<Plan>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const [routing,setRouting]=useState<Routing>({suggestions:[],assignments:[],reassignment_areas:[]});
 const load=useCallback(()=>fetch(`/api/repositories/${repository}/pull-requests/${pull}/review-plans`).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.json() as Promise<Plan>}).then(setPlan).catch(e=>setError(e.message)),[repository,pull]);
 const loadRouting=useCallback(()=>fetch(`/api/repositories/${repository}/pull-requests/${pull}/review-routing`).then(r=>r.json()).then(setRouting),[repository,pull]);
 useEffect(()=>{void load();void loadRouting()},[load,loadRouting]); const current=plan?.versions.at(-1);
 return <section className="investigation-workspace"><header className="panel"><div><p className="eyebrow">Exact change → required expertise → review evidence</p><h3>Review plan</h3><p>Agree on review scope before approvals become a generic signal. Plans preserve their exact code, intent, ownership, policies, commitments, questions, evidence, dependencies, and completion rules.</p></div><Badge>{plan?.stale?"stale":current?`version ${current.number}`:"unplanned"}</Badge></header>
 {error&&<p className="form-error" role="alert">{error.replaceAll("_"," ")}</p>}
 {plan?.blockers.map((b,i)=><p className="proposal-notice panel" key={`${b.kind}-${b.subject}-${i}`}><strong>{b.kind.replaceAll("_"," ")}</strong> · {b.subject} — {b.detail}{b.attributed_to&&<> · {b.attributed_to}</>}</p>)}
 {actor&&<details className="panel" open={!current}><summary>{current?"Publish a revised plan":"Plan this review"}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const area=String(f.get("area")||"").split(" | ");try{const r=await fetch(`/api/repositories/${repository}/pull-requests/${pull}/review-plans`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:plan?.current_version||0,plan:{intent:f.get("intent"),risk:f.get("risk"),change_reason:f.get("reason"),policy_references:lines(f.get("policies")),commitments:contexts(f.get("commitments")),context:contexts(f.get("context")),review_areas:[{id:area[0],name:area[1],expertise:(area[2]||"").split(",").filter(Boolean),owner_ids:lines(f.get("owners")),paths:lines(f.get("paths")),acceptance_questions:lines(f.get("questions")),required_evidence:lines(f.get("evidence")).map(x=>{const [kind,description,reference]=x.split(" | ");return{kind,description,reference,required:true}}),depends_on:lines(f.get("dependencies")),completion_rules:lines(f.get("rules"))}]}})});const body=await r.json();if(!r.ok)throw new Error(body.error);setPlan(body.plan)}catch(x){setError(x instanceof Error?x.message:"Could not publish plan")}finally{setBusy(false)}}}><label>Declared intent<textarea name="intent" required defaultValue={current?.intent}/></label><label>Risk<select name="risk" defaultValue={current?.risk||"medium"}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Why this plan changed<input name="reason" required defaultValue={current?"Refresh review analysis":"Define review before approval"}/></label><label>Policy references, one per line<textarea name="policies" defaultValue={current?.policy_references.join("\n")}/></label><label>Affected commitments: kind | reference | revision | accessible/inaccessible | owner IDs<textarea name="commitments"/></label><label>Other context, same format<textarea name="context"/></label><label>Area: ID | name | expertise tags<input name="area" required placeholder="code | Code behavior | Go,API"/></label><label>Area owners, one ID per line<textarea name="owners"/></label><label>Exact changed paths in this area<textarea name="paths" required defaultValue={paths.join("\n")}/></label><label>Acceptance questions<textarea name="questions" required/></label><label>Evidence: kind | description | reference<textarea name="evidence" required/></label><label>Area dependencies, one area ID per line<textarea name="dependencies"/></label><label>Completion rules<textarea name="rules" required/></label><Button disabled={busy}>{busy?"Publishing…":"Publish immutable plan version"}</Button></form></details>}
 {current&&<article className="panel"><p><Badge>{current.risk} risk</Badge> <code>{current.revision.slice(0,12)}</code> against <code>{current.target_revision.slice(0,12)}</code> · {current.author_id}</p><h3>{current.intent}</h3><p>{current.changed_paths.length} server-derived changed path(s) · {current.policy_references.length} policies · {current.commitments.length} commitments</p>{current.review_areas.map(a=><section className="panel" key={a.id}><h4>{a.name}</h4><p><strong>Expertise:</strong> {a.expertise.join(", ")||"unspecified"} · <strong>Owners:</strong> {a.owner_ids.join(", ")||"missing"}</p><p><strong>Scope:</strong> {a.paths.join(", ")}</p><h5>Acceptance questions</h5><ul>{a.acceptance_questions.map(x=><li key={x}>{x}</li>)}</ul><h5>Required evidence</h5><ul>{a.required_evidence.map((x,i)=><li key={i}><Badge>{x.kind}</Badge> {x.description}{x.reference&&<> · <code>{x.reference}</code></>}</li>)}</ul><p><strong>Complete when:</strong> {a.completion_rules.join(" · ")}</p>{a.depends_on.length>0&&<p><strong>Depends on:</strong> {a.depends_on.join(", ")}</p>}<h5>Accountable review</h5>{routing.reassignment_areas.includes(a.id)&&<p className="form-error">Reassignment required: invite another eligible participant.</p>}{routing.suggestions.filter(x=>x.area_id===a.id).map(s=><p key={s.participant_id}><Badge>{s.eligible?"eligible":"blocked"}</Badge> <strong>{s.participant_id}</strong> ({s.kind}) — {(s.eligible?s.reasons:s.blockers).join(" · ")}</p>)}{routing.assignments.filter(x=>x.area_id===a.id).map(x=><div className="proposal-notice" key={x.id}><p><Badge>{x.state}</Badge> <strong>{x.participant_id}</strong>{x.deadline&&<> · due {new Date(x.deadline).toLocaleString()}</>}{x.escalation&&<> · escalate to {x.escalation}</>}</p><p>{x.invitation_reason}</p><small>{x.authority_notice}</small>{x.outcome_reason&&<p>Outcome: {x.outcome_reason}</p>}</div>)}</section>)}</article>}
 {current&&routing.assignments.some(x=>x.state==="accepted")&&<ReviewWork repository={repository} pull={pull} actor={actor} currentRevision={current.revision} assignments={routing.assignments}/>}
 </section>
}
