"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";

type Runbook={id:string;current_version:number;versions:{name:string}[]};
type Gap={kind:string;detail:string;reference?:string};
type Attempt={id:string;actor_id:string;actor_kind:string;scenario_id:string;classification:string;proof:boolean;stale:boolean;cost:number;currency:string;manual_gaps:string[];gaps:Gap[]};
type Rehearsal={id:string;runbook_id:string;runbook_version:number;title:string;environment_id:string;environment_revision:string;environment_class:string;revision:number;ready:boolean;attempts:Attempt[];gaps:Gap[];non_authority:string[]};
const starter={runbook_version:1,title:"Dependency failure rehearsal",environment_id:"isolated-response-lab",environment_revision:"environment-v1",environment_class:"isolated",limits:{max_duration_seconds:900,max_cost:10,currency:"USD"},scenarios:[{id:"dependency-unavailable",name:"Required dependency is unavailable",failure:"Synthetic connection refusal",evidence_source:"synthetic",input_digest:"sha256:scenario-input",expected_outcomes:["service health restored"],references:[{kind:"service",resource_id:"service-id",revision:"service-v1"},{kind:"dependency",resource_id:"dependency-id",revision:"config-v1"},{kind:"runbook_step",resource_id:"recovery-step",revision:"step-v1"}]}],owner_ids:["responder-id"]};

export function RunbookRehearsals({repository}:{repository:string}){
 const [books,setBooks]=useState<Runbook[]>([]),[items,setItems]=useState<Rehearsal[]>([]),[error,setError]=useState("");
 const load=useCallback(async()=>{const root=`/api/repositories/${repository}/runbooks`;const response=await fetch(root);if(!response.ok)return;const next=(await response.json() as {items:Runbook[]}).items;setBooks(next);const nested=await Promise.all(next.map(async book=>{const r=await fetch(`${root}/${book.id}/rehearsals`);return r.ok?(await r.json() as {items:Rehearsal[]}).items:[]}));setItems(nested.flat())},[repository]);
 useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
  void load()},[load]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),runbook=String(form.get("runbook"));let body:unknown;try{body=JSON.parse(String(form.get("definition")))}catch{setError("Rehearsal definition must be valid JSON");return}const r=await fetch(`/api/repositories/${repository}/runbooks/${runbook}/rehearsals`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error.replaceAll("_"," "));return}setError("");await load()}
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Prove before pressure</span><h2>Runbook rehearsals</h2><p>Exercise an exact procedure in a bounded environment and keep unsafe, incomplete, or stale evidence visible.</p></div><Badge>{items.filter(x=>x.ready).length} ready · {items.length} total</Badge></div>{books.length>0&&<details className="investigation-create panel"><summary>Define a bounded rehearsal</summary><form onSubmit={submit}><label>Selected runbook<select name="runbook">{books.map(x=><option key={x.id} value={x.id}>{x.versions.at(-1)?.name} · version {x.current_version}</option>)}</select></label><label>Scenario definition<textarea name="definition" rows={22} defaultValue={JSON.stringify(starter,null,2)} required/></label><p>Use synthetic or explicitly permitted evidence. Destructive steps must be simulated or excluded; this record grants no environment authority.</p><Button type="submit">Create rehearsal</Button></form></details>}{error&&<p className="form-error">{error}</p>}{items.map(x=><article className="investigation-canvas panel" key={x.id}><header><div><h3>{x.title}</h3><p>Runbook version {x.runbook_version} · {x.environment_class} {x.environment_id} @ {x.environment_revision}</p></div><Badge>{x.ready?"current proof":"proof gaps"}</Badge></header>{x.gaps.map((g,i)=><p className="form-error" key={`${g.kind}-${i}`}><strong>{g.kind.replaceAll("_"," ")}:</strong> {g.detail} {g.reference&&`· ${g.reference}`}</p>)}{x.attempts.map(a=><section key={a.id}><h4>{a.actor_kind} attempt · {a.scenario_id}</h4><p>{a.actor_id} · {a.classification}{a.stale?" · stale":""} · {a.cost} {a.currency}</p>{a.gaps.map((g,i)=><p key={i}><strong>{g.kind.replaceAll("_"," ")}:</strong> {g.detail}</p>)}</section>)}<small>{x.non_authority.join(" ")}</small></article>)}{!items.length&&<p>No runbook rehearsals have been defined.</p>}</section>
}
