"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Finding={kind:string;subject:string;detail:string;attributed_to?:string};
type Preview={step_id:string;inspects:string[];changes:string[];requires_human_judgment:boolean;required_authority:string[];granted:boolean};
type Version={number:number;name:string;purpose:string;scope:{kind:string;resource_id:string;revision:string;owner_id:string};steps:{id:string;kind:string;title:string;purpose:string;expected_evidence:string[];owner_ids:string[];required_skills:string[];rollback_criteria:string[]}[];rollback_criteria:string[];escalation_paths:{condition:string;owner_id:string;action:string}[];change_reason:string;author_id:string};
type Runbook={id:string;current_version:number;versions:Version[];findings:Finding[];authority_preview:Preview[];non_authority:string[]};
const starter={name:"Restore checkout",purpose:"Diagnose user impact and choose safe containment",scope:{kind:"service",resource_id:"checkout",revision:"service-v1",owner_id:"service-owner"},preconditions:[{id:"impact",description:"Confirm current user impact",evidence:"revision-bound dashboard window",owner_id:"responder",safe:true}],steps:[{id:"inspect",kind:"diagnostic",title:"Inspect errors",purpose:"Distinguish dependency failure from release regression",precondition_ids:["impact"],references:[{kind:"command",resource_id:"metrics-query",revision:"reviewed-sha256",detail:"read sanitized errors",accessible:true,reviewed:true,secret_bearing:false,owner_id:"operators"}],expected_evidence:["sanitized error and saturation window"],required_authority:["telemetry:read"],owner_ids:["responder"],required_skills:["diagnosis"],depends_on:[],rollback_criteria:[]},{id:"choose",kind:"decision",title:"Choose containment",purpose:"Place human judgment before an operational change",precondition_ids:["impact"],references:[{kind:"documentation",resource_id:"rollback-policy",revision:"v3",detail:"approved rollback boundary",accessible:true,reviewed:true,secret_bearing:false,owner_id:"release-owner"}],expected_evidence:["attributed decision"],decision:{question:"Is rollback safer than continued operation?",options:["request authorized rollback","escalate"],human_required:true,owner_id:"incident-commander"},required_authority:["deployment:rollback"],owner_ids:["incident-commander"],required_skills:["release"],depends_on:["inspect"],rollback_criteria:["health worsens"]}],rollback_criteria:["service levels worsen after any action"],owner_ids:["service-owner"],required_skills:["diagnosis","release"],escalation_paths:[{condition:"No safe option or required authority is unavailable",owner_id:"incident-commander",required_skills:["incident-command"],audience_ids:["service-owners"],action:"open an ordinary incident"}],policy_references:[{kind:"environment",resource_id:"production-policy",revision:"v1",accessible:true,conflicting:false,owner_id:"platform"}],change_reason:"Publish a reviewable procedure"};

export function Runbooks({repository}:{repository:string}){const root=`/api/repositories/${repository}/runbooks`,[items,setItems]=useState<Runbook[]>([]),[error,setError]=useState("");const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems((await r.json() as {items:Runbook[]}).items)},[root]);useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
void load()},[load]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let body:unknown;try{body=JSON.parse(String(f.get("definition")))}catch{setError("Runbook definition must be valid JSON");return}const r=await fetch(root,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json())as{error:string}).error.replaceAll("_"," "));return}setError("");await load()}
return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Review before an emergency</span><h2>Operational runbooks</h2><p>Publish exact procedures whose purpose, evidence, decisions, rollback boundaries, ownership, skills, escalation, references, and requested authority can be reviewed together.</p></div><Badge>{items.length} runbooks</Badge></div><details className="investigation-create panel"><summary>Author a versioned runbook</summary><form onSubmit={submit}><label>Structured runbook definition<textarea name="definition" rows={24} defaultValue={JSON.stringify(starter,null,2)} required/></label><p>Commands, components, documentation, and agents must name reviewed revisions. Authority is previewed, never granted.</p><Button type="submit">Publish runbook</Button></form></details>{error&&<p className="form-error">{error}</p>}{items.map(r=>{const v=r.versions.at(-1)!;return <article className="investigation-canvas panel" key={r.id}><header><div><h3>{v.name}</h3><p>Version {v.number} by {v.author_id} · {v.change_reason}</p></div><Badge>{r.findings.length?`${r.findings.length} review findings`:"review inputs complete"}</Badge></header><p>{v.purpose}</p><p><strong>{v.scope.kind}:</strong> {v.scope.resource_id} @ {v.scope.revision} · owner {v.scope.owner_id}</p>{r.findings.map((f,i)=><p className="form-error" key={`${f.kind}-${i}`}><strong>{f.kind.replaceAll("_"," ")}:</strong> {f.detail} · accountable to {f.attributed_to||v.author_id}</p>)}{v.steps.map(s=>{const p=r.authority_preview.find(x=>x.step_id===s.id);return <section key={s.id}><h4>{s.kind} · {s.title}</h4><p>{s.purpose}</p><p><strong>Expected evidence:</strong> {s.expected_evidence.join("; ")}</p><p><strong>Authority preview:</strong> {[...(p?.inspects||[]).map(x=>`inspect ${x}`),...(p?.changes||[]).map(x=>`change ${x}`)].join("; ")||"no resource reference"}; requires {p?.required_authority.join(", ")||"no declared capability"}; {p?.requires_human_judgment?"human judgment required":"no decision gate"}; <strong>not granted</strong>.</p></section>})}<p><strong>Whole-procedure rollback:</strong> {v.rollback_criteria.join("; ")}</p>{v.escalation_paths.map((x,i)=><p key={i}><strong>Escalate when {x.condition}:</strong> {x.action} · {x.owner_id}</p>)}<small>{r.non_authority.join(" ")}</small></article>})}{!items.length&&<p>No operational runbooks have been published.</p>}</section>}
