"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";
type Replay={id:string;name:string;behavior:string;revision:string;state_kind:string;status:string;reproduced:boolean;repeated_passing_attempts:number;blockers?:string[];attempts:{id:string;target_kind:string;status:string;cost:number;production_differences:string[];blockers:string[]}[];refinements:{id:string;summary:string;actor_id:string}[]};
const lines=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);
export function RuntimeReplays({repository,workspace,revision,participant,evidence}:{repository:string;workspace:string;revision:string;participant:boolean;evidence:string[]}){
 const root=`/api/repositories/${repository}/debugging-workspaces/${workspace}/replays`,[items,setItems]=useState<Replay[]>([]),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems(((await r.json()) as {items:Replay[]}).items)},[root]);useEffect(()=>{void load()},[load]);
 async function post(path:string,body:unknown){const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError(((await r.json()) as {error:string}).error);return}setError("");await load()}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),source=String(f.get("evidence"));void post(root,{name:f.get("name"),behavior:f.get("behavior"),audience:"participants",evidence_ids:[source],state_kind:f.get("state"),inputs:[{name:"scenario.json",kind:f.get("state")==="synthetic"?"synthetic":"redacted",value:f.get("input"),source_evidence_id:source,transformation:f.get("transformation")}],commands:lines(f.get("commands")),invariants:lines(f.get("invariants")).map(x=>({name:x,expectation:`${x} must hold`})),unsafe_side_effects:lines(f.get("unsafe"))})}
 function attempt(e:FormEvent<HTMLFormElement>,v:Replay){e.preventDefault();const f=new FormData(e.currentTarget),passed=lines(f.get("passed"));void post(`${root}/${v.id}/attempts`,{target_kind:f.get("target_kind"),target_id:f.get("target"),revision:f.get("revision"),environment:{isolation:"credential-free",network:"disabled",state:v.state_kind},commands:lines(f.get("commands")),outputs:lines(f.get("outputs")),traces:lines(f.get("traces")),invariant_results:Object.fromEntries(passed.map(x=>[x,true])),cost:Number(f.get("cost")),production_differences:lines(f.get("differences")),blockers:lines(f.get("blockers"))})}
 return <section className="panel"><header><div><h4>Privacy-safe failure replay</h4><small>Two clean exact-revision observations are required before a scenario is reproduced.</small></div><Badge>{items.length} scenarios</Badge></header>{error&&<p className="form-error">{error.replaceAll("_"," ")}</p>}
 {participant&&evidence.length>0&&<details><summary>Derive a minimized scenario from permitted evidence</summary><form className="stacked-form" onSubmit={create}><input name="name" placeholder="Scenario name" required/><textarea name="behavior" placeholder="Relevant behavior" required/><select name="evidence">{evidence.map(x=><option key={x}>{x}</option>)}</select><select name="state"><option>synthetic</option><option value="privacy_preserving">privacy preserving</option></select><textarea name="input" placeholder="Sanitized input (no protected values)" required/><textarea name="transformation" placeholder="Redaction, aggregation, or synthesis performed" required/><textarea name="commands" placeholder="One bounded command per line" required/><textarea name="invariants" placeholder="One invariant name per line" required/><textarea name="unsafe" placeholder="Unsafe side effects, one per line"/><Button type="submit">Retain safe scenario</Button></form></details>}
 {items.map(v=><article className="panel" key={v.id}><p><Badge>{v.status}</Badge> <strong>{v.name}</strong> · <code>{v.revision.slice(0,12)}</code> · {v.state_kind.replaceAll("_"," ")}</p><p>{v.behavior}</p><p>{v.repeated_passing_attempts} clean matching attempts{v.blockers?.length?` · blockers: ${v.blockers.join(", ")}`:""}</p>{v.attempts.map(a=><p key={a.id}><Badge>{a.status}</Badge> {a.target_kind} · cost {a.cost}{a.production_differences.length?` · differs: ${a.production_differences.join(", ")}`:""}{a.blockers.length?` · ${a.blockers.join(", ")}`:""}</p>)}
 {participant&&<><details><summary>Run in an isolated workspace or preview</summary><form className="stacked-form" onSubmit={e=>attempt(e,v)}><select name="target_kind"><option>workspace</option><option>preview</option></select><input name="target" placeholder="Existing isolated target ID" required/><input name="revision" defaultValue={revision} required/><textarea name="commands" placeholder="Commands executed" required/><textarea name="passed" placeholder="Passing invariant names"/><textarea name="traces" placeholder="Sanitized trace summaries"/><textarea name="outputs" placeholder="Sanitized outputs"/><textarea name="differences" placeholder="Differences from production"/><textarea name="blockers" placeholder="nondeterminism, missing_dependency, irreducible_production_condition"/><input name="cost" type="number" min="0" step="0.01" defaultValue="0"/><Button type="submit">Record isolated attempt</Button></form></details><form className="stacked-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post(`${root}/${v.id}/refinements`,{summary:f.get("summary")})}}><input name="summary" placeholder="Attributable minimization or refinement" required/><Button type="submit">Refine scenario</Button></form></>}</article>)}</section>
}
