"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge, Button } from "@/components/ui";

type Resource={kind:string;repository_id?:string;id?:string;ref?:string;path?:string;label:string};
type Scope={version:number;question:string;constraints:string[];success_measures:string[];deadline?:string;affected_resources:Resource[];participant_ids:string[];owner_id:string;changed_by_id:string;change_summary?:string;created_at:string};
type Evidence={kind:string;repository_id?:string;revision?:string;resource_id?:string;path?:string;url?:string;summary:string;observed_at:string};
type Claim={id:string;kind:string;body:string;author_id:string;supersedes_id?:string;created_at:string};
type Alternative={id:string;title:string;state:string;created_by_id:string;claims:Claim[];evidence:Evidence[];agent_findings:{id:string;agent:string;body:string;uncertainty:string;evidence:Evidence[];created_at:string}[]};
type Comparison={alternative_id:string;current_claims:Record<string,string>;missing_criteria:string[];evidence_count:number;evidence_kinds:string[];stale_evidence_ids:string[];dissent_count:number};
type Decision={id:string;title:string;state:string;context:{kind:string;id?:string};created_by_id:string;updated_at:string;scope:Scope;history:Scope[];comments:{id:string;author_id:string;body:string;created_at:string}[];alternatives:Alternative[];comparison:Comparison[]};
type Repository={id:string;owner_id:string;collaborator_ids?:string[]};

const lines=(value:FormDataEntryValue|null)=>String(value||"").split("\n").map(x=>x.trim()).filter(Boolean);
const participants=(value:FormDataEntryValue|null)=>String(value||"").split(",").map(x=>x.trim()).filter(Boolean);
function scopeBody(f:FormData){const deadline=String(f.get("deadline")||"");const resourceLabel=String(f.get("resource_label")||"").trim();return {question:f.get("question"),constraints:lines(f.get("constraints")),success_measures:lines(f.get("measures")),deadline:deadline?`${deadline}T23:59:59Z`:null,affected_resources:resourceLabel?[{kind:f.get("resource_kind"),repository_id:f.get("resource_repository"),id:f.get("resource_id"),ref:f.get("resource_ref"),path:f.get("resource_path"),label:resourceLabel}]:[],participant_ids:participants(f.get("participants")),owner_id:f.get("owner"),change_summary:f.get("change_summary")}}

export function TechnicalDecisions({repository,actor,selected}:{repository:Repository;actor:string;selected?:string}){
 const router=useRouter(),[items,setItems]=useState<Decision[]>([]),[active,setActive]=useState<Decision>(),[error,setError]=useState(""),[credential,setCredential]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`/api/repositories/${repository.id}/decisions`);if(!r.ok)return;const body=await r.json() as {items:Decision[]};setItems(body.items);const id=selected||body.items[0]?.id;if(id){const detail=await fetch(`/api/repositories/${repository.id}/decisions/${id}`);if(detail.ok)setActive(await detail.json())}},[repository.id,selected]);
 useEffect(()=>{
  // Decision state follows the shareable selection URL.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load()
 },[load]);
 async function mutate(path:string,method:string,body:unknown){setError("");const r=await fetch(`/api/repositories/${repository.id}/decisions${path}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("The decision could not be saved. Confirm that every participant and the owner can contribute to this repository.");return}const v=await r.json() as Decision;setActive(v);setItems(old=>[v,...old.filter(x=>x.id!==v.id)]);return v}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const v=await mutate("","POST",{title:f.get("title"),context:{kind:f.get("context_kind"),id:f.get("context_id")},...scopeBody(f)});if(v)router.push(`/repositories/${repository.id}?view=decisions&decision=${v.id}`)}
 const defaultParticipants=[actor,repository.owner_id].filter((x,i,a)=>x&&a.indexOf(x)===i).join(", ");
 return <section className="investigation-workspace"><div className="section-heading"><div><span className="eyebrow">Before solutions harden</span><h2>Technical decisions</h2><p>Keep the question, boundaries, measures, affected work, and accountable people visible while the choice is pending. Pending decisions inform related work; they do not block unrelated contributions.</p></div><Badge>{items.filter(x=>x.state==="pending").length} pending</Badge></div>
 <details className="investigation-create panel"><summary>Open a technical decision</summary><DecisionForm onSubmit={create} repository={repository.id} participants={defaultParticipants}/></details>{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="investigation-layout"><aside className="investigation-list panel">{items.map(x=><Link className={active?.id===x.id?"active":""} href={`/repositories/${repository.id}?view=decisions&decision=${x.id}`} key={x.id}><strong>{x.title}</strong><small><Badge>{x.state}</Badge> {x.context.kind.replaceAll("_"," ")}{x.context.id?` · ${x.context.id.slice(0,12)}`:""}</small><small>Owner {x.scope.owner_id} · scope v{x.scope.version}</small></Link>)}{!items.length&&<p>No shared decisions yet.</p>}</aside>
 {active&&<article className="investigation-canvas panel"><header><div><span className="eyebrow">{active.context.kind.replaceAll("_"," ")} context</span><h3>{active.title}</h3><p>Decision owner <strong>{active.scope.owner_id}</strong> · scope version {active.scope.version}</p></div><Badge>{active.state}</Badge></header>
 <section><h4>Question</h4><p>{active.scope.question}</p><h4>Constraints</h4><ul>{active.scope.constraints.map(x=><li key={x}>{x}</li>)}</ul><h4>Success measures</h4><ul>{active.scope.success_measures.map(x=><li key={x}>{x}</li>)}</ul><p><strong>Deadline:</strong> {active.scope.deadline?new Date(active.scope.deadline).toLocaleDateString():"No deadline"}</p><p><strong>Participants:</strong> {active.scope.participant_ids.join(", ")}</p></section>
 {active.scope.affected_resources.length>0&&<section><h4>Affected resources</h4><ul>{active.scope.affected_resources.map((x,i)=><li key={`${x.kind}-${i}`}>{x.path&&x.repository_id?<Link href={`/repositories/${x.repository_id}?ref=${encodeURIComponent(x.ref||"")}&path=${encodeURIComponent(x.path)}`}>{x.label}</Link>:<span>{x.label}</span>} <Badge>{x.kind}</Badge></li>)}</ul></section>}
 <section><div className="section-heading"><div><h4>Evidence-backed alternatives</h4><p>Each option uses the same six criteria. Evidence is exact and time-bound; scope changes make older observations visibly stale.</p></div><Badge>{active.alternatives.length} options</Badge></div>
 <details><summary>Propose an alternative</summary><AlternativeForm repository={repository.id} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const claims=["assumption","tradeoff","risk","compatibility","cost","outcome"].map(kind=>({kind,body:f.get(kind)})).filter(x=>String(x.body||"").trim());const evidence=evidenceBody(f);const v=await mutate(`/${active.id}/alternatives`,"POST",{title:f.get("alternative_title"),claims,evidence:evidence?[evidence]:[]});if(v)form.reset()}}/></details>
 {active.comparison.length>0&&<div className="table-wrap"><table><thead><tr><th>Option</th><th>Criteria coverage</th><th>Inspectable evidence</th><th>Challenges</th></tr></thead><tbody>{active.comparison.map(row=>{const alt=active.alternatives.find(x=>x.id===row.alternative_id);return <tr key={row.alternative_id}><td><strong>{alt?.title}</strong></td><td>{row.missing_criteria.length?<>Missing: {row.missing_criteria.join(", ")}</>:"All common criteria addressed"}</td><td>{row.evidence_count} citations · {row.evidence_kinds.join(", ")||"none"}{row.stale_evidence_ids.length>0&&<><br/><Badge>{row.stale_evidence_ids.length} stale</Badge></>}</td><td>{row.dissent_count} dissenting claims</td></tr>})}</tbody></table></div>}
 {active.alternatives.map(alt=><article className="investigation-entry" key={alt.id}><header><div><h4>{alt.title}</h4><small>Proposed by {alt.created_by_id}</small></div><Badge>{alt.state}</Badge></header><dl>{alt.claims.map(claim=><div key={claim.id}><dt>{claim.kind}{claim.supersedes_id?" · superseding claim":""}</dt><dd>{claim.body}<br/><small>{claim.author_id} · {new Date(claim.created_at).toLocaleString()}</small></dd></div>)}</dl><h5>Evidence</h5><ul>{alt.evidence.map((e,i)=><li key={`${e.kind}-${i}`}><Badge>{e.kind}</Badge> {e.url?<a href={e.url}>{e.summary}</a>:e.summary} <small>observed {new Date(e.observed_at).toLocaleString()}{e.revision?` · ${e.revision.slice(0,12)}`:""}{e.path?` · ${e.path}`:""}</small></li>)}</ul>
 <details><summary>Add a claim, dissent, or newer evidence</summary><ClaimForm alternative={alt} repository={repository.id} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),ev=evidenceBody(f);const v=await mutate(`/${active.id}/alternatives/${alt.id}/claims`,"POST",{claims:[{kind:f.get("claim_kind"),body:f.get("claim_body"),supersedes_id:f.get("supersedes_id")}],evidence:ev?[ev]:[]});if(v)form.reset()}}/></details>
 <Button variant="secondary" onClick={async()=>{const r=await fetch(`/api/repositories/${repository.id}/decisions/${active.id}/alternatives/${alt.id}/agent-runs`,{method:"POST"});if(r.ok){const b=await r.json() as {worker_credential:string};setCredential(b.worker_credential)}}}>Delegate read-only research</Button>
 {alt.agent_findings.map(x=><blockquote key={x.id}><strong>{x.agent} finding:</strong> {x.body}<footer>Uncertainty: {x.uncertainty} · {x.evidence.length} retained citation(s)</footer></blockquote>)}</article>)}
 {credential&&<p className="notice"><strong>Worker credential (shown once):</strong> <code>{credential}</code><br/>It can read only the selected decision alternative and publish cited findings for 24 hours. It cannot read Git or mutate the repository.</p>}
 </section>
 <details><summary>Revise scope with attribution</summary><DecisionForm repository={repository.id} decision={active} participants={active.scope.participant_ids.join(", ")} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate(`/${active.id}`,"PATCH",{title:f.get("title"),...scopeBody(f)})}}/></details>
 <section><h4>Scope history</h4><ol className="investigation-entries">{active.history.map(x=><li key={x.version}><strong>Version {x.version}</strong> by {x.changed_by_id}<p>{x.change_summary||"Decision opened"}</p><small>{new Date(x.created_at).toLocaleString()}</small></li>)}</ol></section>
 <section><h4>Discussion</h4><ol className="investigation-entries">{active.comments.map(x=><li key={x.id}><strong>{x.author_id}</strong><p>{x.body}</p><small>{new Date(x.created_at).toLocaleString()}</small></li>)}</ol><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const v=await mutate(`/${active.id}/comments`,"POST",{body:f.get("body")});if(v)form.reset()}}><label>Add to the decision record<textarea name="body" required maxLength={65536}/></label><Button type="submit">Comment</Button></form></section></article>}</div></section>
}

function evidenceBody(f:FormData):Evidence|undefined{const summary=String(f.get("evidence_summary")||"").trim();if(!summary)return;const kind=String(f.get("evidence_kind")||"code");return {kind,repository_id:String(f.get("evidence_repository")||"")||undefined,revision:String(f.get("evidence_revision")||"")||undefined,resource_id:String(f.get("evidence_resource")||"")||undefined,path:String(f.get("evidence_path")||"")||undefined,url:String(f.get("evidence_url")||"")||undefined,summary,observed_at:new Date(String(f.get("evidence_observed")||new Date().toISOString())).toISOString()}}
function EvidenceFields({repository}:{repository:string}){return <fieldset><legend>Exact evidence (optional)</legend><label>Kind<select name="evidence_kind"><option>code</option><option>dependency</option><option>release</option><option>incident</option><option>usage</option></select></label><label>Summary<input name="evidence_summary"/></label><label>Repository ID<input name="evidence_repository" defaultValue={repository}/></label><label>Exact revision<input name="evidence_revision"/></label><label>Resource ID<input name="evidence_resource"/></label><label>Path<input name="evidence_path"/></label><label>Inspectable URL<input name="evidence_url" type="url"/></label><label>Observed at<input name="evidence_observed" type="datetime-local"/></label></fieldset>}
function AlternativeForm({onSubmit,repository}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;repository:string}){return <form onSubmit={onSubmit}><label>Alternative title<input name="alternative_title" required maxLength={200}/></label>{["assumption","tradeoff","risk","compatibility","cost","outcome"].map(x=><label key={x}>{x[0].toUpperCase()+x.slice(1)}<textarea name={x} required maxLength={4000}/></label>)}<EvidenceFields repository={repository}/><Button type="submit">Propose alternative</Button></form>}
function ClaimForm({onSubmit,repository,alternative}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;repository:string;alternative:Alternative}){return <form onSubmit={onSubmit}><label>Criterion<select name="claim_kind">{["assumption","tradeoff","risk","compatibility","cost","outcome","dissent"].map(x=><option key={x}>{x}</option>)}</select></label><label>Claim<textarea name="claim_body" required maxLength={4000}/></label><label>Supersedes claim (optional)<select name="supersedes_id"><option value="">None</option>{alternative.claims.map(x=><option value={x.id} key={x.id}>{x.kind}: {x.body.slice(0,60)}</option>)}</select></label><EvidenceFields repository={repository}/><Button type="submit">Append to record</Button></form>}

function DecisionForm({onSubmit,repository,participants,decision}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;repository:string;participants:string;decision?:Decision}){const s=decision?.scope,r=s?.affected_resources[0];return <form onSubmit={onSubmit}><label>Title<input name="title" required maxLength={200} defaultValue={decision?.title}/></label>{!decision&&<><label>Origin<select name="context_kind"><option value="repository">Repository</option><option value="proposal">Proposal</option><option value="investigation">Investigation</option><option value="incident">Incident</option><option value="evolution_plan">Evolution plan</option><option value="stewardship_opportunity">Stewardship opportunity</option></select></label><label>Origin ID (not needed for repository)<input name="context_id"/></label></>}<label className="wide">Question<textarea name="question" required maxLength={4000} defaultValue={s?.question}/></label><label>Constraints, one per line<textarea name="constraints" required defaultValue={s?.constraints.join("\n")}/></label><label>Success measures, one per line<textarea name="measures" required defaultValue={s?.success_measures.join("\n")}/></label><label>Deadline<input type="date" name="deadline" defaultValue={s?.deadline?.slice(0,10)}/></label><label>Participant IDs, comma separated<input name="participants" required defaultValue={participants}/></label><label>Decision owner ID<input name="owner" required defaultValue={s?.owner_id||participants.split(",")[0]?.trim()}/></label><fieldset><legend>Affected resource (optional)</legend><label>Label<input name="resource_label" defaultValue={r?.label}/></label><label>Kind<input name="resource_kind" defaultValue={r?.kind||"code"}/></label><input type="hidden" name="resource_repository" value={r?.repository_id||repository}/><label>Resource ID<input name="resource_id" defaultValue={r?.id}/></label><label>Revision<input name="resource_ref" defaultValue={r?.ref}/></label><label>Path<input name="resource_path" defaultValue={r?.path}/></label></fieldset>{decision&&<label>What changed?<input name="change_summary" required maxLength={500}/></label>}<Button type="submit">{decision?"Save new scope version":"Open decision"}</Button></form>}
