"use client";
import {useCallback,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";

type Component={id:string;name:string;version:string;summary:string;package_version_id:string;source_repository_id:string;source_revision:string;source_path:string;artifact_digest:string;attestation:string;requested_capabilities:string[];compatibility:{engine:string;minimum_version:string;breaking:boolean};data_use:{classes:string[];purposes:string[];retention:string;external_transfer:boolean};tests:{name:string;status:string;attestation:string}[];support:{policy:string;contact:string};publisher_subject:string;publisher_instance?:string;federation_document_digest?:string};
type Installation={id:string;current_revision:number;state:string;blockers:string[];grants_authority:boolean;revisions:{number:number;component:Component;pull_request_id:string;pull_revision:string;permissions:{requested:string;local_permission:string;resource:string}[];reason:string;decided_by:string}[]};
const health={publisher:"unchanged",trust:"trusted",peer:"available",vulnerability:"clear",compatibility:"compatible"};
export function WorkflowComponents({repository,actor}:{repository:string;actor:string}){
 const root=`/api/repositories/${repository}`,[components,setComponents]=useState<Component[]>([]),[installations,setInstallations]=useState<Installation[]>([]),[error,setError]=useState("");
 const load=useCallback(async()=>{const [c,i]=await Promise.all([fetch(`${root}/workflow-components`),fetch(`${root}/workflow-component-installations`)]);if(c.ok)setComponents((await c.json() as {items:Component[]}).items);if(i.ok)setInstallations((await i.json() as {items:Installation[]}).items)},[root]);useEffect(()=>{void load()},[load]);
 async function install(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{const payload={component_id:d.get("component"),pull_request_id:d.get("pull"),pull_revision:d.get("revision"),configuration:JSON.parse(String(d.get("configuration"))),permissions:JSON.parse(String(d.get("permissions"))),health,reason:d.get("reason")};const r=await fetch(`${root}/workflow-component-installations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){setError((await r.json() as {error:string}).error);return}setError("");await load()}catch{setError("invalid_component_installation")}}
 return <section className="investigation-workspace"><div className="section-heading"><div><p className="eyebrow">Attested practice → local authority</p><h2>Reusable workflow components</h2><p>Inspect exact provider code, evidence, data use, compatibility, support, and requested capabilities before pinning them through an ordinary pull request.</p></div><Badge>{components.length} published · {installations.length} installed</Badge></div>{error&&<p className="form-error" role="alert">{error.replaceAll("_"," ")}</p>}{components.map(c=><article className="workspace-card" key={c.id}><div className="section-heading"><div><h3>{c.name}@{c.version}</h3><p>{c.summary}</p></div><Badge>immutable</Badge></div><p><strong>Source:</strong> <code>{c.source_repository_id}@{c.source_revision}</code> · <code>{c.source_path}</code> · package <code>{c.package_version_id}</code></p><p><strong>Attestation:</strong> {c.attestation} · <code>{c.artifact_digest}</code></p><p><strong>Publisher:</strong> {c.publisher_subject}{c.publisher_instance&&` via ${c.publisher_instance}`} · federation evidence {c.federation_document_digest||"local"}</p><p><strong>Requests:</strong> {c.requested_capabilities.join(", ")} · engine {c.compatibility.engine} ≥ {c.compatibility.minimum_version}{c.compatibility.breaking?" (breaking)":""}</p><p><strong>Data:</strong> {c.data_use.classes.join(", ")||"none"} for {c.data_use.purposes.join(", ")}; retained {c.data_use.retention}; external transfer {String(c.data_use.external_transfer)}.</p><p><strong>Tests:</strong> {c.tests.map(t=>`${t.name}: ${t.status} (${t.attestation})`).join("; ")} · <strong>Support:</strong> {c.support.policy} — {c.support.contact}</p></article>)}
 {actor&&components.length>0&&<details className="workspace-card"><summary>Pin a component through a pull request</summary><form className="workspace-form" onSubmit={e=>void install(e)}><select name="component" required>{components.map(c=><option key={c.id} value={c.id}>{c.name}@{c.version}</option>)}</select><input name="pull" placeholder="Pull request ID" required/><input name="revision" placeholder="Exact pull revision" required/><textarea name="configuration" defaultValue="{}" aria-label="Non-secret local configuration JSON"/><textarea name="permissions" defaultValue="[]" aria-label="Explicit requested-to-local permission mappings JSON"/><input name="reason" placeholder="Adoption rationale" required/><Button type="submit">Pin exact component</Button></form></details>}
 {installations.map(i=>{const r=i.revisions.at(-1)!;return <article className="workspace-card" key={i.id}><div className="section-heading"><div><h3>{r.component.name}@{r.component.version}</h3><p>Installed by {r.decided_by} from {r.pull_request_id}@{r.pull_revision}</p></div><Badge>{i.state} · revision {i.current_revision}</Badge></div><p><strong>Mapped local authority:</strong> {r.permissions.map(p=>`${p.requested} → ${p.local_permission} on ${p.resource}`).join("; ")}. Installation grants authority: {String(i.grants_authority)}.</p>{i.blockers.length>0&&<p><strong>Visible blockers:</strong> {i.blockers.join(", ")}</p>}<details><summary>Retained pin history</summary><ol>{i.revisions.map(h=><li key={h.number}>r{h.number}: {h.component.name}@{h.component.version}, {h.pull_revision} — {h.reason}</li>)}</ol></details></article>})}</section>
}
