"use client";
import {useCallback,useEffect,useState} from "react";
import {Badge,Button} from "@/components/ui";

type Diagnostic={kind:string;subject:string;detail:string;attributed_to:string[];blocking:boolean};
type Version={number:number;name:string;outcome:string;repository_revision:string;definition_path:string;triggers:{id:string;type:string;event:string;conditions:string[]}[];steps:{id:string;name:string;needs:string[];conditions:string[];invocation:{kind:string;reference:string;revision:string;owner_ids:string[];capabilities:string[]};retry:{maximum_attempts:number;backoff_seconds:number};timeout_seconds:number;maximum_cost:number;completion_criteria:string[]}[];maximum_cost:number;currency:string;owner_ids:string[];completion_criteria:string[];change_reason:string;author_id:string;published_at:string};
type Workflow={id:string;current_version:number;versions:Version[];event_subscriptions:string[];effective_authority:{capabilities:string[];resources:string[];owner_ids:string[];grants_authority:boolean};diagnostics:Diagnostic[];state:string};
const starter=JSON.stringify({triggers:[{id:"issue-accepted",type:"repository_event",event:"issue.accepted",conditions:["issue.labels contains repair"],input_mappings:{issue_id:"event.issue_id"}}],inputs:[{name:"issue_id",type:"string",required:true,description:"Accepted issue"}],steps:[{id:"prepare",name:"Prepare bounded repair",needs:[],conditions:["inputs.issue_id is present"],inputs:{issue_id:"workflow.issue_id"},outputs:[{name:"proposal_id",type:"string",required:true,description:"Draft proposal"}],invocation:{kind:"approved_agent",reference:"repair-agent",revision:"agent-release-v1",accessible:true,owner_ids:["owner"],capabilities:["proposal:draft"],emits:["proposal.drafted"]},retry:{maximum_attempts:2,backoff_seconds:30},timeout_seconds:900,maximum_cost:5,optional:false,completion_criteria:["draft cites the accepted issue"]}],outputs:[{name:"proposal_id",type:"string",required:true,description:"Prepared proposal"}],maximum_cost:5,currency:"USD",owner_ids:["owner"],completion_criteria:["a reviewable repair proposal exists"],policies:[{id:"draft-only",effect:"allow",capability:"proposal:draft",owner_ids:["owner"]}]},null,2);
const bodyOf=(v:Version)=>JSON.stringify(Object.fromEntries(Object.entries(v).filter(([k])=>!["number","name","outcome","repository_revision","definition_path","change_reason","author_id","published_at"].includes(k))),null,2);

export function WorkflowDefinitions({repository,actor}:{repository:string;actor:string}){
 const root=`/api/repositories/${repository}/workflow-definitions`,[items,setItems]=useState<Workflow[]>([]),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(root);if(r.ok)setItems((await r.json() as {items:Workflow[]}).items)},[root]);useEffect(()=>{void load()},[load]);
 async function submit(e:React.FormEvent<HTMLFormElement>,x?:Workflow){e.preventDefault();const d=new FormData(e.currentTarget);try{const payload={...JSON.parse(String(d.get("definition"))) as object,name:d.get("name"),outcome:d.get("outcome"),repository_revision:d.get("repository_revision"),definition_path:d.get("definition_path"),change_reason:d.get("change_reason"),...(x?{expected_version:x.current_version}:{})};const r=await fetch(x?`${root}/${x.id}/versions`:root,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){setError((await r.json() as {error:string}).error);return}setError("");await load()}catch{setError("invalid_workflow_json")}}
 async function activate(x:Workflow){const r=await fetch(`${root}/${x.id}/activation`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({version:x.current_version})});if(!r.ok){setError((await r.json() as {error:string}).error)}else{setError("");await load()}}
 const form=(x?:Workflow)=>{const v=x?.versions.at(-1);return <form className="workspace-form" onSubmit={e=>void submit(e,x)}><input name="name" defaultValue={v?.name} placeholder="Workflow name" required/><textarea name="outcome" defaultValue={v?.outcome} placeholder="Shared outcome" required/><input name="repository_revision" defaultValue={v?.repository_revision} placeholder="Reviewed commit revision" required/><input name="definition_path" defaultValue={v?.definition_path} placeholder="Workflow configuration path" required/><textarea name="definition" defaultValue={v?bodyOf(v):starter} rows={24} aria-label="Typed workflow definition as JSON" required/><input name="change_reason" placeholder="Reason for this version" required/><Button type="submit">{x?`Publish version ${x.current_version+1}`:"Publish workflow"}</Button></form>};
 return <section className="investigation-workspace"><div className="section-heading"><div><p className="eyebrow">Reviewed events → bounded collaboration</p><h2>Workflow definitions</h2><p>Explain what reacts, why it runs, its graph and limits, whose authority is requested, and what completion means before activation.</p></div><Badge>{items.length} workflows</Badge></div>{error&&<p className="form-error" role="alert">{error.replaceAll("_"," ")}</p>}{actor&&<details className="workspace-card"><summary>Define a versioned workflow</summary>{form()}</details>}{items.map(x=>{const v=x.versions.at(-1)!;return <article className="workspace-card" key={x.id}><div className="section-heading"><div><h3>{v.name}</h3><p>{v.outcome}</p></div><Badge>{x.state} · v{v.number}</Badge></div><p><strong>Reviewed source:</strong> <code>{v.repository_revision}</code> · <code>{v.definition_path}</code></p><p><strong>Subscriptions:</strong> {x.event_subscriptions.join(", ")} · <strong>Owners:</strong> {v.owner_ids.join(", ")}</p><p><strong>Effective authority requested:</strong> {x.effective_authority.capabilities.join(", ")||"none"}; resources {x.effective_authority.resources.join(", ")}. Definition grants authority: {String(x.effective_authority.grants_authority)}.</p><p><strong>Budget:</strong> {v.maximum_cost} {v.currency} · <strong>Completion:</strong> {v.completion_criteria.join("; ")}</p><ol>{v.steps.map(s=><li key={s.id}><strong>{s.name}</strong> ({s.invocation.kind}: {s.invocation.reference}@{s.invocation.revision}) after {s.needs.join(", ")||"trigger"}; {s.retry.maximum_attempts} attempts, {s.timeout_seconds}s, {s.maximum_cost} {v.currency}. Done when {s.completion_criteria.join("; ")}.</li>)}</ol>{x.diagnostics.length>0&&<><h4>Activation blockers</h4><ul>{x.diagnostics.map((d,i)=><li key={i}><Badge>{d.kind}</Badge> {d.subject}: {d.detail} — {d.attributed_to.join(", ")||"unowned"}</li>)}</ul></>}{actor&&x.state!=="active"&&<Button onClick={()=>void activate(x)} disabled={x.diagnostics.length>0}>Activate exact version</Button>}<details><summary>Revise and review history</summary>{actor&&form(x)}<ol>{x.versions.map(h=><li key={h.number}>v{h.number}: {h.change_reason} by {h.author_id}</li>)}</ol></details></article>})}</section>
}
