"use client";

import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Badge, Button } from "@/components/ui";
import { Book, Branch, Check, ChevronRight, Clock, Code, Copy, Edit, File, Folder, Lightbulb, MessageCircle, Plus } from "@/components/icons";

type Repository = { id:string; owner_id:string; name:string; description:string; visibility:"public"|"private"; empty:boolean; git_url:string; updated_at:string };
type BranchRecord = { name:string; commit_id:string; is_default:boolean };
type Branches = { items:BranchRecord[]; default_branch:string };
type Commit = { id:string; parent_ids:string[]; author:string; email:string; authored_at?:string; message:string };
type TreeEntry = { name:string; path:string; type:"tree"|"blob"|"commit"; mode:number; object_id:string; size?:number };
type Tree = { revision:string; commit_id:string; path:string; tree_id:string; entries:TreeEntry[] };
type Blob = { revision:string; commit_id:string; path:string; object_id:string; size:number; binary:boolean; truncated:boolean; content:string };
type Commits = { items:Commit[]; revision:string; commit_id:string; total_count:number };
type Proposal = { id:string; repository_id:string; author_id:string; title:string; body:string; state:"open"|"closed"; created_at:string; updated_at:string; closed_at?:string; closed_by_id?:string };
type ProposalComment = { id:string; proposal_id:string; author_id:string; body:string; created_at:string };
type ProposalList = { items:Proposal[]; total_count:number };
type CommentList = { items:ProposalComment[]; total_count:number };

async function get<T>(path:string):Promise<T> { const response = await fetch(`/api${path}`); if (!response.ok) throw new Error(response.status === 401 ? "Sign in to view this private repository." : "This repository state could not be found."); return response.json(); }
async function send<T>(path:string, method:string, body:unknown):Promise<T> { const response = await fetch(`/api${path}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); if (!response.ok) { const result = await response.json().catch(()=>({})) as {error?:string}; throw new Error(response.status === 401 ? "Sign in with repository access to continue." : result.error === "invalid_proposal" ? "Add a title of 200 characters or fewer." : result.error === "invalid_comment" ? "Write a comment before posting." : "This action is not available to your account."); } return response.json(); }
const short = (id:string) => id.slice(0,7);
const summary = (message:string) => message.split("\n")[0] || "Untitled commit";
const formatSize = (size:number) => size < 1024 ? `${size} B` : `${(size/1024).toFixed(1)} KB`;

export default function RepositoryPage({ params, searchParams }: { params:Promise<{id:string}>; searchParams:Promise<{ref?:string;path?:string;view?:string;proposal?:string;state?:string;q?:string}> }) {
  const { id } = use(params); const query = use(searchParams); const router = useRouter();
  const revision = query.ref ?? ""; const path = query.path ?? ""; const view = query.view === "commits" ? "commits" : query.view === "proposals" ? "proposals" : "code";
  const [repository,setRepository] = useState<Repository>(); const [branches,setBranches] = useState<Branches>();
  const [tree,setTree] = useState<Tree>(); const [blob,setBlob] = useState<Blob>(); const [commits,setCommits] = useState<Commits>();
  const [error,setError] = useState(""); const [copied,setCopied] = useState(false);
  const ref = revision || branches?.default_branch || "";

  const load = useCallback(async () => {
    setError("");
    try {
      const [repo,branchData] = await Promise.all([get<Repository>(`/repositories/${id}`),get<Branches>(`/repositories/${id}/branches`)]);
      setRepository(repo); setBranches(branchData);
      const selected = revision || branchData.default_branch;
      if (view === "proposals" || repo.empty || !selected) { setTree(undefined); setBlob(undefined); setCommits(undefined); return; }
      if (view === "commits") { setCommits(await get<Commits>(`/repositories/${id}/commits?ref=${encodeURIComponent(selected)}&per_page=100`)); setTree(undefined); setBlob(undefined); }
      else if (path) {
        try { setBlob(await get<Blob>(`/repositories/${id}/blob?ref=${encodeURIComponent(selected)}&path=${encodeURIComponent(path)}`)); setTree(undefined); }
        catch { setTree(await get<Tree>(`/repositories/${id}/tree?ref=${encodeURIComponent(selected)}&path=${encodeURIComponent(path)}`)); setBlob(undefined); }
        setCommits(undefined);
      } else { setTree(await get<Tree>(`/repositories/${id}/tree?ref=${encodeURIComponent(selected)}`)); setBlob(undefined); setCommits(undefined); }
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Repository unavailable."); }
  },[id,path,revision,view]);
  useEffect(() => {
    // Repository state follows the shareable revision/path URL.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);

  function navigate(next:{ref?:string;path?:string;view?:string}) { const values = new URLSearchParams(); const nextView = next.view ?? view; if (nextView !== "proposals") { const nextRef = next.ref ?? ref; if (nextRef) values.set("ref",nextRef); const nextPath = next.path ?? path; if (nextPath) values.set("path",nextPath); } if (nextView !== "code") values.set("view",nextView); router.push(`/repositories/${id}?${values}`); }
  const clone = repository ? `${process.env.NEXT_PUBLIC_GIT_ORIGIN ?? "http://localhost:8080"}${repository.git_url}` : "";
  async function copyClone() { await navigator.clipboard.writeText(clone); setCopied(true); setTimeout(()=>setCopied(false),1600); }

  if (error) return <RepositoryFrame><section className="repository-error panel"><Book/><h1>Repository unavailable</h1><p>{error}</p><Link href="/">Return to workspace</Link></section></RepositoryFrame>;
  if (!repository || !branches) return <RepositoryFrame><div className="repository-loading">Reading repository state…</div></RepositoryFrame>;
  const contextCommit = tree?.commit_id ?? blob?.commit_id ?? commits?.commit_id;
  return <RepositoryFrame>
    <header className="repository-heading"><div className="repository-title"><span className="repo-icon"><Book/></span><div><div className="repository-owner"><Link href="/">Workspace</Link><ChevronRight size={13}/><strong>{repository.name}</strong><Badge>{repository.visibility === "public" ? "Public" : "Private"}</Badge></div><h1>{repository.name}</h1><p>{repository.description || "No description has been added yet."}</p></div></div><div className="clone-control"><code>{clone}</code><Button variant="secondary" size="sm" onClick={copyClone}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?"Copied":"Clone"}</Button></div></header>
    <nav className="repository-tabs" aria-label="Repository"><button className={view === "code"?"active":""} onClick={()=>navigate({view:"code",path:""})}><Code size={15}/>Code</button><button className={view === "commits"?"active":""} onClick={()=>navigate({view:"commits",path:""})}><Clock size={15}/>Commits</button><button className={view === "proposals"?"active":""} onClick={()=>navigate({view:"proposals",path:""})}><Lightbulb size={15}/>Proposals</button></nav>
    {view === "proposals" ? <ProposalWorkspace repository={id} owner={repository.owner_id} selected={query.proposal} initialState={query.state} initialQuery={query.q} /> : repository.empty ? <section className="empty-repository panel"><Branch/><h2>This repository is ready for its first push</h2><p>Clone it, add project files and a README, then push the <code>{branches.default_branch}</code> branch.</p><pre><code>{`git clone ${clone}\ncd ${repository.name}\ngit push origin ${branches.default_branch}`}</code></pre></section> : <>
      <div className="revision-bar panel"><label><Branch size={15}/><span className="sr-only">Branch</span><select value={ref} onChange={event=>navigate({ref:event.target.value,path:""})}>{branches.items.map(branch=><option key={branch.name}>{branch.name}</option>)}</select></label><div><span>Viewing</span><strong>{ref}</strong>{contextCommit&&<><span>at</span><code>{short(contextCommit)}</code></>}</div><span className="revision-note">Branch and revision stay attached to every path.</span></div>
      {view === "commits" && commits ? <CommitList commits={commits.items} repository={id} refName={ref}/> : blob ? <BlobView blob={blob} onCrumb={next=>navigate({path:next})}/> : tree ? <TreeView tree={tree} onPath={next=>navigate({path:next})}/> : <div className="repository-loading">Loading revision…</div>}
    </>}
  </RepositoryFrame>;
}

function RepositoryFrame({children}:{children:React.ReactNode}) { return <div className="repository-page"><a className="skip-link" href="#main-content">Skip to repository content</a><header className="repository-topbar"><Link className="brand" href="/"><span className="brand-mark">K</span><span>Kanso</span></Link><Link href="/" className="back-workspace">Your workspace</Link></header><main id="main-content" className="repository-main">{children}</main></div>; }
function Breadcrumbs({path,onCrumb}:{path:string;onCrumb:(path:string)=>void}) { const parts=path.split("/").filter(Boolean); return <nav className="breadcrumbs" aria-label="File path"><button onClick={()=>onCrumb("")}>root</button>{parts.map((part,index)=><span key={`${part}-${index}`}><ChevronRight size={12}/><button onClick={()=>onCrumb(parts.slice(0,index+1).join("/"))}>{part}</button></span>)}</nav>; }
function TreeView({tree,onPath}:{tree:Tree;onPath:(path:string)=>void}) { return <section className="file-browser panel"><div className="browser-header"><Breadcrumbs path={tree.path} onCrumb={onPath}/><code>{tree.entries.length} items · {short(tree.tree_id)}</code></div>{tree.entries.length ? <div className="file-list">{tree.entries.map(entry=><button key={entry.path} onClick={()=>onPath(entry.path)}><span className={entry.type === "tree"?"folder-icon":"file-icon"}>{entry.type === "tree"?<Folder size={16}/>:<File size={16}/>}</span><strong>{entry.name}</strong><span>{entry.type === "tree"?"Directory":formatSize(entry.size??0)}</span><code>{short(entry.object_id)}</code></button>)}</div>:<p className="empty-directory">This directory is empty.</p>}</section>; }
function BlobView({blob,onCrumb}:{blob:Blob;onCrumb:(path:string)=>void}) { const lines=blob.content.split("\n"); return <section className="blob-browser"><div className="browser-header panel"><Breadcrumbs path={blob.path} onCrumb={onCrumb}/><span>{formatSize(blob.size)} · <code>{short(blob.object_id)}</code></span></div>{blob.binary?<div className="binary-file panel"><File/><h2>Binary file</h2><p>This file cannot be displayed, but its identity and size are preserved above.</p></div>:<div className="code-view panel">{lines.map((line,index)=><div className="code-line" key={index}><span>{index+1}</span><code>{line || " "}</code></div>)}{blob.truncated&&<p className="truncated">Preview limited to the first 1 MB.</p>}</div>}</section>; }
function CommitList({commits,repository,refName}:{commits:Commit[];repository:string;refName:string}) { return <section className="commit-list panel"><div className="browser-header"><strong>{commits.length} commits on {refName}</strong><span>Newest reachable work first</span></div>{commits.map(commit=><article key={commit.id}><span className="commit-node"><Clock size={14}/></span><div><h2>{summary(commit.message)}</h2><p>{commit.author || "Unknown author"}{commit.authored_at&&<> committed <time dateTime={commit.authored_at}>{new Date(commit.authored_at).toLocaleString()}</time></>}</p></div><Link href={`/repositories/${repository}?ref=${commit.id}`}><code>{short(commit.id)}</code></Link></article>)}</section>; }

function ProposalWorkspace({repository,owner,selected,initialState,initialQuery}:{repository:string;owner:string;selected?:string;initialState?:string;initialQuery?:string}) {
  const router=useRouter(); const state=initialState === "closed" ? "closed" : initialState === "all" ? "all" : "open"; const [query,setQuery]=useState(initialQuery??"");
  const [items,setItems]=useState<Proposal[]>([]); const [proposal,setProposal]=useState<Proposal>(); const [comments,setComments]=useState<ProposalComment[]>([]); const [actor,setActor]=useState(""); const [loading,setLoading]=useState(true); const [creating,setCreating]=useState(false); const [editing,setEditing]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{ setLoading(true); setError(""); try { const session=fetch("/api/session").then(async response=>response.ok ? ((await response.json()) as {user:{id:string}}).user.id : "").catch(()=>""); if(selected){ const [item,conversation,user]=await Promise.all([get<Proposal>(`/repositories/${repository}/proposals/${selected}`),get<CommentList>(`/repositories/${repository}/proposals/${selected}/comments?per_page=100`),session]); setProposal(item); setComments(conversation.items); setActor(user); } else { const suffix=state === "all" ? "" : `&state=${state}`; const [list,user]=await Promise.all([get<ProposalList>(`/repositories/${repository}/proposals?per_page=100${suffix}`),session]); setItems(list.items); setProposal(undefined); setActor(user); } } catch(cause){setError(cause instanceof Error?cause.message:"Proposals unavailable.");} finally {setLoading(false);} },[repository,selected,state]);
  useEffect(()=>{
    // Proposal state follows the shareable state/query/detail URL.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  function go(next:{proposal?:string;state?:string;q?:string}){const values=new URLSearchParams({view:"proposals"});const nextState=next.state??state;if(nextState!=="open")values.set("state",nextState);const nextQuery=next.q??query;if(nextQuery)values.set("q",nextQuery);if(next.proposal)values.set("proposal",next.proposal);router.push(`/repositories/${repository}?${values}`);}
  const filtered=items.filter(item=>!query||`${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase()));
  if(loading)return <div className="repository-loading">Reading proposal context…</div>;
  if(error)return <section className="proposal-notice panel"><Lightbulb/><h2>Proposals unavailable</h2><p>{error}</p><Button variant="secondary" onClick={()=>void load()}>Try again</Button></section>;
  if(proposal)return <ProposalDetail item={proposal} comments={comments} repository={repository} canDiscuss={Boolean(actor)} canEdit={actor===proposal.author_id||actor===owner} onBack={()=>go({state})} onChanged={()=>void load()} editing={editing} setEditing={setEditing}/>;
  return <section className="proposal-workspace"><header className="proposal-toolbar"><div><p className="eyebrow"><Lightbulb size={14}/>Shared context</p><h2>Proposals</h2><p>Search what collaborators have already explored before starting overlapping work.</p></div>{actor&&<Button onClick={()=>setCreating(value=>!value)}><Plus size={14}/>{creating?"Cancel":"New proposal"}</Button>}</header>
    {creating&&<ProposalForm title="Start with the problem" submit="Create proposal" onCancel={()=>setCreating(false)} onSubmit={async(title,body)=>{const created=await send<Proposal>(`/repositories/${repository}/proposals`,"POST",{title,body});go({proposal:created.id});}}/>}
    <div className="proposal-filters panel"><label><span className="sr-only">Search proposals</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} onBlur={()=>go({q:query})} placeholder="Search titles and descriptions…"/></label><div role="group" aria-label="Proposal state">{(["open","closed","all"] as const).map(value=><button key={value} className={state===value?"active":""} onClick={()=>go({state:value,q:query})}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div>
    <div className="proposal-list panel">{filtered.length?filtered.map(item=><button key={item.id} onClick={()=>go({proposal:item.id})}><span className={`proposal-state ${item.state}`}><Lightbulb size={16}/></span><span><strong>{item.title}</strong><p>{item.body||"No description was added."}</p><small>Opened {new Date(item.created_at).toLocaleDateString()} · updated {new Date(item.updated_at).toLocaleDateString()}</small></span><ChevronRight size={16}/></button>):<div className="proposal-empty"><Lightbulb/><h3>{query?"No matching context":"No proposals here yet"}</h3><p>{query?"Try another phrase or state filter.":"Start a proposal so the next collaborator can discover the reasoning before duplicating work."}</p></div>}</div>
  </section>;
}

function ProposalForm({title,body="",submit,onCancel,onSubmit}:{title:string;body?:string;submit:string;onCancel:()=>void;onSubmit:(title:string,body:string)=>Promise<void>}){const [name,setName]=useState(title);const [description,setDescription]=useState(body);const [error,setError]=useState("");const [busy,setBusy]=useState(false);return <form className="proposal-form panel" onSubmit={async event=>{event.preventDefault();setBusy(true);setError("");try{await onSubmit(name,description);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save proposal.");setBusy(false);}}}><label>Title<input required maxLength={200} value={name} onChange={event=>setName(event.target.value)} placeholder="What should collaborators consider?"/></label><label>Description<textarea maxLength={65536} value={description} onChange={event=>setDescription(event.target.value)} placeholder="Describe the motivation, constraints, and desired outcome."/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={busy}>{busy?"Saving…":submit}</Button></div></form>}

function ProposalDetail({item,comments,repository,canDiscuss,canEdit,onBack,onChanged,editing,setEditing}:{item:Proposal;comments:ProposalComment[];repository:string;canDiscuss:boolean;canEdit:boolean;onBack:()=>void;onChanged:()=>void;editing:boolean;setEditing:(value:boolean)=>void}){const [comment,setComment]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);return <section className="proposal-detail"><button className="proposal-back" onClick={onBack}>← All proposals</button><header className="proposal-detail-heading"><div><span className={`proposal-status ${item.state}`}><Lightbulb size={14}/>{item.state}</span><h2>{item.title}</h2><p>Opened {new Date(item.created_at).toLocaleString()} by <code>{short(item.author_id)}</code></p></div>{item.state==="open"&&canEdit&&<div><Button variant="secondary" size="sm" onClick={()=>setEditing(!editing)}><Edit size={13}/>Edit</Button><Button variant="secondary" size="sm" onClick={async()=>{setError("");try{await send(`/repositories/${repository}/proposals/${item.id}`,"PATCH",{state:"closed"});onChanged();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to close proposal.");}}}><Check size={13}/>Close</Button></div>}</header>{error&&<p className="form-error">{error}</p>}
    {editing?<ProposalForm title={item.title} body={item.body} submit="Save changes" onCancel={()=>setEditing(false)} onSubmit={async(title,body)=>{await send(`/repositories/${repository}/proposals/${item.id}`,"PATCH",{title,body});setEditing(false);onChanged();}}/>:<article className="proposal-body panel"><div className="proposal-author"><span className="avatar sm">{item.author_id.slice(0,2).toUpperCase()}</span><span><strong>Proposal author</strong><small>{new Date(item.created_at).toLocaleString()}</small></span></div><div>{item.body?<p>{item.body}</p>:<p className="muted">No description was added.</p>}</div></article>}
    <div className="conversation-heading"><MessageCircle size={16}/><h3>Conversation</h3><span>{comments.length}</span></div><div className="proposal-comments">{comments.map(entry=><article className="panel" key={entry.id}><div className="proposal-author"><span className="avatar sm">{entry.author_id.slice(0,2).toUpperCase()}</span><span><strong>Collaborator <code>{short(entry.author_id)}</code></strong><small>{new Date(entry.created_at).toLocaleString()}</small></span></div><p>{entry.body}</p></article>)}{!comments.length&&<p className="no-comments">No replies yet. Add a question or context that moves the idea forward.</p>}</div>
    {item.state==="open"&&canDiscuss?<form className="comment-form panel" onSubmit={async event=>{event.preventDefault();setBusy(true);setError("");try{await send(`/repositories/${repository}/proposals/${item.id}/comments`,"POST",{body:comment});setComment("");onChanged();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to post comment.");}finally{setBusy(false);}}}><label><strong>Join the conversation</strong><textarea required value={comment} onChange={event=>setComment(event.target.value)} placeholder="Ask a question, share a constraint, or suggest a next step."/></label><div className="form-actions"><Button type="submit" disabled={busy}>{busy?"Posting…":"Comment"}</Button></div></form>:item.state==="closed"?<div className="closed-note panel"><Check size={16}/><span><strong>This proposal is closed.</strong> Its context and conversation remain available for future work.</span></div>:<div className="closed-note panel"><MessageCircle size={16}/><span><strong>Sign in to participate.</strong> Public context remains available to everyone.</span></div>}
  </section>}
